Repository OCA/edi, pull requests merged in 2020-07, with the labels that each got.

#217 10 FIX travis
  .travis.yml
Labels: approved

#201 [13.0][MIG] sale_order_import
  oca_dependencies.txt
  sale_order_import/README.rst
  sale_order_import/__init__.py
  sale_order_import/__manifest__.py
  sale_order_import/i18n/es.po
  sale_order_import/i18n/fr.po
  sale_order_import/i18n/sale_order_import.pot
  sale_order_import/models/__init__.py
  sale_order_import/models/sale.py
  sale_order_import/readme/CONTRIBUTORS.rst
  sale_order_import/readme/DESCRIPTION.rst
  sale_order_import/readme/USAGE.rst
  sale_order_import/static/description/icon.png
  sale_order_import/static/description/index.html
  sale_order_import/tests/__init__.py
  sale_order_import/tests/test_order_import.py
  sale_order_import/tests/test_sale_order.py
  sale_order_import/wizard/__init__.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_import/wizard/sale_order_import_view.xml
  setup/sale_order_import/odoo/addons/sale_order_import
  setup/sale_order_import/setup.py
Labels: bot is merging ⏳

#202 [13.0][MIG] sale_order_import_ubl
  sale_order_import_ubl/README.rst
  sale_order_import_ubl/__init__.py
  sale_order_import_ubl/__manifest__.py
  sale_order_import_ubl/demo/demo_data.xml
  sale_order_import_ubl/i18n/sale_order_import_ubl.pot
  sale_order_import_ubl/readme/CONTRIBUTORS.rst
  sale_order_import_ubl/readme/DESCRIPTION.rst
  sale_order_import_ubl/readme/USAGE.rst
  sale_order_import_ubl/static/description/icon.png
  sale_order_import_ubl/static/description/index.html
  sale_order_import_ubl/tests/__init__.py
  sale_order_import_ubl/tests/files/UBL-Order-2.0-Example.xml
  sale_order_import_ubl/tests/files/UBL-Order-2.1-Example.xml
  sale_order_import_ubl/tests/files/UBL-RequestForQuotation-2.0-Example.xml
  sale_order_import_ubl/tests/files/UBL-RequestForQuotation-2.1-Example.xml
  sale_order_import_ubl/tests/test_ubl_order_import.py
  sale_order_import_ubl/wizard/__init__.py
  sale_order_import_ubl/wizard/sale_order_import.py
  setup/sale_order_import_ubl/odoo/addons/sale_order_import_ubl
  setup/sale_order_import_ubl/setup.py
Labels: approved, bot is merging ⏳

#220 FIX example xml files: disable pylint
  account_invoice_import_ubl/tests/files/UBLKetentest_Referentiefactuur_20150100.xml
  sale_order_import_ubl/tests/files/UBL-Order-2.0-Example.xml
  sale_order_import_ubl/tests/files/UBL-Order-2.0-Example_no-party-name.xml
  sale_order_import_ubl/tests/files/UBL-RequestForQuotation-2.0-Example.xml
  sale_order_import_ubl/tests/files/UBL-RequestForQuotation-2.1-Example.xml
Labels: bot is merging ⏳
