Repository OCA/edi, pull requests merged in 2020-12, with the labels that each got.

#263 [ADD] edi_account
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/models/edi_exchange_type.py
  edi/views/edi_exchange_record_views.xml
  edi/views/edi_exchange_type_views.xml
  edi_account/README.rst
  edi_account/__init__.py
  edi_account/__manifest__.py
  edi_account/models/__init__.py
  edi_account/models/account_move.py
  edi_account/readme/CONTRIBUTORS.rst
  edi_account/readme/DESCRIPTION.rst
  edi_account/static/description/icon.png
  edi_account/static/description/index.html
  edi_account/tests/__init__.py
  edi_account/tests/test_edi.py
  edi_account/views/account_journal.xml
  edi_account/views/account_move.xml
  edi_account/views/res_partner.xml
Labels: approved, bot is merging ⏳

#270 [13.0] EDI Misc improvements
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi_storage/components/check.py
  edi_storage/tests/common.py
Labels: bot is merging ⏳

#271 [13.0] EDI refactor ack handling w/ its own type
  edi/models/edi_exchange_record.py
  edi/models/edi_exchange_type.py
  edi/tests/common.py
  edi/tests/test_record.py
  edi/views/edi_exchange_record_views.xml
  edi/views/edi_exchange_type_views.xml
  edi_storage/components/check.py
  edi_storage/tests/common.py
  edi_storage/tests/test_edi_backend_storage.py
Labels: bot is merging ⏳

#275 [13.0] edi: misc improvements
  edi/__manifest__.py
  edi/components/__init__.py
  edi/components/base_input.py
  edi/components/base_validate.py
  edi/exceptions.py
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/models/edi_exchange_type.py
  edi/security/res_groups.xml
  edi/tests/__init__.py
  edi/tests/fake_components.py
  edi/tests/test_backend_base.py
  edi/tests/test_backend_input.py
  edi/tests/test_backend_output.py
  edi/tests/test_backend_process.py
  edi/tests/test_backend_type.py
  edi/tests/test_backend_validate.py
  edi/tests/test_exchange_type.py
  edi/views/edi_exchange_type_views.xml
  edi_exchange_template/models/edi_exchange_template_output.py
  edi_exchange_template/tests/test_edi_backend_output.py
  edi_xml/README.rst
  edi_xml/__init__.py
  edi_xml/__manifest__.py
  edi_xml/components/__init__.py
  edi_xml/components/xml_handler.py
  edi_xml/readme/CONTRIBUTORS.rst
  edi_xml/readme/DESCRIPTION.rst
  edi_xml/tests/__init__.py
  edi_xml/tests/common.py
  edi_xml/tests/fixtures/Test.xsd
  edi_xml/tests/test_xml.py
  edi_xml/xmler.py
  requirements.txt
  setup/edi_xml/odoo/addons/edi_xml
  setup/edi_xml/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#268 [IMP] edi: Security
  edi/models/edi_exchange_consumer_mixin.py
  edi/models/edi_exchange_record.py
  edi/security/ir_model_access.xml
  edi/tests/__init__.py
  edi/tests/fake_models.py
  edi/tests/test_security.py
Labels: bot is merging ⏳

#283 [FIX] edi: Rule not correctly created
  edi/security/ir_model_access.xml
Labels: approved, bot is merging ⏳

#274 [IMP] edi: Detection of Pending Manual EDIs and adding it to form view
  edi/README.rst
  edi/__init__.py
  edi/__manifest__.py
  edi/models/edi_exchange_consumer_mixin.py
  edi/models/edi_exchange_type.py
  edi/readme/CONFIGURE.rst
  edi/readme/DESCRIPTION.rst
  edi/readme/USAGE.rst
  edi/static/description/index.html
  edi/static/src/js/widget_edi.js
  edi/static/src/xml/widget_edi.xml
  edi/templates/assets.xml
  edi/templates/exchange_mixin_buttons.xml
  edi/tests/test_consumer_mixin.py
  edi/views/edi_exchange_type_views.xml
  edi/wizards/__init__.py
  edi/wizards/edi_exchange_record_create.py
  edi/wizards/edi_exchange_record_create.xml
Labels: approved, bot is merging ⏳, ready to merge

#223 8.0 supplier_inventory_import_ubl: misc improvements
  supplier_inventory_import_ubl/demo/product.xml
  supplier_inventory_import_ubl/models/product.py
  supplier_inventory_import_ubl/tests/inventory_report_sample/same_barcode.xml
  supplier_inventory_import_ubl/tests/test_import.py
  supplier_inventory_import_ubl/views/product_view.xml
  supplier_inventory_import_ubl/wizards/inventory_import.py
Labels: approved, bot is merging ⏳

#292 EDI: Some fixes
  edi/models/edi_exchange_consumer_mixin.py
Labels: approved, bot is merging ⏳

#294 8.0 FIX crash when pivot format had a 'note' key (and no attachment) backport from v10
  base_business_document_import/models/business_document_import.py
  sale_order_import/wizard/sale_order_import.py
Labels: bot is merging ⏳

#291 [13.0][FIX] account_invoice_ubl_email_attachment: attach only the most recently generated UBL file
  account_invoice_ubl_email_attachment/models/mail_template.py
Labels: approved, bot is merging ⏳, ready to merge
