Repository OCA/edi, pull requests merged in 2020-11, with the labels that each got.

#233 [13.0][MIG] account_invoice_ubl_email_attachment
  account_invoice_ubl_email_attachment/README.rst
  account_invoice_ubl_email_attachment/__init__.py
  account_invoice_ubl_email_attachment/__manifest__.py
  account_invoice_ubl_email_attachment/i18n/account_invoice_ubl_email_attachment.pot
  account_invoice_ubl_email_attachment/i18n/de.po
  account_invoice_ubl_email_attachment/i18n/hr.po
  account_invoice_ubl_email_attachment/i18n/nl.po
  account_invoice_ubl_email_attachment/models/__init__.py
  account_invoice_ubl_email_attachment/models/account_move.py
  account_invoice_ubl_email_attachment/models/mail_template.py
  account_invoice_ubl_email_attachment/models/res_company.py
  account_invoice_ubl_email_attachment/models/res_config_settings.py
  account_invoice_ubl_email_attachment/readme/CONFIGURE.rst
  account_invoice_ubl_email_attachment/readme/CONTRIBUTORS.rst
  account_invoice_ubl_email_attachment/readme/DESCRIPTION.rst
  account_invoice_ubl_email_attachment/readme/USAGE.rst
  account_invoice_ubl_email_attachment/static/description/icon.png
  account_invoice_ubl_email_attachment/static/description/index.html
  account_invoice_ubl_email_attachment/tests/__init__.py
  account_invoice_ubl_email_attachment/tests/test_ubl_email_attachment.py
  account_invoice_ubl_email_attachment/views/res_config_settings.xml
Labels: approved, bot is merging ⏳, ready to merge

#207 [13.0][ADD] base_ebill_payment_contract
  base_ebill_payment_contract/__init__.py
  base_ebill_payment_contract/__manifest__.py
  base_ebill_payment_contract/demo/ebill_payment_contract.xml
  base_ebill_payment_contract/models/__init__.py
  base_ebill_payment_contract/models/ebill_payment_contract.py
  base_ebill_payment_contract/models/res_partner.py
  base_ebill_payment_contract/readme/CONTRIBUTORS.rst
  base_ebill_payment_contract/readme/DESCRIPTION.rst
  base_ebill_payment_contract/readme/USAGE.rst
  base_ebill_payment_contract/security/ir.model.access.csv
  base_ebill_payment_contract/static/description/icon.png
  base_ebill_payment_contract/tests/__init__.py
  base_ebill_payment_contract/tests/test_base_ebill_payment_contract.py
  base_ebill_payment_contract/views/ebill_payment_contract.xml
  setup/base_ebill_payment_contract/odoo/addons/base_ebill_payment_contract
  setup/base_ebill_payment_contract/setup.py
Labels: approved, bot is merging ⏳

#212 [13.0][ADD] account_invoice_export
  account_invoice_export/__init__.py
  account_invoice_export/__manifest__.py
  account_invoice_export/data/mail_activity_type.xml
  account_invoice_export/models/__init__.py
  account_invoice_export/models/account_move.py
  account_invoice_export/models/transmit_method.py
  account_invoice_export/readme/CONTRIBUTORS.rst
  account_invoice_export/readme/DESCRIPTION.rst
  account_invoice_export/tests/__init__.py
  account_invoice_export/tests/test_export_invoice.py
  account_invoice_export/views/account_move.xml
  account_invoice_export/views/message_template.xml
  account_invoice_export/views/transmit_method.xml
  oca_dependencies.txt
  setup/account_invoice_export/odoo/addons/account_invoice_export
  setup/account_invoice_export/setup.py
Labels: bot is merging ⏳

#237 [13.0][ADD] edi_voxel: new module
  edi_voxel/README.rst
  edi_voxel/__init__.py
  edi_voxel/__manifest__.py
  edi_voxel/data/data_voxel_uom.xml
  edi_voxel/i18n/edi_voxel.pot
  edi_voxel/i18n/es.po
  edi_voxel/models/__init__.py
  edi_voxel/models/account.py
  edi_voxel/models/queue_job.py
  edi_voxel/models/res_company.py
  edi_voxel/models/res_config_settings.py
  edi_voxel/models/res_partner.py
  edi_voxel/models/uom_uom.py
  edi_voxel/models/voxel_login.py
  edi_voxel/models/voxel_mixin.py
  edi_voxel/readme/CONTRIBUTORS.rst
  edi_voxel/readme/DESCRIPTION.rst
  edi_voxel/security/ir.model.access.csv
  edi_voxel/security/voxel_security.xml
  edi_voxel/static/description/index.html
  edi_voxel/views/account_tax_views.xml
  edi_voxel/views/product_uom_views.xml
  edi_voxel/views/res_company_view.xml
  edi_voxel/views/res_config_settings_views.xml
  edi_voxel/views/res_partner_views.xml
  edi_voxel/views/template_voxel_report.xml
  edi_voxel/views/voxel_login_views.xml
  oca_dependencies.txt
  setup/edi_voxel/odoo/addons/edi_voxel
  setup/edi_voxel/setup.py
Labels: approved, bot is merging ⏳

#239 [13.0][ADD] edi_voxel_stock_picking: New module.
  edi_voxel_stock_picking/README.rst
  edi_voxel_stock_picking/__init__.py
  edi_voxel_stock_picking/__manifest__.py
  edi_voxel_stock_picking/data/ir_cron_data.xml
  edi_voxel_stock_picking/i18n/edi_voxel_stock_picking.pot
  edi_voxel_stock_picking/i18n/es.po
  edi_voxel_stock_picking/models/__init__.py
  edi_voxel_stock_picking/models/res_company.py
  edi_voxel_stock_picking/models/res_config_settings.py
  edi_voxel_stock_picking/models/stock_picking.py
  edi_voxel_stock_picking/readme/CONFIGURE.rst
  edi_voxel_stock_picking/readme/CONTRIBUTORS.rst
  edi_voxel_stock_picking/readme/DESCRIPTION.rst
  edi_voxel_stock_picking/readme/USAGE.rst
  edi_voxel_stock_picking/reports/__init__.py
  edi_voxel_stock_picking/reports/report_voxel_picking.py
  edi_voxel_stock_picking/static/description/index.html
  edi_voxel_stock_picking/tests/__init__.py
  edi_voxel_stock_picking/tests/test_voxel_stock_picking.py
  edi_voxel_stock_picking/views/report_voxel_picking.xml
  edi_voxel_stock_picking/views/res_company_view.xml
  edi_voxel_stock_picking/views/res_config_settings_views.xml
  edi_voxel_stock_picking/views/stock_picking_views.xml
Labels: bot is merging ⏳

#238 [13.0][ADD] edi_voxel_account_invoice: new module
  edi_voxel_account_invoice/README.rst
  edi_voxel_account_invoice/__init__.py
  edi_voxel_account_invoice/__manifest__.py
  edi_voxel_account_invoice/data/ir_cron_data.xml
  edi_voxel_account_invoice/i18n/edi_voxel_account_invoice.pot
  edi_voxel_account_invoice/i18n/es.po
  edi_voxel_account_invoice/models/__init__.py
  edi_voxel_account_invoice/models/account_move.py
  edi_voxel_account_invoice/models/res_company.py
  edi_voxel_account_invoice/models/res_config_settings.py
  edi_voxel_account_invoice/readme/CONFIGURE.rst
  edi_voxel_account_invoice/readme/CONTRIBUTORS.rst
  edi_voxel_account_invoice/readme/DESCRIPTION.rst
  edi_voxel_account_invoice/readme/USAGE.rst
  edi_voxel_account_invoice/reports/__init__.py
  edi_voxel_account_invoice/reports/report_voxel_invoice.py
  edi_voxel_account_invoice/static/description/index.html
  edi_voxel_account_invoice/tests/__init__.py
  edi_voxel_account_invoice/tests/test_voxel_account_invoice.py
  edi_voxel_account_invoice/views/account_move_views.xml
  edi_voxel_account_invoice/views/report_voxel_invoice.xml
  edi_voxel_account_invoice/views/res_company_view.xml
  edi_voxel_account_invoice/views/res_config_settings_views.xml
  setup/edi_voxel_account_invoice/odoo/addons/edi_voxel_account_invoice
  setup/edi_voxel_account_invoice/setup.py
Labels: bot is merging ⏳

#240 [13.0][ADD] edi_voxel_sale_order_import: New module
  edi_voxel_sale_order_import/README.rst
  edi_voxel_sale_order_import/__init__.py
  edi_voxel_sale_order_import/__manifest__.py
  edi_voxel_sale_order_import/data/ir_cron_data.xml
  edi_voxel_sale_order_import/i18n/edi_voxel_sale_order_import.pot
  edi_voxel_sale_order_import/i18n/es.po
  edi_voxel_sale_order_import/models/__init__.py
  edi_voxel_sale_order_import/models/res_company.py
  edi_voxel_sale_order_import/models/res_config_settings.py
  edi_voxel_sale_order_import/models/sale_order.py
  edi_voxel_sale_order_import/readme/CONFIGURE.rst
  edi_voxel_sale_order_import/readme/CONTRIBUTORS.rst
  edi_voxel_sale_order_import/readme/DESCRIPTION.rst
  edi_voxel_sale_order_import/readme/USAGE.rst
  edi_voxel_sale_order_import/security/ir.model.access.csv
  edi_voxel_sale_order_import/security/voxel_sale_order_security.xml
  edi_voxel_sale_order_import/static/description/index.html
  edi_voxel_sale_order_import/tests/__init__.py
  edi_voxel_sale_order_import/tests/test_voxel_sale_order_import.py
  edi_voxel_sale_order_import/tests/voxel_xml/Pedido_20190619_145750_0611125750634.xml
  edi_voxel_sale_order_import/views/res_company_views.xml
  edi_voxel_sale_order_import/views/res_config_settings_views.xml
  edi_voxel_sale_order_import/views/sale_order_views.xml
  setup/edi_voxel_sale_order_import/odoo/addons/edi_voxel_sale_order_import
  setup/edi_voxel_sale_order_import/setup.py
Labels: bot is merging ⏳

#247 [13.0] Add base_edi
  base_edi/README.rst
  base_edi/__init__.py
  base_edi/__manifest__.py
  base_edi/data/module_category.xml
  base_edi/readme/CONTRIBUTORS.rst
  base_edi/readme/DESCRIPTION.rst
  base_edi/readme/ROADMAP.rst
  base_edi/security/edi_groups.xml
  base_edi/static/description/icon.png
  base_edi/static/description/index.html
  base_edi/views/edi_menu.xml
  setup/base_edi/odoo/addons/base_edi
  setup/base_edi/setup.py
Labels: approved, bot is merging ⏳

#252 [IMP] base_edi: Add Icon
  base_edi/static/description/icon.png
  base_edi/static/description/icon.svg
Labels: approved

#251 [IMP] edi: define type, record, record create helper
  edi/__manifest__.py
  edi/models/__init__.py
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/models/edi_exchange_type.py
  edi/readme/CONTRIBUTORS.rst
  edi/readme/DESCRIPTION.rst
  edi/security/ir_model_access.xml
  edi/static/description/icon.png
  edi/static/description/icon.svg
  edi/templates/exchange_chatter_msg.xml
  edi/tests/common.py
  edi/tests/test_edi_backend.py
  edi/views/edi_exchange_record_views.xml
  edi/views/edi_exchange_type_views.xml
  requirements.txt
Labels: approved

#253 [IMP] edi: add generic send function
  edi/__manifest__.py
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/tests/test_edi_backend.py
Labels: approved

#261 [FIX] travis
  .travis.yml
  account_invoice_ubl/models/account_move.py
  base_ubl/models/ubl.py
  requirements.txt
Labels: approved, bot is merging ⏳

#259 [13.0] Add edi_exchange_template
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/models/edi_exchange_type.py
  edi/tests/test_edi_backend.py
  edi_exchange_template/README.rst
  edi_exchange_template/__init__.py
  edi_exchange_template/__manifest__.py
  edi_exchange_template/components/__init__.py
  edi_exchange_template/components/common.py
  edi_exchange_template/components/output_mixin.py
  edi_exchange_template/models/__init__.py
  edi_exchange_template/models/edi_backend.py
  edi_exchange_template/models/edi_exchange_template_mixin.py
  edi_exchange_template/models/edi_exchange_template_output.py
  edi_exchange_template/readme/CONTRIBUTORS.rst
  edi_exchange_template/readme/DESCRIPTION.rst
  edi_exchange_template/security/ir_model_access.xml
  edi_exchange_template/static/description/icon.png
  edi_exchange_template/static/description/index.html
  edi_exchange_template/tests/__init__.py
  edi_exchange_template/tests/test_edi_backend_output.py
  edi_exchange_template/utils.py
  edi_exchange_template/views/edi_exchange_template_output_views.xml
  setup/edi_exchange_template/odoo/addons/edi_exchange_template
  setup/edi_exchange_template/setup.py
Labels: bot is merging ⏳

#262 [IMP] edi: Add mixins
  edi/models/__init__.py
  edi/models/edi_exchange_consumer_mixin.py
  edi/models/edi_exchange_type.py
  edi/tests/__init__.py
  edi/tests/models.py
  edi/tests/test_edi_mixin.py
  requirements.txt
Labels: approved, bot is merging ⏳

#264 [13.0] EDI Add crons to automate record status
  edi/__init__.py
  edi/__manifest__.py
  edi/components/__init__.py
  edi/components/base.py
  edi/data/cron.xml
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/models/edi_exchange_type.py
  edi/tests/common.py
  edi/tests/fake_components.py
  edi/tests/test_edi_backend_cron.py
  edi/views/edi_exchange_type_views.xml
  edi_exchange_template/models/edi_backend.py
  edi_exchange_template/models/edi_exchange_template_output.py
  edi_exchange_template/tests/test_edi_backend_output.py
  edi_exchange_template/utils.py
Labels: bot is merging ⏳

#266 [13.0] edi: add specific events, improve msg handling
  edi/__manifest__.py
  edi/components/base.py
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/tests/__init__.py
  edi/tests/common.py
  edi/tests/fake_components.py
  edi/tests/test_backend_base.py
  edi/tests/test_backend_output.py
  edi/tests/test_edi_backend.py
  edi/tests/test_edi_backend_cron.py
  edi/tests/test_record.py
  edi/tests/test_type.py
Labels: approved, bot is merging ⏳

#254 [IMP] edi: Define a processing function for incoming documents
  edi/components/__init__.py
  edi/components/base.py
  edi/components/base_input.py
  edi/components/base_output.py
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/tests/__init__.py
  edi/tests/fake_components.py
  edi/tests/test_backend_input.py
  edi/tests/test_backend_output.py
  edi/tests/test_edi_backend_cron.py
  edi_exchange_template/models/edi_backend.py
  edi_exchange_template/tests/test_edi_backend_output.py
Labels: bot is merging ⏳

#265 [13.0] Add edi_storage + add unique identifier
  edi/__manifest__.py
  edi/data/cron.xml
  edi/data/sequence.xml
  edi/models/edi_backend.py
  edi/models/edi_exchange_record.py
  edi/tests/__init__.py
  edi/tests/fake_models.py
  edi/tests/test_consumer_mixin.py
  edi/tests/test_edi_mixin.py
  edi/tests/test_record.py
  edi/views/edi_backend_type_views.xml
  edi/views/edi_backend_views.xml
  edi/views/edi_exchange_record_views.xml
  edi/views/edi_exchange_type_views.xml
  edi/views/menuitems.xml
  edi_storage/README.rst
  edi_storage/__init__.py
  edi_storage/__manifest__.py
  edi_storage/components/__init__.py
  edi_storage/components/base.py
  edi_storage/components/check.py
  edi_storage/components/send.py
  edi_storage/demo/edi_backend_demo.xml
  edi_storage/models/__init__.py
  edi_storage/models/edi_backend.py
  edi_storage/readme/CONTRIBUTORS.rst
  edi_storage/readme/DESCRIPTION.rst
  edi_storage/readme/USAGE.rst
  edi_storage/security/ir_model_access.xml
  edi_storage/static/description/icon.png
  edi_storage/static/description/index.html
  edi_storage/tests/__init__.py
  edi_storage/tests/common.py
  edi_storage/tests/test_components_base.py
  edi_storage/tests/test_edi_backend_storage.py
  edi_storage/views/edi_backend_views.xml
  oca_dependencies.txt
  setup/edi_storage/odoo/addons/edi_storage
  setup/edi_storage/setup.py
Labels: bot is merging ⏳
