Repository OCA/edi, pull requests merged in 2020-04, with the labels that each got.

#180 FIX travis config
  .travis.yml
Labels: approved

#178 8.0 IMP purch_order: allow to using xml with no pdf and hook to customize xml
  purchase_order_ubl/models/purchase.py
Labels: approved

#188 [8.0] IMP base_ubl: set a base_company_view
  account_invoice_ubl/views/company.xml
  base_ubl/__openerp__.py
  base_ubl/views/company_view.xml
Labels: approved, bot is merging ⏳

#184 [8.0] ADD ubl inventory report
  supplier_inventory_import_ubl/README.rst
  supplier_inventory_import_ubl/__init__.py
  supplier_inventory_import_ubl/__openerp__.py
  supplier_inventory_import_ubl/demo/partner.xml
  supplier_inventory_import_ubl/demo/product.xml
  supplier_inventory_import_ubl/models/__init__.py
  supplier_inventory_import_ubl/models/company.py
  supplier_inventory_import_ubl/models/product.py
  supplier_inventory_import_ubl/models/stock.py
  supplier_inventory_import_ubl/models/supplierinfo.py
  supplier_inventory_import_ubl/readme/CONFIGURE.rst
  supplier_inventory_import_ubl/readme/CONTRIBUTORS.rst
  supplier_inventory_import_ubl/readme/CREDITS.rst
  supplier_inventory_import_ubl/readme/DESCRIPTION.rst
  supplier_inventory_import_ubl/readme/ROADMAP.rst
  supplier_inventory_import_ubl/readme/USAGE.rst
  supplier_inventory_import_ubl/static/description/icon.png
  supplier_inventory_import_ubl/static/description/import.png
  supplier_inventory_import_ubl/static/description/index.html
  supplier_inventory_import_ubl/static/description/product.png
  supplier_inventory_import_ubl/static/description/settings.png
  supplier_inventory_import_ubl/static/description/stock_report.png
  supplier_inventory_import_ubl/static/description/supplier_info.png
  supplier_inventory_import_ubl/static/description/supplierinfo_updated_data.png
  supplier_inventory_import_ubl/static/description/wood_message.png
  supplier_inventory_import_ubl/tests/__init__.py
  supplier_inventory_import_ubl/tests/inventory_report_sample/main.xml
  supplier_inventory_import_ubl/tests/inventory_report_sample/no_seller_reference.xml
  supplier_inventory_import_ubl/tests/inventory_report_sample/only_one_default_code.xml
  supplier_inventory_import_ubl/tests/inventory_report_sample/unknow_supplier.xml
  supplier_inventory_import_ubl/tests/test_import.py
  supplier_inventory_import_ubl/views/company_view.xml
  supplier_inventory_import_ubl/views/product_view.xml
  supplier_inventory_import_ubl/views/stock_view.xml
  supplier_inventory_import_ubl/views/supplierinfo_view.xml
  supplier_inventory_import_ubl/wizards/__init__.py
  supplier_inventory_import_ubl/wizards/inventory_helper.py
  supplier_inventory_import_ubl/wizards/inventory_import.py
  supplier_inventory_import_ubl/wizards/inventory_import_view.xml
Labels: approved, bot is merging ⏳

#191 FIX display images in readme, IMP _extract_data_and_upd_supplierinfo()
  supplier_inventory_import_ubl/README.rst
  supplier_inventory_import_ubl/models/supplierinfo.py
  supplier_inventory_import_ubl/readme/CONFIGURE.rst
  supplier_inventory_import_ubl/readme/USAGE.rst
  supplier_inventory_import_ubl/static/description/index.html
  supplier_inventory_import_ubl/tests/test_import.py
  supplier_inventory_import_ubl/wizards/inventory_import.py
Labels: bot is merging ⏳

#193 [FIX]Restore new api compatibility to get_pdf method
  purchase_order_ubl/models/report.py
Labels: approved

#194 FIX purch_order_ubl: switch get_pdf() in new api
  purchase_order_ubl/models/report.py
Labels: approved
