Repository OCA/edi, pull requests merged in 2021-08, with the labels that each got.

#427 [14.0][FIX] edi_storage_oca: remove duplicate backend_type_id field in edi backend form
  edi_storage_oca/views/edi_backend_views.xml
Labels: approved, bot is merging ⏳

#426 [13.0][FIX] edi_storage: remove duplicate backend_type_id field in edi backend form
  edi_storage/views/edi_backend_views.xml
Labels: approved, bot is merging ⏳

#316 [MIG] sale_order_import_ubl: Migration to 14.0
  base_business_document_import/models/business_document_import.py
  base_ubl/models/ubl.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_import_ubl/README.rst
  sale_order_import_ubl/__init__.py
  sale_order_import_ubl/__manifest__.py
  sale_order_import_ubl/demo/demo_data.xml
  sale_order_import_ubl/i18n/sale_order_import_ubl.pot
  sale_order_import_ubl/readme/CONTRIBUTORS.rst
  sale_order_import_ubl/readme/CREDITS.rst
  sale_order_import_ubl/readme/DESCRIPTION.rst
  sale_order_import_ubl/readme/USAGE.rst
  sale_order_import_ubl/static/description/icon.png
  sale_order_import_ubl/static/description/index.html
  sale_order_import_ubl/tests/__init__.py
  sale_order_import_ubl/tests/files/UBL-Order-2.0-Example.xml
  sale_order_import_ubl/tests/files/UBL-Order-2.1-Example.xml
  sale_order_import_ubl/tests/files/UBL-RequestForQuotation-2.0-Example.xml
  sale_order_import_ubl/tests/files/UBL-RequestForQuotation-2.1-Example.xml
  sale_order_import_ubl/tests/test_ubl_order_import.py
  sale_order_import_ubl/wizard/__init__.py
  sale_order_import_ubl/wizard/sale_order_import.py
  setup/sale_order_import_ubl/odoo/addons/sale_order_import_ubl
  setup/sale_order_import_ubl/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#332 [MIG] partner_identification_import: Migration to 14.0
  partner_identification_import/README.rst
  partner_identification_import/__init__.py
  partner_identification_import/__manifest__.py
  partner_identification_import/i18n/partner_identification_import.pot
  partner_identification_import/models/__init__.py
  partner_identification_import/models/business_document_import.py
  partner_identification_import/readme/CONTRIBUTORS.rst
  partner_identification_import/readme/CREDITS.rst
  partner_identification_import/readme/DESCRIPTION.rst
  partner_identification_import/static/description/icon.png
  partner_identification_import/static/description/index.html
  partner_identification_import/tests/__init__.py
  partner_identification_import/tests/test_business_document_import.py
  setup/partner_identification_import/odoo/addons/partner_identification_import
  setup/partner_identification_import/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#423 [13.0][IMP] base_ubl: add customer as an argument in _ubl_add_item method
  base_ubl/models/ubl.py
Labels: approved, ready to merge, bot is merging ⏳

#428 [13.0][ADD] edi_backend_partner
  edi_backend_partner/README.rst
  edi_backend_partner/__init__.py
  edi_backend_partner/__manifest__.py
  edi_backend_partner/models/__init__.py
  edi_backend_partner/models/edi_backend.py
  edi_backend_partner/models/res_partner.py
  edi_backend_partner/readme/CONTRIBUTORS.rst
  edi_backend_partner/readme/DESCRIPTION.rst
  edi_backend_partner/static/description/icon.png
  edi_backend_partner/static/description/index.html
  edi_backend_partner/tests/__init__.py
  edi_backend_partner/tests/test_edi_backend_partner.py
  edi_backend_partner/views/edi_backend_views.xml
  edi_backend_partner/views/res_partner_views.xml
  setup/edi_backend_partner/odoo/addons/edi_backend_partner
  setup/edi_backend_partner/setup.py
Labels: approved, bot is merging ⏳

#430 [14.0][MIG] edi_backend_partner
  edi_backend_partner_oca/README.rst
  edi_backend_partner_oca/__init__.py
  edi_backend_partner_oca/__manifest__.py
  edi_backend_partner_oca/i18n/edi_backend_partner.pot
  edi_backend_partner_oca/models/__init__.py
  edi_backend_partner_oca/models/edi_backend.py
  edi_backend_partner_oca/models/res_partner.py
  edi_backend_partner_oca/readme/CONTRIBUTORS.rst
  edi_backend_partner_oca/readme/DESCRIPTION.rst
  edi_backend_partner_oca/static/description/icon.png
  edi_backend_partner_oca/static/description/index.html
  edi_backend_partner_oca/tests/__init__.py
  edi_backend_partner_oca/tests/test_edi_backend_partner.py
  edi_backend_partner_oca/views/edi_backend_views.xml
  edi_backend_partner_oca/views/res_partner_views.xml
  setup/edi_backend_partner_oca/odoo/addons/edi_backend_partner
  setup/edi_backend_partner_oca/setup.py
Labels: approved, bot is merging ⏳

#210 [IMP] account_invoice_import_invoice2data: Allow a field for company vat
  account_invoice_import_invoice2data/wizard/account_invoice_import.py
  requirements.txt
  test-requirements.txt
Labels: needs fixing, approved, bot is merging ⏳
