Repository OCA/edi, pull requests merged in 2021-12, with the labels that each got.

#489 [15.0][mig] base_edi
  all-physical.sloc
  all.filecount
  base_edi/README.rst
  base_edi/__init__.py
  base_edi/__manifest__.py
  base_edi/data/module_category.xml
  base_edi/i18n/base_edi.pot
  base_edi/i18n/fr.po
  base_edi/i18n/nl.po
  base_edi/readme/CONTRIBUTORS.rst
  base_edi/readme/DESCRIPTION.rst
  base_edi/readme/ROADMAP.rst
  base_edi/security/edi_groups.xml
  base_edi/static/description/icon.png
  base_edi/static/description/icon.svg
  base_edi/static/description/index.html
  base_edi/views/edi_menu.xml
  setup/base_edi/odoo/addons/base_edi
  setup/base_edi/setup.py
Labels: bot is merging ⏳

#435 [IMP] account_invoice_import_invoice2data: Allow a field for company vat
  account_invoice_import_invoice2data/wizard/account_invoice_import.py
Labels: approved, bot is merging ⏳

#216 [IMP] . amounts decimal places should be no more than 2
  account_invoice_ubl/models/account_invoice.py
  base_ubl/models/ubl.py
Labels: bot is merging ⏳

#488 [IMP] From travis to Github actions
  .copier-answers.yml
  .github/workflows/test.yml
  .t2d.yml
  README.md
  account_invoice_import_invoice2data/__manifest__.py
  account_invoice_import_simple_pdf/__manifest__.py
  base_edi/__manifest__.py
  edi_oca/__manifest__.py
Labels: approved, ready to merge

#331 [12.0][MIG] base_business_document_import_stock
  base_business_document_import_stock/README.rst
  base_business_document_import_stock/__init__.py
  base_business_document_import_stock/__manifest__.py
  base_business_document_import_stock/i18n/base_business_document_import_stock.pot
  base_business_document_import_stock/models/__init__.py
  base_business_document_import_stock/models/business_document_import.py
  base_business_document_import_stock/static/description/icon.png
  base_business_document_import_stock/tests/__init__.py
  base_business_document_import_stock/tests/test_incoterm_match.py
Labels: bot is merging ⏳

#487 [14.0] edi_account: forward port commits from 13.0
  edi_account_oca/__manifest__.py
  edi_account_oca/models/account_move.py
  edi_account_oca/views/account_move.xml
  edi_account_oca/views/edi_exchange_record.xml
Labels: approved, bot is merging ⏳

#457 [10.0][IMP] account_invoice_import: restore hook for override
  account_invoice_import/wizard/account_invoice_import.py
Labels: approved, bot is merging ⏳
