Repository OCA/edi, pull requests merged in 2021-05, with the labels that each got.

#359 [13.0][ADD] edi_voxel_sale_secondary_unit: new module
  edi_voxel_sale_order_import/i18n/edi_voxel_sale_order_import.pot
  edi_voxel_sale_order_import/i18n/es.po
  edi_voxel_sale_order_import/models/sale_order.py
  edi_voxel_sale_order_import/tests/test_voxel_sale_order_import.py
  edi_voxel_sale_order_import/tests/voxel_xml/Pedido_20190619_145750_0611125750634.xml
  edi_voxel_sale_secondary_unit/README.rst
  edi_voxel_sale_secondary_unit/__init__.py
  edi_voxel_sale_secondary_unit/__manifest__.py
  edi_voxel_sale_secondary_unit/models/__init__.py
  edi_voxel_sale_secondary_unit/models/sale_order.py
  edi_voxel_sale_secondary_unit/readme/CONTRIBUTORS.rst
  edi_voxel_sale_secondary_unit/readme/DESCRIPTION.rst
  edi_voxel_sale_secondary_unit/readme/USAGE.rst
  edi_voxel_sale_secondary_unit/static/description/index.html
  edi_voxel_sale_secondary_unit/tests/__init__.py
  edi_voxel_sale_secondary_unit/tests/test_edi_voxel_sale_secondary_unit.py
  setup/edi_voxel_sale_secondary_unit/odoo/addons/edi_voxel_sale_secondary_unit
  setup/edi_voxel_sale_secondary_unit/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#379 [13.0][FIX] order_import_order_ubl_http fail if exists
  sale_order_import_ubl_http/models/sale_order.py
  sale_order_import_ubl_http/tests/test_sale_order_import_endpoint.py
Labels: approved, bot is merging ⏳

#380 [13.0][FIX] edi_voxel: Get customerinfo from commercial partner too
  edi_voxel/models/voxel_mixin.py
Labels: approved, bot is merging ⏳

#381 [FIX] edi_voxel_stock_picking: Filter out cancel lines
  edi_voxel_stock_picking/reports/report_voxel_picking.py
  edi_voxel_stock_picking/tests/test_voxel_stock_picking.py
Labels: approved, bot is merging ⏳

#376 [MIG] edi_account_oca: Migration to 14.0 and rename
  edi_account_oca/README.rst
  edi_account_oca/__init__.py
  edi_account_oca/__manifest__.py
  edi_account_oca/i18n/edi_account.pot
  edi_account_oca/models/__init__.py
  edi_account_oca/models/account_move.py
  edi_account_oca/readme/CONTRIBUTORS.rst
  edi_account_oca/readme/DESCRIPTION.rst
  edi_account_oca/static/description/icon.png
  edi_account_oca/static/description/index.html
  edi_account_oca/tests/__init__.py
  edi_account_oca/tests/test_edi.py
  edi_account_oca/views/account_journal.xml
  edi_account_oca/views/account_move.xml
  edi_account_oca/views/res_partner.xml
Labels: approved, bot is merging ⏳, ready to merge

#375 [MIG] webservice: Migration to 14.0
  test-requirements.txt
  webservice/README.rst
  webservice/__init__.py
  webservice/__manifest__.py
  webservice/components/__init__.py
  webservice/components/base_adapter.py
  webservice/components/request_adapter.py
  webservice/i18n/webservice.pot
  webservice/models/__init__.py
  webservice/models/webservice_backend.py
  webservice/readme/CONTRIBUTORS.rst
  webservice/readme/DESCRIPTION.rst
  webservice/security/ir.model.access.csv
  webservice/static/description/icon.png
  webservice/static/description/index.html
  webservice/tests/__init__.py
  webservice/tests/common.py
  webservice/tests/test_webservice.py
  webservice/views/webservice_backend.xml
Labels: approved, bot is merging ⏳

#333 [14.0][mig] base_ubl_payment
  base_ubl_payment/README.rst
  base_ubl_payment/__init__.py
  base_ubl_payment/__manifest__.py
  base_ubl_payment/i18n/base_ubl_payment.pot
  base_ubl_payment/i18n/hr.po
  base_ubl_payment/i18n/nl.po
  base_ubl_payment/models/__init__.py
  base_ubl_payment/models/ubl.py
  base_ubl_payment/readme/CONTRIBUTORS.rst
  base_ubl_payment/readme/DESCRIPTION.rst
  base_ubl_payment/static/description/icon.png
  base_ubl_payment/static/description/index.html
  oca_dependencies.txt
  setup/base_ubl_payment/odoo/addons/base_ubl_payment
  setup/base_ubl_payment/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#101 [12.0][MIG] sale_order_import
  sale_order_import/README.rst
  sale_order_import/__init__.py
  sale_order_import/__manifest__.py
  sale_order_import/i18n/es.po
  sale_order_import/i18n/fr.po
  sale_order_import/i18n/sale_order_import.pot
  sale_order_import/models/__init__.py
  sale_order_import/models/sale.py
  sale_order_import/readme/CONTRIBUTORS.rst
  sale_order_import/readme/DESCRIPTION.rst
  sale_order_import/readme/USAGE.rst
  sale_order_import/static/description/icon.png
  sale_order_import/static/description/index.html
  sale_order_import/tests/__init__.py
  sale_order_import/tests/test_order_import.py
  sale_order_import/tests/test_sale_order.py
  sale_order_import/wizard/__init__.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_import/wizard/sale_order_import_view.xml
Labels: approved, bot is merging ⏳

#112 [10.0][FIX] Fill the account_id (required) for every configuration
  account_invoice_import/wizard/account_invoice_import.py
Labels: approved, bot is merging ⏳, ready to merge

#328 [13.0][ADD] sale_order_customer_free_ref
  sale_order_customer_free_ref/__init__.py
  sale_order_customer_free_ref/__manifest__.py
  sale_order_customer_free_ref/models/__init__.py
  sale_order_customer_free_ref/models/account_move.py
  sale_order_customer_free_ref/models/sale_order.py
  sale_order_customer_free_ref/readme/CONTRIBUTORS.rst
  sale_order_customer_free_ref/readme/DESCRIPTION.rst
  sale_order_customer_free_ref/tests/__init__.py
  sale_order_customer_free_ref/tests/test_sale_order_customer_free_ref.py
  sale_order_customer_free_ref/views/account_move.xml
  sale_order_customer_free_ref/views/sale_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#385 [ADD][13.0]sale_order_import no mail subscribe
  sale_order_import/wizard/sale_order_import.py
Labels: approved, bot is merging ⏳, ready to merge

#382 [MIG] edi_webservice_oca: Migration to 14.0
  edi_webservice_oca/README.rst
  edi_webservice_oca/__init__.py
  edi_webservice_oca/__manifest__.py
  edi_webservice_oca/i18n/edi_webservice.pot
  edi_webservice_oca/models/__init__.py
  edi_webservice_oca/models/edi_backend.py
  edi_webservice_oca/readme/CONTRIBUTORS.rst
  edi_webservice_oca/readme/DESCRIPTION.rst
  edi_webservice_oca/security/ir.model.access.csv
  edi_webservice_oca/static/description/icon.png
  edi_webservice_oca/static/description/index.html
  edi_webservice_oca/tests/__init__.py
  edi_webservice_oca/tests/test_edi_webservice.py
  edi_webservice_oca/views/edi_backend.xml
Labels: bot is merging ⏳

#386 [IMP] edi_exchange_template: Allow to use report instead of view
  edi_exchange_template/models/edi_exchange_template_output.py
  edi_exchange_template/tests/test_edi_backend_output.py
  edi_exchange_template/views/edi_exchange_template_output_views.xml
Labels: approved, bot is merging ⏳

#372 [14.0] [mig] edi_storage_oca
  edi_storage_oca/README.rst
  edi_storage_oca/__init__.py
  edi_storage_oca/__manifest__.py
  edi_storage_oca/components/__init__.py
  edi_storage_oca/components/base.py
  edi_storage_oca/components/check.py
  edi_storage_oca/components/send.py
  edi_storage_oca/demo/edi_backend_demo.xml
  edi_storage_oca/i18n/edi_storage.pot
  edi_storage_oca/models/__init__.py
  edi_storage_oca/models/edi_backend.py
  edi_storage_oca/readme/CONTRIBUTORS.rst
  edi_storage_oca/readme/DESCRIPTION.rst
  edi_storage_oca/readme/USAGE.rst
  edi_storage_oca/security/ir_model_access.xml
  edi_storage_oca/static/description/icon.png
  edi_storage_oca/static/description/index.html
  edi_storage_oca/tests/__init__.py
  edi_storage_oca/tests/common.py
  edi_storage_oca/tests/test_component_match.py
  edi_storage_oca/tests/test_components_base.py
  edi_storage_oca/tests/test_edi_backend_storage.py
  edi_storage_oca/views/edi_backend_views.xml
  setup/edi_storage_oca/odoo/addons/edi_storage_oca
  setup/edi_storage_oca/setup.py
Labels: bot is merging ⏳

#388 [MIG] edi_exchange_template_oca: Migration to 14.0
  edi_exchange_template_oca/README.rst
  edi_exchange_template_oca/__init__.py
  edi_exchange_template_oca/__manifest__.py
  edi_exchange_template_oca/components/__init__.py
  edi_exchange_template_oca/components/common.py
  edi_exchange_template_oca/components/output_mixin.py
  edi_exchange_template_oca/i18n/edi_exchange_template.pot
  edi_exchange_template_oca/models/__init__.py
  edi_exchange_template_oca/models/edi_backend.py
  edi_exchange_template_oca/models/edi_exchange_template_mixin.py
  edi_exchange_template_oca/models/edi_exchange_template_output.py
  edi_exchange_template_oca/readme/CONTRIBUTORS.rst
  edi_exchange_template_oca/readme/DESCRIPTION.rst
  edi_exchange_template_oca/security/ir_model_access.xml
  edi_exchange_template_oca/static/description/icon.png
  edi_exchange_template_oca/static/description/index.html
  edi_exchange_template_oca/tests/__init__.py
  edi_exchange_template_oca/tests/test_edi_backend_output.py
  edi_exchange_template_oca/utils.py
  edi_exchange_template_oca/views/edi_exchange_template_output_views.xml
  setup/edi_exchange_template_oca/odoo/addons/edi_exchange_template
  setup/edi_exchange_template_oca/setup.py
Labels: approved, bot is merging ⏳
