Repository OCA/edi, pull requests merged in 2021-04, with the labels that each got.

#349 [13.0][IMP] Add sale order ubl parse latest delivery
  base_ubl/models/ubl.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_import_ubl/tests/files/UBL-Order-2.0-Example.xml
  sale_order_import_ubl/tests/files/UBL-Order-2.1-Example.xml
  sale_order_import_ubl/tests/test_ubl_order_import.py
  sale_order_import_ubl/wizard/sale_order_import.py
Labels: approved, bot is merging ⏳, ready to merge

#339 [13.0][IMP] account_invoice_export send button visibility
  account_invoice_export/models/account_move.py
  account_invoice_export/models/transmit_method.py
  account_invoice_export/views/account_move.xml
  account_invoice_export/views/transmit_method.xml
Labels: bot is merging ⏳

#357 [13.0][ADD] edi_voxel_secondary_unit: new module
  edi_voxel/i18n/edi_voxel.pot
  edi_voxel/i18n/es.po
  edi_voxel/models/uom_uom.py
  edi_voxel_secondary_unit/README.rst
  edi_voxel_secondary_unit/__init__.py
  edi_voxel_secondary_unit/__manifest__.py
  edi_voxel_secondary_unit/i18n/edi_voxel_secondary_unit.pot
  edi_voxel_secondary_unit/i18n/es.po
  edi_voxel_secondary_unit/models/__init__.py
  edi_voxel_secondary_unit/models/product_secondary_unit.py
  edi_voxel_secondary_unit/readme/CONTRIBUTORS.rst
  edi_voxel_secondary_unit/readme/DESCRIPTION.rst
  edi_voxel_secondary_unit/readme/USAGE.rst
  edi_voxel_secondary_unit/static/description/index.html
  edi_voxel_secondary_unit/views/product_secondary_unit_views.xml
  setup/edi_voxel_secondary_unit/odoo/addons/edi_voxel_secondary_unit
  setup/edi_voxel_secondary_unit/setup.py
Labels: approved, bot is merging ⏳

#354 [13.0] s_order_import_ubl_http: add job config + ease override
  sale_order_import_ubl_http/__manifest__.py
  sale_order_import_ubl_http/controllers/main.py
  sale_order_import_ubl_http/data/queue_job_channel.xml
  sale_order_import_ubl_http/data/queue_job_function.xml
  sale_order_import_ubl_http/models/sale_order.py
  sale_order_import_ubl_http/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#356 [14.0] [mig] sale_order_ubl
  sale_order_ubl/README.rst
  sale_order_ubl/__init__.py
  sale_order_ubl/__manifest__.py
  sale_order_ubl/i18n/hr.po
  sale_order_ubl/i18n/sale_order_ubl.pot
  sale_order_ubl/models/__init__.py
  sale_order_ubl/models/report.py
  sale_order_ubl/models/sale.py
  sale_order_ubl/readme/CONTRIBUTORS.rst
  sale_order_ubl/readme/DESCRIPTION.rst
  sale_order_ubl/static/description/icon.png
  sale_order_ubl/static/description/index.html
  sale_order_ubl/tests/__init__.py
  sale_order_ubl/tests/test_ubl_generate.py
  setup/sale_order_ubl/odoo/addons/sale_order_ubl
  setup/sale_order_ubl/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#362 [FIX] edi & edi_storage
  edi/models/edi_exchange_record.py
  edi/tests/test_record.py
  edi_storage/models/edi_backend.py
Labels: approved, bot is merging ⏳

#301 [MIG] base_business_document_import: Migration to 14.0
  base_business_document_import/README.rst
  base_business_document_import/__init__.py
  base_business_document_import/__manifest__.py
  base_business_document_import/i18n/base_business_document_import.pot
  base_business_document_import/i18n/cs_CZ.po
  base_business_document_import/i18n/fr.po
  base_business_document_import/models/__init__.py
  base_business_document_import/models/business_document_import.py
  base_business_document_import/readme/CONTRIBUTORS.rst
  base_business_document_import/readme/CREDITS.rst
  base_business_document_import/readme/DESCRIPTION.rst
  base_business_document_import/static/description/icon.png
  base_business_document_import/static/description/index.html
  base_business_document_import/tests/__init__.py
  base_business_document_import/tests/test_business_document_import.py
  setup/base_business_document_import/odoo/addons/base_business_document_import
  setup/base_business_document_import/setup.py
Labels: approved, bot is merging ⏳

#366 [14.0] base_business_document_import: Improve tests on taxes
  base_business_document_import/__manifest__.py
  base_business_document_import/models/business_document_import.py
  base_business_document_import/readme/CREDITS.rst
  base_business_document_import/tests/test_business_document_import.py
Labels: approved, bot is merging ⏳

#360 [13.0][ADD] edi_voxel_stock_picking_secondary_unit: new module
  edi_voxel_stock_picking/tests/test_voxel_stock_picking.py
  edi_voxel_stock_picking_secondary_unit/README.rst
  edi_voxel_stock_picking_secondary_unit/__init__.py
  edi_voxel_stock_picking_secondary_unit/__manifest__.py
  edi_voxel_stock_picking_secondary_unit/readme/CONTRIBUTORS.rst
  edi_voxel_stock_picking_secondary_unit/readme/DESCRIPTION.rst
  edi_voxel_stock_picking_secondary_unit/readme/USAGE.rst
  edi_voxel_stock_picking_secondary_unit/reports/__init__.py
  edi_voxel_stock_picking_secondary_unit/reports/report_voxel_picking.py
  edi_voxel_stock_picking_secondary_unit/static/description/index.html
  edi_voxel_stock_picking_secondary_unit/tests/__init__.py
  edi_voxel_stock_picking_secondary_unit/tests/test_voxel_stock_picking_secondary_unit.py
  setup/edi_voxel_stock_picking_secondary_unit/odoo/addons/edi_voxel_stock_picking_secondary_unit
  setup/edi_voxel_stock_picking_secondary_unit/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#352 [14.0] [MIG] purchase_order_ubl
  purchase_order_ubl/README.rst
  purchase_order_ubl/__init__.py
  purchase_order_ubl/__manifest__.py
  purchase_order_ubl/i18n/purchase_order_ubl.pot
  purchase_order_ubl/models/__init__.py
  purchase_order_ubl/models/purchase.py
  purchase_order_ubl/models/report.py
  purchase_order_ubl/readme/CONTRIBUTORS.rst
  purchase_order_ubl/readme/DESCRIPTION.rst
  purchase_order_ubl/static/description/icon.png
  purchase_order_ubl/static/description/index.html
  purchase_order_ubl/tests/__init__.py
  purchase_order_ubl/tests/test_ubl_generate.py
  setup/purchase_order_ubl/odoo/addons/purchase_order_ubl
  setup/purchase_order_ubl/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#368 [12.0][FIX] Fix runbot build
  account_invoice_download_ovh/wizard/ovh_api_credentials.py
Labels: bot is merging ⏳

#327 [13.0] account_invoice_facturx: backport no-tax-bugfix from v14
  account_invoice_facturx/models/account_move.py
  account_invoice_facturx/models/company.py
Labels: bot is merging ⏳
