Repository OCA/edi, pull requests merged in 2021-09, with the labels that each got.

#429 [13.0][IMP] base_ubl: hook to add the AdditionalAccountID ubl field
  base_ubl/models/ubl.py
Labels: approved, ready to merge, bot is merging ⏳

#335 [MIG][14.0] account_invoice_import_facturx
  .prettierignore
  account_invoice_import_facturx/README.rst
  account_invoice_import_facturx/__init__.py
  account_invoice_import_facturx/__manifest__.py
  account_invoice_import_facturx/demo/demo_data.xml
  account_invoice_import_facturx/i18n/account_invoice_import_factur-x.pot
  account_invoice_import_facturx/i18n/account_invoice_import_facturx.pot
  account_invoice_import_facturx/i18n/de.po
  account_invoice_import_facturx/i18n/es.po
  account_invoice_import_facturx/i18n/fr.po
  account_invoice_import_facturx/i18n/sl.po
  account_invoice_import_facturx/readme/CONTRIBUTORS.rst
  account_invoice_import_facturx/readme/DESCRIPTION.rst
  account_invoice_import_facturx/readme/INSTALL.rst
  account_invoice_import_facturx/static/description/icon.png
  account_invoice_import_facturx/static/description/index.html
  account_invoice_import_facturx/tests/__init__.py
  account_invoice_import_facturx/tests/files/Facture_FR_BASIC.pdf
  account_invoice_import_facturx/tests/files/Facture_FR_BASICWL.pdf
  account_invoice_import_facturx/tests/files/Facture_FR_EN16931.pdf
  account_invoice_import_facturx/tests/files/Facture_FR_EXTENDED.pdf
  account_invoice_import_facturx/tests/files/Facture_FR_MINIMUM.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_BASIC_Einfach.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_BASIC_Rechnungskorrektur.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_COMFORT_Einfach.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_COMFORT_Einfach.pdf-ZUGFeRD-invoice.xml
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_COMFORT_Haftpflichtversicherung_Versicherungssteuer.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_COMFORT_Kraftfahrversicherung_Bruttopreise.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_COMFORT_Rabatte.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_COMFORT_Rechnungskorrektur.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_COMFORT_SEPA_Prenotification.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_COMFORT_Sachversicherung_berechneter_Steuersatz.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_EXTENDED_Kostenrechnung.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_EXTENDED_Rechnungskorrektur.pdf
  account_invoice_import_facturx/tests/files/ZUGFeRD_1p0_EXTENDED_Warenrechnung.pdf
  account_invoice_import_facturx/tests/test_facturx.py
  account_invoice_import_facturx/wizard/__init__.py
  account_invoice_import_facturx/wizard/account_invoice_import.py
  account_invoice_import_facturx/wizard/account_invoice_import_view.xml
  requirements.txt
  setup/account_invoice_import_facturx/odoo/addons/account_invoice_import_facturx
  setup/account_invoice_import_facturx/setup.py
Labels: needs review, bot is merging ⏳

#395 [14.0][MIG] account_invoice_download
  account_invoice_download/README.rst
  account_invoice_download/__init__.py
  account_invoice_download/__manifest__.py
  account_invoice_download/data/cron.xml
  account_invoice_download/i18n/account_invoice_download.pot
  account_invoice_download/i18n/nl.po
  account_invoice_download/models/__init__.py
  account_invoice_download/models/account_invoice_download_config.py
  account_invoice_download/models/account_invoice_download_log.py
  account_invoice_download/models/account_invoice_import_config.py
  account_invoice_download/readme/CONFIGURE.rst
  account_invoice_download/readme/CONTRIBUTORS.rst
  account_invoice_download/readme/DESCRIPTION.rst
  account_invoice_download/readme/INSTALL.rst
  account_invoice_download/security/ir.model.access.csv
  account_invoice_download/security/rule.xml
  account_invoice_download/static/description/icon.png
  account_invoice_download/views/account_invoice_download_config.xml
  account_invoice_download/views/account_invoice_download_log.xml
  account_invoice_download/views/account_invoice_import_config.xml
  account_invoice_download/wizard/__init__.py
  account_invoice_download/wizard/account_invoice_download_credentials.py
  account_invoice_download/wizard/account_invoice_download_credentials_view.xml
  setup/account_invoice_download/odoo/addons/account_invoice_download
  setup/account_invoice_download/setup.py
Labels: approved, bot is merging ⏳

#255 [14.0][MIG] account_einvoice_generate
  account_einvoice_generate/README.rst
  account_einvoice_generate/__init__.py
  account_einvoice_generate/__manifest__.py
  account_einvoice_generate/i18n/account_e-invoice_generate.pot
  account_einvoice_generate/i18n/hr.po
  account_einvoice_generate/models/__init__.py
  account_einvoice_generate/models/account_move.py
  account_einvoice_generate/models/res_company.py
  account_einvoice_generate/readme/CONFIGURE.rst
  account_einvoice_generate/readme/CONTRIBUTORS.rst
  account_einvoice_generate/readme/DESCRIPTION.rst
  account_einvoice_generate/readme/INSTALL.rst
  account_einvoice_generate/static/description/icon.png
  account_einvoice_generate/static/description/index.html
  account_einvoice_generate/tests/__init__.py
  account_einvoice_generate/tests/test_einvoice_generate.py
  account_einvoice_generate/views/res_config_settings.xml
  account_einvoice_generate/wizards/__init__.py
  account_einvoice_generate/wizards/res_config_settings.py
  setup/account_einvoice_generate/odoo/addons/account_einvoice_generate
  setup/account_einvoice_generate/setup.py
Labels: needs review, bot is merging ⏳

#397 [14.0][MIG] account_invoice_download_ovh
  account_invoice_download_ovh/README.rst
  account_invoice_download_ovh/__init__.py
  account_invoice_download_ovh/__manifest__.py
  account_invoice_download_ovh/demo/ovh_demo.xml
  account_invoice_download_ovh/i18n/account_invoice_download_ovh.pot
  account_invoice_download_ovh/models/__init__.py
  account_invoice_download_ovh/models/account_invoice_download_config.py
  account_invoice_download_ovh/readme/CONFIGURE.rst
  account_invoice_download_ovh/readme/CONTRIBUTORS.rst
  account_invoice_download_ovh/readme/DESCRIPTION.rst
  account_invoice_download_ovh/readme/INSTALL.rst
  account_invoice_download_ovh/readme/USAGE.rst
  account_invoice_download_ovh/security/ir.model.access.csv
  account_invoice_download_ovh/static/description/icon.png
  account_invoice_download_ovh/views/account_invoice_download_config.xml
  account_invoice_download_ovh/wizard/__init__.py
  account_invoice_download_ovh/wizard/ovh_api_credentials.py
  account_invoice_download_ovh/wizard/ovh_api_credentials_view.xml
  requirements.txt
  setup/account_invoice_download_ovh/odoo/addons/account_invoice_download_ovh
  setup/account_invoice_download_ovh/setup.py
Labels: bot is merging ⏳

#441 [FIX] edi_voxel_account_invoice: send button not shown in posted invoices.
  edi_voxel_account_invoice/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#438 [14.0][IMP] base_ubl: return supplier and customer nodes to allow customization
  base_ubl/models/ubl.py
Labels: approved, ready to merge, bot is merging ⏳

#444 [FIX] edi_voxel_account_invoice: Fix non exists number field. Replaced by name.
  edi_voxel_account_invoice/reports/report_voxel_invoice.py
Labels: approved, bot is merging ⏳

#442 [14.0][IMP] base_ubl: add hooks to allow customization
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#447 [14.0] sale_order_import: misc fix/imp
  sale_order_import/wizard/sale_order_import.py
Labels: approved, bot is merging ⏳

#351 [13.0][ADD] account_invoice_export_server_env
  account_invoice_export_server_env/__init__.py
  account_invoice_export_server_env/__manifest__.py
  account_invoice_export_server_env/models/__init__.py
  account_invoice_export_server_env/models/transmit_method.py
  account_invoice_export_server_env/readme/DESCRIPTION.rst
  setup/account_invoice_export_server_env/odoo/addons/account_invoice_export_server_env
  setup/account_invoice_export_server_env/setup.py
Labels: bot is merging ⏳
