Repository OCA/edi, pull requests merged in 2021-03, with the labels that each got.

#337 [13.0][FIX] edi_voxel_stock_picking: Crash when a picking is cancelled
  edi_voxel_stock_picking/models/stock_picking.py
Labels: approved, bot is merging ⏳

#295 [13.0] edi: refactor component lookup
  edi/components/base.py
  edi/models/edi_backend.py
  edi/models/edi_exchange_consumer_mixin.py
  edi/tests/__init__.py
  edi/tests/fake_components.py
  edi/tests/test_backend_base.py
  edi/tests/test_component_match.py
  edi_exchange_template/components/common.py
  edi_exchange_template/models/edi_backend.py
  edi_exchange_template/tests/test_edi_backend_output.py
  edi_storage/components/base.py
  edi_storage/components/check.py
  edi_storage/components/send.py
  edi_storage/models/edi_backend.py
  edi_storage/tests/common.py
  edi_storage/tests/test_component_match.py
  edi_storage/tests/test_components_base.py
  edi_xml/tests/test_xml.py
Labels: approved, bot is merging ⏳, ready to merge

#338 [13.0][FIX] edi_voxel_account_invoice: Fix tests computen in the same company
  edi_voxel_account_invoice/tests/test_voxel_account_invoice.py
Labels: bot is merging ⏳

#347 Backport of Base_edi
  base_edi/README.rst
  base_edi/__init__.py
  base_edi/__manifest__.py
  base_edi/data/module_category.xml
  base_edi/i18n/base_edi.pot
  base_edi/i18n/nl.po
  base_edi/readme/CONTRIBUTORS.rst
  base_edi/readme/DESCRIPTION.rst
  base_edi/readme/ROADMAP.rst
  base_edi/security/edi_groups.xml
  base_edi/static/description/icon.png
  base_edi/static/description/icon.svg
  base_edi/static/description/index.html
  base_edi/views/edi_menu.xml
Labels: approved, bot is merging ⏳

#286 [ADD] edi_webservice
  edi_webservice/README.rst
  edi_webservice/__init__.py
  edi_webservice/__manifest__.py
  edi_webservice/models/__init__.py
  edi_webservice/models/edi_backend.py
  edi_webservice/readme/CONTRIBUTORS.rst
  edi_webservice/readme/DESCRIPTION.rst
  edi_webservice/security/ir.model.access.csv
  edi_webservice/static/description/icon.png
  edi_webservice/tests/__init__.py
  edi_webservice/tests/test_edi_webservice.py
  edi_webservice/views/edi_backend.xml
  test-requirements.txt
  webservice/README.rst
  webservice/__init__.py
  webservice/__manifest__.py
  webservice/components/__init__.py
  webservice/components/base_adapter.py
  webservice/components/request_adapter.py
  webservice/models/__init__.py
  webservice/models/webservice_backend.py
  webservice/readme/CONTRIBUTORS.rst
  webservice/readme/DESCRIPTION.rst
  webservice/security/ir.model.access.csv
  webservice/static/description/icon.png
  webservice/static/description/index.html
  webservice/tests/__init__.py
  webservice/tests/common.py
  webservice/tests/test_webservice.py
  webservice/views/webservice_backend.xml
Labels: bot is merging ⏳

#279 [13.0] edi: add jobs conf
  edi/__manifest__.py
  edi/data/cron.xml
  edi/data/job_channel.xml
  edi/data/job_function.xml
  edi/models/edi_backend.py
  edi/tests/__init__.py
  edi/tests/test_backend_jobs.py
  edi/tests/test_backend_output.py
  edi/tests/test_backend_validate.py
  edi/tests/test_edi_backend_cron.py
  edi_exchange_template/models/edi_backend.py
  edi_exchange_template/models/edi_exchange_template_output.py
  edi_exchange_template/tests/test_edi_backend_output.py
Labels: approved, bot is merging ⏳

#290 [12.0][FIX] account_invoice_ubl_email_attachment: attach only the most recently generated UBL file
  account_invoice_ubl_email_attachment/models/mail_template.py
Labels: approved, bot is merging ⏳, ready to merge

#289 [11.0][FIX] account_invoice_ubl_email_attachment: attach only the most recently generated UBL file
  account_invoice_ubl_email_attachment/models/mail_template.py
Labels: approved, bot is merging ⏳, ready to merge

#241 [13.0][ADD] sale_order_import_ubl_http
  oca_dependencies.txt
  sale_order_import_ubl_http/__init__.py
  sale_order_import_ubl_http/__manifest__.py
  sale_order_import_ubl_http/controllers/__init__.py
  sale_order_import_ubl_http/controllers/main.py
  sale_order_import_ubl_http/data/res_users.xml
  sale_order_import_ubl_http/models/__init__.py
  sale_order_import_ubl_http/models/res_company.py
  sale_order_import_ubl_http/models/res_config_settings.py
  sale_order_import_ubl_http/models/sale_order.py
  sale_order_import_ubl_http/readme/CONTRIBUTORS.rst
  sale_order_import_ubl_http/readme/DESCRIPTION.rst
  sale_order_import_ubl_http/readme/USAGE.rst
  sale_order_import_ubl_http/tests/__init__.py
  sale_order_import_ubl_http/tests/examples/UBL-Order-2.0-Example.xml
  sale_order_import_ubl_http/tests/test_sale_order_import_endpoint.py
  sale_order_import_ubl_http/views/res_config_settings.xml
  setup/sale_order_import_ubl_http/odoo/addons/sale_order_import_ubl_http
  setup/sale_order_import_ubl_http/setup.py
Labels: bot is merging ⏳
