Repository OCA/edi, pull requests merged in 2021-10, with the labels that each got.

#453 [14.0][FIX] edi_storage: incorrect call to output checker in receive component
  edi_storage_oca/components/receive.py
Labels: approved, bot is merging ⏳

#439 [13.0][FIX] edi_storage: incorrect call to output checker in receive component.
  account_invoice_export_server_env/README.rst
  account_invoice_export_server_env/readme/DESCRIPTION.rst
  account_invoice_export_server_env/static/description/index.html
  edi_storage/components/receive.py
Labels: approved, ready to merge, bot is merging ⏳

#322 [MIG] base_ebill_payment_contract: Migration to 14.0
  base_ebill_payment_contract/README.rst
  base_ebill_payment_contract/__init__.py
  base_ebill_payment_contract/__manifest__.py
  base_ebill_payment_contract/demo/ebill_payment_contract.xml
  base_ebill_payment_contract/i18n/base_ebill_payment_contract.pot
  base_ebill_payment_contract/models/__init__.py
  base_ebill_payment_contract/models/ebill_payment_contract.py
  base_ebill_payment_contract/models/res_partner.py
  base_ebill_payment_contract/readme/CONTRIBUTORS.rst
  base_ebill_payment_contract/readme/CREDITS.rst
  base_ebill_payment_contract/readme/DESCRIPTION.rst
  base_ebill_payment_contract/readme/USAGE.rst
  base_ebill_payment_contract/security/ir.model.access.csv
  base_ebill_payment_contract/static/description/icon.png
  base_ebill_payment_contract/static/description/index.html
  base_ebill_payment_contract/tests/__init__.py
  base_ebill_payment_contract/tests/test_base_ebill_payment_contract.py
  base_ebill_payment_contract/views/ebill_payment_contract.xml
  setup/base_ebill_payment_contract/odoo/addons/base_ebill_payment_contract
  setup/base_ebill_payment_contract/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#452 [14.0][MIG] sale_order_customer_free_ref: Migration to 14.0
  sale_order_customer_free_ref/README.rst
  sale_order_customer_free_ref/__init__.py
  sale_order_customer_free_ref/__manifest__.py
  sale_order_customer_free_ref/i18n/sale_order_customer_free_ref.pot
  sale_order_customer_free_ref/models/__init__.py
  sale_order_customer_free_ref/models/account_move.py
  sale_order_customer_free_ref/models/sale_order.py
  sale_order_customer_free_ref/readme/CONTRIBUTORS.rst
  sale_order_customer_free_ref/readme/CREDITS.rst
  sale_order_customer_free_ref/readme/DESCRIPTION.rst
  sale_order_customer_free_ref/static/description/icon.png
  sale_order_customer_free_ref/static/description/index.html
  sale_order_customer_free_ref/tests/__init__.py
  sale_order_customer_free_ref/tests/test_sale_order_customer_free_ref.py
  sale_order_customer_free_ref/views/account_move.xml
  sale_order_customer_free_ref/views/sale_order.xml
  setup/sale_order_customer_free_ref/odoo/addons/sale_order_customer_free_ref
  setup/sale_order_customer_free_ref/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#464 [14.0] [MIG] account_invoice_export_server_env
  account_invoice_export_server_env/README.rst
  account_invoice_export_server_env/__init__.py
  account_invoice_export_server_env/__manifest__.py
  account_invoice_export_server_env/i18n/account_invoice_export_server_env.pot
  account_invoice_export_server_env/models/__init__.py
  account_invoice_export_server_env/models/transmit_method.py
  account_invoice_export_server_env/readme/DESCRIPTION.rst
  account_invoice_export_server_env/static/description/icon.png
  account_invoice_export_server_env/static/description/index.html
  setup/account_invoice_export_server_env/odoo/addons/account_invoice_export_server_env
  setup/account_invoice_export_server_env/setup.py
Labels: approved, bot is merging ⏳

#455 [IMP] edi_account
  edi_account/__manifest__.py
  edi_account/models/account_move.py
  edi_account/views/account_move.xml
  edi_account/views/edi_exchange_record.xml
Labels: approved, ready to merge, bot is merging ⏳

#384 [13.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .isort.cfg
  .pre-commit-config.yaml
  .travis.yml
  account_invoice_export/__manifest__.py
  account_invoice_export_server_env/__manifest__.py
  account_invoice_ubl/__manifest__.py
  account_invoice_ubl_email_attachment/__manifest__.py
  base_business_document_import/models/business_document_import.py
  base_edi/__manifest__.py
  base_ubl/__manifest__.py
  base_ubl_payment/__manifest__.py
  edi/__manifest__.py
  edi_exchange_template/__manifest__.py
  edi_storage/__manifest__.py
  edi_voxel/__manifest__.py
  edi_voxel_account_invoice/__manifest__.py
  edi_voxel_sale_order_import/__manifest__.py
  edi_voxel_stock_picking/__manifest__.py
  edi_xml/__manifest__.py
  partner_identification_import/models/business_document_import.py
  purchase_order_ubl/__manifest__.py
  purchase_stock_ubl/__manifest__.py
  sale_order_customer_free_ref/__manifest__.py
  sale_order_import/__manifest__.py
  sale_order_import_ubl/__manifest__.py
  sale_order_import_ubl_customer_free_ref/__manifest__.py
  sale_order_import_ubl_http/__manifest__.py
  sale_order_ubl/__manifest__.py
Labels: help wanted, needs review, bot is merging ⏳

#288 [MIG][14.0] account_invoice_facturx
  account_invoice_facturx/README.rst
  account_invoice_facturx/__init__.py
  account_invoice_facturx/__manifest__.py
  account_invoice_facturx/hooks.py
  account_invoice_facturx/i18n/account_invoice_factur-x.pot
  account_invoice_facturx/i18n/account_invoice_facturx.pot
  account_invoice_facturx/i18n/de.po
  account_invoice_facturx/i18n/es.po
  account_invoice_facturx/i18n/fr.po
  account_invoice_facturx/models/__init__.py
  account_invoice_facturx/models/account_move.py
  account_invoice_facturx/models/company.py
  account_invoice_facturx/models/ir_actions_report.py
  account_invoice_facturx/readme/CONFIGURE.rst
  account_invoice_facturx/readme/CONTRIBUTORS.rst
  account_invoice_facturx/readme/DESCRIPTION.rst
  account_invoice_facturx/readme/INSTALL.rst
  account_invoice_facturx/static/description/icon.png
  account_invoice_facturx/static/description/index.html
  account_invoice_facturx/static/logos/factur-x-basic.png
  account_invoice_facturx/static/logos/factur-x-basicwl.png
  account_invoice_facturx/static/logos/factur-x-en16931.png
  account_invoice_facturx/static/logos/factur-x-extended.png
  account_invoice_facturx/static/logos/factur-x-minimum.png
  account_invoice_facturx/tests/__init__.py
  account_invoice_facturx/tests/test_facturx_invoice.py
  account_invoice_facturx/views/report_invoice.xml
  account_invoice_facturx/views/res_config_settings.xml
  account_invoice_facturx/views/res_partner.xml
  account_invoice_facturx/wizards/__init__.py
  account_invoice_facturx/wizards/res_config_settings.py
  setup/account_invoice_facturx/odoo/addons/account_invoice_facturx
  setup/account_invoice_facturx/setup.py
Labels: bot is merging ⏳
