Repository OCA/edi, pull requests merged in 2021-07, with the labels that each got.

#402 [13.0][IMP] edi_storage: implement basis of the input process.
  edi/models/edi_backend.py
  edi/tests/common.py
  edi/views/edi_exchange_record_views.xml
  edi_storage/__manifest__.py
  edi_storage/components/__init__.py
  edi_storage/components/base.py
  edi_storage/components/receive.py
  edi_storage/data/cron.xml
  edi_storage/data/job_channel_data.xml
  edi_storage/data/queue_job_function_data.xml
  edi_storage/models/__init__.py
  edi_storage/models/edi_backend.py
  edi_storage/models/edi_exchange_type.py
  edi_storage/readme/CONTRIBUTORS.rst
  edi_storage/tests/common.py
  edi_storage/tests/test_edi_backend_storage.py
Labels: approved, bot is merging ⏳

#407 [14.0][IMP] edi_storage_oca: implement basis of the input process.
  edi_oca/models/edi_backend.py
  edi_oca/tests/common.py
  edi_oca/views/edi_exchange_record_views.xml
  edi_storage_oca/__manifest__.py
  edi_storage_oca/components/__init__.py
  edi_storage_oca/components/base.py
  edi_storage_oca/components/receive.py
  edi_storage_oca/data/cron.xml
  edi_storage_oca/data/job_channel_data.xml
  edi_storage_oca/data/queue_job_function_data.xml
  edi_storage_oca/models/__init__.py
  edi_storage_oca/models/edi_backend.py
  edi_storage_oca/models/edi_exchange_type.py
  edi_storage_oca/readme/CONTRIBUTORS.rst
  edi_storage_oca/tests/common.py
  edi_storage_oca/tests/test_edi_backend_storage.py
Labels: approved, bot is merging ⏳

#408 [13.0][IMP] edi_storage: add listener to move files to done/error dirs
  edi/models/edi_backend.py
  edi_storage/components/__init__.py
  edi_storage/components/listener.py
  edi_storage/tests/__init__.py
  edi_storage/tests/test_edi_storage_listener.py
Labels: bot is merging ⏳

#409 [13.0][FIX] account_invoice_ubl: do not force report rendering
  account_invoice_ubl/models/ir_actions_report.py
Labels: approved, bot is merging ⏳

#413 [13.0][FIX] edi_storage: `list_files` expects a string.
  edi_storage/components/listener.py
Labels: bot is merging ⏳

#410 [14.0][IMP] edi_storage: add listener to move files to done/error dirs
  edi_oca/models/edi_backend.py
  edi_storage_oca/components/__init__.py
  edi_storage_oca/components/listener.py
  edi_storage_oca/tests/__init__.py
  edi_storage_oca/tests/test_edi_storage_listener.py
Labels: approved, bot is merging ⏳

#416 [13.0][IMP] base_ubl: add _ubl_get_seller_code_from_product method
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#412 [13.0][FIX] base_ubl: cbc fields where set as cac
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#417 [14.0][IMP] base_ubl: add _ubl_get_seller_code_from_product
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#418 [14.0][FIX] base_ubl: cbc fields where set as cac
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#421 [13.0][IMP] account_invoice_ubl & base_ubl: add hooks
  account_invoice_ubl/models/account_move.py
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#390 [14.0] [mig] account_invoice_import_ubl
  account_invoice_import_ubl/README.rst
  account_invoice_import_ubl/__init__.py
  account_invoice_import_ubl/__manifest__.py
  account_invoice_import_ubl/demo/demo_data.xml
  account_invoice_import_ubl/i18n/account_invoice_import_ubl.pot
  account_invoice_import_ubl/i18n/fr.po
  account_invoice_import_ubl/i18n/sl.po
  account_invoice_import_ubl/readme/CONFIGURE.rst
  account_invoice_import_ubl/readme/CONTRIBUTORS.rst
  account_invoice_import_ubl/readme/DESCRIPTION.rst
  account_invoice_import_ubl/readme/USAGE.rst
  account_invoice_import_ubl/static/description/icon.png
  account_invoice_import_ubl/static/description/index.html
  account_invoice_import_ubl/tests/__init__.py
  account_invoice_import_ubl/tests/files/UBLInvoice-multitankcard-line_adjust.xml
  account_invoice_import_ubl/tests/files/UBLKetentest_Referentiefactuur_20150100.xml
  account_invoice_import_ubl/tests/files/efff_BE0505890632_160421_Inv_16117778.xml
  account_invoice_import_ubl/tests/test_ubl.py
  account_invoice_import_ubl/wizard/__init__.py
  account_invoice_import_ubl/wizard/account_invoice_import.py
  account_invoice_import_ubl/wizard/account_invoice_import_view.xml
  setup/account_invoice_import_ubl/odoo/addons/account_invoice_import_ubl
  setup/account_invoice_import_ubl/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#401 [13.0][FIX] webservice: server.env.mixin needs to be inherited
  webservice/models/webservice_backend.py
Labels: approved, bot is merging ⏳, ready to merge

#424 [14.0][FIX] webservice: server.env.mixin needs to be inherited
  webservice/models/webservice_backend.py
Labels: approved, bot is merging ⏳
