Repository OCA/edi, pull requests merged in 2021-06, with the labels that each got.

#387 [14.0][MIG] account_invoice_import
  account_invoice_import/README.rst
  account_invoice_import/__init__.py
  account_invoice_import/__manifest__.py
  account_invoice_import/i18n/account_invoice_import.pot
  account_invoice_import/i18n/de.po
  account_invoice_import/i18n/es.po
  account_invoice_import/i18n/fr.po
  account_invoice_import/i18n/sl.po
  account_invoice_import/images/sshot-wizard1.png
  account_invoice_import/models/__init__.py
  account_invoice_import/models/account_invoice_import_config.py
  account_invoice_import/models/account_move.py
  account_invoice_import/models/res_company.py
  account_invoice_import/models/res_partner.py
  account_invoice_import/readme/CONFIGURE.rst
  account_invoice_import/readme/CONTRIBUTORS.rst
  account_invoice_import/readme/DESCRIPTION.rst
  account_invoice_import/readme/ROADMAP.rst
  account_invoice_import/readme/USAGE.rst
  account_invoice_import/scripts/inotify-sample.sh
  account_invoice_import/scripts/mass_invoice_import.py
  account_invoice_import/security/ir.model.access.csv
  account_invoice_import/security/rule.xml
  account_invoice_import/static/description/icon.png
  account_invoice_import/static/description/index.html
  account_invoice_import/tests/__init__.py
  account_invoice_import/tests/test_invoice_import.py
  account_invoice_import/views/account_invoice.xml
  account_invoice_import/views/account_invoice_import_config.xml
  account_invoice_import/views/account_journal_dashboard.xml
  account_invoice_import/views/res_config_settings.xml
  account_invoice_import/views/res_partner.xml
  account_invoice_import/wizard/__init__.py
  account_invoice_import/wizard/account_invoice_import.py
  account_invoice_import/wizard/account_invoice_import_view.xml
  account_invoice_import/wizard/res_config_settings.py
  setup/account_invoice_import/odoo/addons/account_invoice_import
  setup/account_invoice_import/setup.py
Labels: approved, bot is merging ⏳

#302 [MIG] sale_order_import: Migration to 14.0
  sale_order_import/README.rst
  sale_order_import/__init__.py
  sale_order_import/__manifest__.py
  sale_order_import/i18n/es.po
  sale_order_import/i18n/fr.po
  sale_order_import/i18n/sale_order_import.pot
  sale_order_import/models/__init__.py
  sale_order_import/models/sale.py
  sale_order_import/readme/CONTRIBUTORS.rst
  sale_order_import/readme/CREDITS.rst
  sale_order_import/readme/DESCRIPTION.rst
  sale_order_import/readme/USAGE.rst
  sale_order_import/security/ir.model.access.csv
  sale_order_import/static/description/icon.png
  sale_order_import/static/description/index.html
  sale_order_import/tests/__init__.py
  sale_order_import/tests/test_order_import.py
  sale_order_import/tests/test_sale_order.py
  sale_order_import/wizard/__init__.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_import/wizard/sale_order_import_view.xml
  setup/sale_order_import/odoo/addons/sale_order_import
  setup/sale_order_import/setup.py
Labels: approved, bot is merging ⏳

#394 [14.0] several fixes on account_invoice_import
  account_invoice_import/models/res_partner.py
  account_invoice_import/views/account_invoice_import_config.xml
  account_invoice_import/views/res_partner.xml
  account_invoice_import/wizard/account_invoice_import.py
Labels: approved, bot is merging ⏳

#205 [IMP] account_invoice_import: Allow to use multicompany and define hooks
  account_invoice_import/wizard/account_invoice_import.py
Labels: approved, bot is merging ⏳, ready to merge

#256 [14.0][MIG] base_facturx
  base_facturx/README.rst
  base_facturx/__init__.py
  base_facturx/__manifest__.py
  base_facturx/data/zugferd_codes.xml
  base_facturx/i18n/base_zugferd.pot
  base_facturx/i18n/es.po
  base_facturx/models/__init__.py
  base_facturx/models/base_facturx.py
  base_facturx/readme/CONFIGURE.rst
  base_facturx/readme/CONTRIBUTORS.rst
  base_facturx/readme/DESCRIPTION.rst
  base_facturx/readme/USAGE.rst
  base_facturx/static/description/icon.png
  base_facturx/static/description/index.html
Labels: approved, bot is merging ⏳

#369 [12.0] account_invoice_import backport hooks from v13
  account_invoice_import/tests/test_invoice_import.py
  account_invoice_import/wizard/account_invoice_import.py
Labels: approved, bot is merging ⏳, ready to merge

#336 [14.0][MIG] account_invoice_import_invoice2data
  .travis.yml
  account_invoice_import_invoice2data/README.rst
  account_invoice_import_invoice2data/__init__.py
  account_invoice_import_invoice2data/__manifest__.py
  account_invoice_import_invoice2data/demo/demo_data.xml
  account_invoice_import_invoice2data/i18n/account_invoice_import_invoice2data.pot
  account_invoice_import_invoice2data/i18n/de.po
  account_invoice_import_invoice2data/i18n/es.po
  account_invoice_import_invoice2data/i18n/nl.po
  account_invoice_import_invoice2data/i18n/pt.po
  account_invoice_import_invoice2data/i18n/sl.po
  account_invoice_import_invoice2data/readme/CONFIGURE.rst
  account_invoice_import_invoice2data/readme/CONTRIBUTORS.rst
  account_invoice_import_invoice2data/readme/DESCRIPTION.rst
  account_invoice_import_invoice2data/readme/INSTALL.rst
  account_invoice_import_invoice2data/static/description/icon.png
  account_invoice_import_invoice2data/static/description/index.html
  account_invoice_import_invoice2data/tests/__init__.py
  account_invoice_import_invoice2data/tests/pdf/invoice_free_fiber_201507.pdf
  account_invoice_import_invoice2data/tests/test_invoice_import.py
  account_invoice_import_invoice2data/wizard/__init__.py
  account_invoice_import_invoice2data/wizard/account_invoice_import.py
  account_invoice_import_invoice2data/wizard/account_invoice_import_view.xml
  requirements.txt
  setup/account_invoice_import_invoice2data/odoo/addons/account_invoice_import_invoice2data
  setup/account_invoice_import_invoice2data/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#400 [13.0][FIX] edi_voxel_sale_order_import: Search products from customerinfo
  edi_voxel_sale_order_import/models/sale_order.py
  edi_voxel_sale_order_import/tests/test_voxel_sale_order_import.py
  edi_voxel_sale_order_import/tests/voxel_xml/Pedido_20190619_145750_0611125750634.xml
Labels: approved, bot is merging ⏳

#404 [FIX] edi: output might be not UTF-8 encodable, like PDFs
  edi/models/edi_backend.py
Labels: bot is merging ⏳
