Repository OCA/edi, pull requests merged in 2021-11, with the labels that each got.

#471 [14.0] Add endpoint_auth_api_key
  endpoint_auth_api_key/README.rst
  endpoint_auth_api_key/__init__.py
  endpoint_auth_api_key/__manifest__.py
  endpoint_auth_api_key/demo/api_key_demo.xml
  endpoint_auth_api_key/demo/endpoint_demo.xml
  endpoint_auth_api_key/models/__init__.py
  endpoint_auth_api_key/models/endpoint_mixin.py
  endpoint_auth_api_key/readme/CONTRIBUTORS.rst
  endpoint_auth_api_key/readme/DESCRIPTION.rst
  endpoint_auth_api_key/tests/__init__.py
  endpoint_auth_api_key/tests/test_endpoint.py
  endpoint_auth_api_key/tests/test_endpoint_controller.py
  endpoint_auth_api_key/views/endpoint_view.xml
  setup/endpoint_auth_api_key/odoo/addons/endpoint_auth_api_key
  setup/endpoint_auth_api_key/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#470 [14.0] Add edi_endpoint_oca
  edi_endpoint_oca/README.rst
  edi_endpoint_oca/__init__.py
  edi_endpoint_oca/__manifest__.py
  edi_endpoint_oca/controllers/__init__.py
  edi_endpoint_oca/controllers/main.py
  edi_endpoint_oca/demo/edi_backend_demo.xml
  edi_endpoint_oca/models/__init__.py
  edi_endpoint_oca/models/edi_backend.py
  edi_endpoint_oca/models/edi_backend_type.py
  edi_endpoint_oca/models/edi_endpoint.py
  edi_endpoint_oca/readme/CONFIGURE.rst
  edi_endpoint_oca/readme/CONTRIBUTORS.rst
  edi_endpoint_oca/readme/DESCRIPTION.rst
  edi_endpoint_oca/security/ir.model.access.csv
  edi_endpoint_oca/tests/__init__.py
  edi_endpoint_oca/tests/test_edi_endpoint.py
  edi_endpoint_oca/tests/test_edi_endpoint_controller.py
  edi_endpoint_oca/views/edi_backend_views.xml
  edi_endpoint_oca/views/edi_endpoint_views.xml
  edi_oca/components/base.py
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/tests/test_component_match.py
  edi_oca/tests/test_consumer_mixin.py
  edi_storage_oca/tests/__init__.py
  edi_storage_oca/tests/common.py
  edi_storage_oca/tests/test_component_match.py
  edi_storage_oca/tests/test_edi_backend_storage.py
  setup/edi_endpoint_oca/odoo/addons/edi_endpoint_oca
  setup/edi_endpoint_oca/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#472 [14.0] edi: fix wrong status bar display new exc record
  edi_oca/views/edi_exchange_record_views.xml
Labels: bot is merging ⏳

#477 [14.0][FWD][IMP] base_ubl: add hooks
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#479 [14.0][FWD] sale_order_import*
  sale_order_import/wizard/sale_order_import.py
  sale_order_import_ubl_customer_free_ref/__init__.py
  sale_order_import_ubl_customer_free_ref/__manifest__.py
  sale_order_import_ubl_customer_free_ref/readme/CONTRIBUTORS.rst
  sale_order_import_ubl_customer_free_ref/readme/DESCRIPTION.rst
  sale_order_import_ubl_customer_free_ref/tests/__init__.py
  sale_order_import_ubl_customer_free_ref/tests/files/UBL-Order-2.0-Example.xml
  sale_order_import_ubl_customer_free_ref/tests/files/UBL-Order-2.1-Example.xml
  sale_order_import_ubl_customer_free_ref/tests/test_ubl_order_import.py
  sale_order_import_ubl_customer_free_ref/wizard/__init__.py
  sale_order_import_ubl_customer_free_ref/wizard/sale_order_import.py
  setup/sale_order_import_ubl_customer_free_ref/odoo/addons/sale_order_import_ubl_customer_free_ref
  setup/sale_order_import_ubl_customer_free_ref/setup.py
Labels: bot is merging ⏳

#478 [14.0][FWD] base_ubl + partner_identification_import
  base_business_document_import/models/business_document_import.py
  base_ubl/models/ubl.py
  partner_identification_import/models/business_document_import.py
Labels: bot is merging ⏳

#473 [IMP] edi: External identifier must be unique on a type and backend
  edi/models/edi_exchange_record.py
Labels: approved, ready to merge, bot is merging ⏳

#480 [IMP] edi: fix external identifier
  edi_oca/models/edi_exchange_record.py
Labels: approved, bot is merging ⏳

#481 [FIX] endpoint: fix loading of demo data
  endpoint/__manifest__.py
Labels: bot is merging ⏳

#483 [14.0] Misc fix/imp
  edi_endpoint_oca/__manifest__.py
  edi_oca/models/edi_backend.py
  sale_order_import/wizard/sale_order_import.py
Labels: approved, bot is merging ⏳

#485 [14.0] endpoint_route_handler: reduce log noise
  endpoint_route_handler/models/endpoint_route_handler.py
  endpoint_route_handler/models/ir_http.py
Labels: bot is merging ⏳

#482 [14.0][MIG] account_invoice_ubl: Migration to 14.0
  account_invoice_ubl/README.rst
  account_invoice_ubl/__init__.py
  account_invoice_ubl/__manifest__.py
  account_invoice_ubl/hooks.py
  account_invoice_ubl/i18n/account_invoice_ubl.pot
  account_invoice_ubl/i18n/es.po
  account_invoice_ubl/i18n/fr.po
  account_invoice_ubl/i18n/hr.po
  account_invoice_ubl/i18n/nl.po
  account_invoice_ubl/models/__init__.py
  account_invoice_ubl/models/account_move.py
  account_invoice_ubl/models/ir_actions_report.py
  account_invoice_ubl/models/res_company.py
  account_invoice_ubl/models/res_config_settings.py
  account_invoice_ubl/readme/CONFIGURE.rst
  account_invoice_ubl/readme/CONTRIBUTORS.rst
  account_invoice_ubl/readme/DESCRIPTION.rst
  account_invoice_ubl/static/description/icon.png
  account_invoice_ubl/static/description/index.html
  account_invoice_ubl/tests/__init__.py
  account_invoice_ubl/tests/test_ubl_generate.py
  account_invoice_ubl/views/account_move.xml
  account_invoice_ubl/views/res_config_settings.xml
  setup/account_invoice_ubl/odoo/addons/account_invoice_ubl
  setup/account_invoice_ubl/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#234 [10.0] account_import_invoice - Add 2 hooks to get invoice content and partner
  account_invoice_import/wizard/account_invoice_import.py
Labels: needs fixing, approved, bot is merging ⏳
