Repository OCA/edi, pull requests merged in 2022-05, with the labels that each got.

#577 [13.0][IMP] edi: add exchange_filename search
  edi/views/edi_exchange_record_views.xml
Labels: bot is merging ⏳

#584 [FIX] edi_account_oca: Tests failing
  edi_account_oca/tests/test_edi.py
Labels: bot is merging ⏳

#580 [15.0][FW] edi_oca: add exchange_filename search
  edi_oca/views/edi_exchange_record_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#537 [REF] account_e-invoice_generate : do not exclude odoo modules, to avoid runboat failing
  account_e-invoice_generate/__manifest__.py
Labels: bot is merging ⏳

#579 [14.0][FW] edi_oca: add exchange_filename search
  edi_oca/views/edi_exchange_record_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#588 [IMP] edi_exchange_template: Allow users to see, but not edit
  edi_exchange_template_oca/security/ir_model_access.xml
Labels: bot is merging ⏳

#586 [IMP] edi_exchange_template: Allow users to see, but not edit
  edi_exchange_template/security/ir_model_access.xml
Labels: bot is merging ⏳

#589 [15.0][FIX] edi_storage_oca: Fix errors with get done/failed directories
  edi_storage_oca/components/base.py
Labels: bot is merging ⏳

#590 [14.0][FIX] edi_storage_oca: Fix errors with get done/failed directories
  edi_storage_oca/components/base.py
Labels: approved, bot is merging ⏳

#494 [14.0] Fix account_invoice_export wrong assignment
  account_invoice_export/models/account_move.py
Labels: bot is merging ⏳

#525 [14.0] Fix account_invoice_export resend button visibility
  account_invoice_export/views/account_move.xml
Labels: approved, ready to merge, bot is merging ⏳

#543 [14.0] sale_order_import: fix missing defaults
  sale_order_import/wizard/sale_order_import.py
Labels: approved, ready to merge, bot is merging ⏳

#549 [14.0] edi_sale_order_import: misc improvements
  edi_oca/__manifest__.py
  edi_oca/templates/exchange_chatter_msg.xml
  edi_sale_order_import/__manifest__.py
  edi_sale_order_import/components/process.py
  edi_sale_order_import/templates/exchange_chatter_msg.xml
  edi_sale_order_import/tests/__init__.py
  edi_sale_order_import/tests/test_process.py
Labels: approved, ready to merge, bot is merging ⏳

#524 [14.0][FIX] edi: remove span inside anchor to fix exchange record navigation
  edi_oca/templates/exchange_chatter_msg.xml
Labels: approved, ready to merge, bot is merging ⏳

#598 [14.0] account_invoice_import: fix error logging and add more test cov
  account_invoice_import/readme/CONTRIBUTORS.rst
  account_invoice_import/tests/test_invoice_import.py
  account_invoice_import/wizard/account_invoice_import.py
Labels: bot is merging ⏳

#529 [14.0] Add sale_order_packaging_import
  base_business_document_import/models/business_document_import.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_packaging_import/__init__.py
  sale_order_packaging_import/__manifest__.py
  sale_order_packaging_import/models/__init__.py
  sale_order_packaging_import/models/business_document_import.py
  sale_order_packaging_import/readme/CONTRIBUTORS.rst
  sale_order_packaging_import/readme/DESCRIPTION.rst
  sale_order_packaging_import/tests/__init__.py
  sale_order_packaging_import/tests/test_order_line_packaging_import.py
  sale_order_packaging_import/wizard/__init__.py
  sale_order_packaging_import/wizard/sale_order_import.py
  setup/sale_order_packaging_import/odoo/addons/sale_order_packaging_import
  setup/sale_order_packaging_import/setup.py
Labels: bot is merging ⏳

#596 [14.0] Add pdf_helper: stop copy/pasting code :)
  base_business_document_import/__manifest__.py
  base_business_document_import/models/business_document_import.py
  base_business_document_import/readme/CONTRIBUTORS.rst
  base_ubl/__manifest__.py
  base_ubl/models/ubl.py
  base_ubl/readme/CONTRIBUTORS.rst
  pdf_helper/README.rst
  pdf_helper/__init__.py
  pdf_helper/__manifest__.py
  pdf_helper/models/__init__.py
  pdf_helper/models/helper.py
  pdf_helper/readme/CONTRIBUTORS.rst
  pdf_helper/readme/DESCRIPTION.rst
  pdf_helper/readme/USAGE.rst
  pdf_helper/tests/__init__.py
  pdf_helper/tests/fixtures/pdf_with_xml_test.pdf
  pdf_helper/tests/test_helper.py
  pdf_helper/utils.py
  setup/pdf_helper/odoo/addons/pdf_helper
  setup/pdf_helper/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#595 [14.0] sale_order_import: increase test coverage
  sale_order_import/__manifest__.py
  sale_order_import/readme/CONTRIBUTORS.rst
  sale_order_import/tests/__init__.py
  sale_order_import/tests/common.py
  sale_order_import/tests/fixtures/test.pdf
  sale_order_import/tests/test_order_import.py
  sale_order_import/tests/test_parse_validate.py
  sale_order_import/tests/test_sale_order.py
  sale_order_import/wizard/sale_order_import.py
Labels: enhancement, bot is merging ⏳
