Repository OCA/edi, pull requests merged in 2022-03, with the labels that each got.

#535 [MIG] edi_account_oca: Migration to 15.0
  edi_account_oca/README.rst
  edi_account_oca/__init__.py
  edi_account_oca/__manifest__.py
  edi_account_oca/i18n/edi_account.pot
  edi_account_oca/i18n/edi_account_oca.pot
  edi_account_oca/i18n/fr.po
  edi_account_oca/models/__init__.py
  edi_account_oca/models/account_move.py
  edi_account_oca/readme/CONTRIBUTORS.rst
  edi_account_oca/readme/DESCRIPTION.rst
  edi_account_oca/static/description/icon.png
  edi_account_oca/static/description/index.html
  edi_account_oca/tests/__init__.py
  edi_account_oca/tests/test_edi.py
  edi_account_oca/views/account_journal.xml
  edi_account_oca/views/account_move.xml
  edi_account_oca/views/edi_exchange_record.xml
  edi_account_oca/views/res_partner.xml
  setup/edi_account_oca/odoo/addons/edi_account_oca
  setup/edi_account_oca/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#536 [15.0][MIG] edi_webservice_oca: Migration to 15.0
  edi_webservice_oca/README.rst
  edi_webservice_oca/__init__.py
  edi_webservice_oca/__manifest__.py
  edi_webservice_oca/i18n/edi_webservice.pot
  edi_webservice_oca/i18n/edi_webservice_oca.pot
  edi_webservice_oca/models/__init__.py
  edi_webservice_oca/models/edi_backend.py
  edi_webservice_oca/readme/CONTRIBUTORS.rst
  edi_webservice_oca/readme/DESCRIPTION.rst
  edi_webservice_oca/security/ir.model.access.csv
  edi_webservice_oca/static/description/icon.png
  edi_webservice_oca/static/description/index.html
  edi_webservice_oca/tests/__init__.py
  edi_webservice_oca/tests/test_edi_webservice.py
  edi_webservice_oca/views/edi_backend.xml
  setup/edi_webservice_oca/odoo/addons/edi_webservice_oca
  setup/edi_webservice_oca/setup.py
Labels: approved, bot is merging ⏳

#526 [13.0][ADD] edi_purchase_oca
  edi_purchase_oca/README.rst
  edi_purchase_oca/__init__.py
  edi_purchase_oca/__manifest__.py
  edi_purchase_oca/models/__init__.py
  edi_purchase_oca/models/purchase_order.py
  edi_purchase_oca/readme/CONTRIBUTORS.rst
  edi_purchase_oca/readme/DESCRIPTION.rst
  edi_purchase_oca/static/description/icon.png
  edi_purchase_oca/static/description/index.html
  edi_purchase_oca/views/edi_exchange_record_views.xml
  edi_purchase_oca/views/purchase_order_views.xml
  setup/edi_purchase_oca/odoo/addons/edi_purchase_oca
  setup/edi_purchase_oca/setup.py
Labels: approved, bot is merging ⏳

#539 [IMP] edi_webservice: Promote to Beta
  edi_webservice_oca/README.rst
  edi_webservice_oca/__manifest__.py
  edi_webservice_oca/static/description/index.html
Labels: bot is merging ⏳

#538 [14.0] webservice, edi_webservice: Promote to Beta
  edi_webservice_oca/README.rst
  edi_webservice_oca/__manifest__.py
  edi_webservice_oca/static/description/index.html
  webservice/__manifest__.py
Labels: bot is merging ⏳

#532 [14.0] endpoint: block all RPC calls
  endpoint/__manifest__.py
  endpoint/migrations/14.0.1.1.0/pre-migrate.py
  endpoint/models/endpoint_mixin.py
  endpoint/readme/DESCRIPTION.rst
Labels: approved, ready to merge, bot is merging ⏳

#491 [MIG][15.0] edi_storage_oca
  edi_storage_oca/README.rst
  edi_storage_oca/__init__.py
  edi_storage_oca/__manifest__.py
  edi_storage_oca/components/__init__.py
  edi_storage_oca/components/base.py
  edi_storage_oca/components/check.py
  edi_storage_oca/components/listener.py
  edi_storage_oca/components/receive.py
  edi_storage_oca/components/send.py
  edi_storage_oca/data/cron.xml
  edi_storage_oca/data/job_channel_data.xml
  edi_storage_oca/data/queue_job_function_data.xml
  edi_storage_oca/demo/edi_backend_demo.xml
  edi_storage_oca/models/__init__.py
  edi_storage_oca/models/edi_backend.py
  edi_storage_oca/models/edi_exchange_type.py
  edi_storage_oca/readme/CONTRIBUTORS.rst
  edi_storage_oca/readme/DESCRIPTION.rst
  edi_storage_oca/readme/USAGE.rst
  edi_storage_oca/security/ir_model_access.xml
  edi_storage_oca/static/description/icon.png
  edi_storage_oca/static/description/index.html
  edi_storage_oca/tests/__init__.py
  edi_storage_oca/tests/common.py
  edi_storage_oca/tests/test_component_match.py
  edi_storage_oca/tests/test_components_base.py
  edi_storage_oca/tests/test_edi_backend_storage.py
  edi_storage_oca/tests/test_edi_storage_listener.py
  edi_storage_oca/views/edi_backend_views.xml
  setup/edi_storage_oca/odoo/addons/edi_storage_oca
  setup/edi_storage_oca/setup.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#545 [FIX] sale_order_import_ubl_http: pre-commit issue
  sale_order_import_ubl_http/tests/test_sale_order_import_endpoint.py
Labels: bot is merging ⏳

#547 [14.0] account_invoice_import_invoice2data: pin dateparser=1.1.1
  account_invoice_import_invoice2data/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#540 [14.0] edi: misc fix/imp
  edi_oca/data/job_function.xml
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/templates/exchange_chatter_msg.xml
  edi_oca/tests/test_backend_base.py
  edi_oca/tests/test_backend_output.py
  edi_oca/tests/test_record.py
  edi_oca/views/edi_backend_views.xml
  edi_oca/views/edi_exchange_record_views.xml
  edi_oca/views/menuitems.xml
  edi_storage_oca/components/check.py
Labels: approved, ready to merge, bot is merging ⏳

#551 [FIX] edi_oca: Restore removed functions
  edi_oca/data/job_function.xml
  edi_oca/models/edi_backend.py
Labels: bot is merging ⏳
