Repository OCA/edi, pull requests merged in 2022-11, with the labels that each got.

#674 [MIG] [14.0] purchase_stock_ubl
  purchase_stock_ubl/README.rst
  purchase_stock_ubl/__init__.py
  purchase_stock_ubl/__manifest__.py
  purchase_stock_ubl/i18n/purchase_stock_ubl.pot
  purchase_stock_ubl/models/__init__.py
  purchase_stock_ubl/models/purchase.py
  purchase_stock_ubl/readme/CONTRIBUTORS.rst
  purchase_stock_ubl/readme/DESCRIPTION.rst
  purchase_stock_ubl/static/description/icon.png
  purchase_stock_ubl/static/description/index.html
  purchase_stock_ubl/tests/__init__.py
  purchase_stock_ubl/tests/test_purchase_order.py
  setup/purchase_stock_ubl/odoo/addons/purchase_stock_ubl
  setup/purchase_stock_ubl/setup.py
Labels: approved

#687 [14.0][ADD] product_import
  product_import/README.rst
  product_import/__init__.py
  product_import/__manifest__.py
  product_import/models/__init__.py
  product_import/readme/CONTRIBUTORS.rst
  product_import/readme/DESCRIPTION.rst
  product_import/security/ir.model.access.csv
  product_import/tests/__init__.py
  product_import/tests/common.py
  product_import/tests/test_parse_validate.py
  product_import/tests/test_product_import.py
  product_import/wizard/__init__.py
  product_import/wizard/product_import.py
  product_import/wizard/product_import_view.xml
  setup/product_import/odoo/addons/product_import
  setup/product_import/setup.py
Labels: approved, bot is merging ⏳

#690 [14.0][ADD] edi_account_invoice_import
  edi_account_invoice_import/README.rst
  edi_account_invoice_import/__init__.py
  edi_account_invoice_import/__manifest__.py
  edi_account_invoice_import/components/__init__.py
  edi_account_invoice_import/components/process.py
  edi_account_invoice_import/readme/CONTRIBUTORS.rst
  edi_account_invoice_import/readme/DESCRIPTION.rst
  edi_account_invoice_import/static/description/icon.png
  edi_account_invoice_import/static/description/index.html
  edi_account_invoice_import/templates/exchange_chatter_msg.xml
  edi_account_invoice_import/tests/__init__.py
  edi_account_invoice_import/tests/test_process.py
  setup/edi_account_invoice_import/odoo/addons/edi_account_invoice_import
  setup/edi_account_invoice_import/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#693 [FIX] edi: output might be not UTF-8 encodable, like PDFs
  edi_oca/models/edi_backend.py
  edi_oca/tests/result.pdf
  edi_oca/tests/test_backend_output.py
Labels: approved, bot is merging ⏳
