Repository OCA/edi, pull requests merged in 2022-08, with the labels that each got.

#636 [14.0] endpoint_auth_api_key: move to OCA/web-api
  endpoint_auth_api_key/README.rst
  endpoint_auth_api_key/__init__.py
  endpoint_auth_api_key/__manifest__.py
  endpoint_auth_api_key/demo/api_key_demo.xml
  endpoint_auth_api_key/demo/endpoint_demo.xml
  endpoint_auth_api_key/i18n/endpoint_auth_api_key.pot
  endpoint_auth_api_key/models/__init__.py
  endpoint_auth_api_key/models/endpoint_mixin.py
  endpoint_auth_api_key/readme/CONTRIBUTORS.rst
  endpoint_auth_api_key/readme/DESCRIPTION.rst
  endpoint_auth_api_key/static/description/icon.png
  endpoint_auth_api_key/static/description/index.html
  endpoint_auth_api_key/tests/__init__.py
  endpoint_auth_api_key/tests/test_endpoint.py
  endpoint_auth_api_key/tests/test_endpoint_controller.py
  endpoint_auth_api_key/views/endpoint_view.xml
  setup/endpoint_auth_api_key/odoo/addons/endpoint_auth_api_key
  setup/endpoint_auth_api_key/setup.py
Labels: bot is merging ⏳

#637 [14.0][MOV] webservice: move to OCA/web-api
  setup/webservice/odoo/addons/webservice
  setup/webservice/setup.py
  webservice/README.rst
  webservice/__init__.py
  webservice/__manifest__.py
  webservice/components/__init__.py
  webservice/components/base_adapter.py
  webservice/components/request_adapter.py
  webservice/i18n/fr.po
  webservice/i18n/webservice.pot
  webservice/models/__init__.py
  webservice/models/webservice_backend.py
  webservice/readme/CONTRIBUTORS.rst
  webservice/readme/DESCRIPTION.rst
  webservice/security/ir.model.access.csv
  webservice/static/description/icon.png
  webservice/static/description/index.html
  webservice/tests/__init__.py
  webservice/tests/common.py
  webservice/tests/test_webservice.py
  webservice/views/webservice_backend.xml
Labels: approved, bot is merging ⏳

#634 [14.0][MIG] edi_xml (and renamed to edi_xml_oca)
  edi_oca/__manifest__.py
  edi_oca/components/base.py
  edi_xml_oca/README.rst
  edi_xml_oca/__init__.py
  edi_xml_oca/__manifest__.py
  edi_xml_oca/components/__init__.py
  edi_xml_oca/components/xml_handler.py
  edi_xml_oca/i18n/edi_xml.pot
  edi_xml_oca/readme/CONTRIBUTORS.rst
  edi_xml_oca/readme/DESCRIPTION.rst
  edi_xml_oca/static/description/icon.png
  edi_xml_oca/static/description/index.html
  edi_xml_oca/tests/__init__.py
  edi_xml_oca/tests/common.py
  edi_xml_oca/tests/fixtures/Test.xsd
  edi_xml_oca/tests/test_xml.py
  edi_xml_oca/xmler.py
  requirements.txt
  setup/edi_xml_oca/edi_xml/odoo/addons/edi_xml
  setup/edi_xml_oca/edi_xml/setup.py
  setup/edi_xml_oca/odoo/addons/edi_xml
  setup/edi_xml_oca/odoo/addons/edi_xml_oca
  setup/edi_xml_oca/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#639 [14.0] edi_exchange_template_oca: fix xml_purge_nswrapper
  edi_exchange_template_oca/__manifest__.py
  edi_exchange_template_oca/tests/__init__.py
  edi_exchange_template_oca/tests/test_nswrapper.py
  edi_exchange_template_oca/utils.py
Labels: bot is merging ⏳

#635 [15.0][MIG] edi_backend_partner_oca
  edi_backend_partner_oca/README.rst
  edi_backend_partner_oca/__init__.py
  edi_backend_partner_oca/__manifest__.py
  edi_backend_partner_oca/i18n/edi_backend_partner.pot
  edi_backend_partner_oca/i18n/edi_backend_partner_oca.pot
  edi_backend_partner_oca/models/__init__.py
  edi_backend_partner_oca/models/edi_backend.py
  edi_backend_partner_oca/models/res_partner.py
  edi_backend_partner_oca/readme/CONTRIBUTORS.rst
  edi_backend_partner_oca/readme/DESCRIPTION.rst
  edi_backend_partner_oca/static/description/icon.png
  edi_backend_partner_oca/static/description/index.html
  edi_backend_partner_oca/tests/__init__.py
  edi_backend_partner_oca/tests/test_edi_backend_partner.py
  edi_backend_partner_oca/views/edi_backend_views.xml
  edi_backend_partner_oca/views/res_partner_views.xml
  setup/edi_backend_partner_oca/odoo/addons/edi_backend_partner_oca
  setup/edi_backend_partner_oca/setup.py
Labels: approved, bot is merging ⏳

#641 [15.0][MOV] webservice: move to OCA/web-api
  setup/webservice/odoo/addons/webservice
  setup/webservice/setup.py
  webservice/README.rst
  webservice/__init__.py
  webservice/__manifest__.py
  webservice/components/__init__.py
  webservice/components/base_adapter.py
  webservice/components/request_adapter.py
  webservice/i18n/fr.po
  webservice/i18n/webservice.pot
  webservice/models/__init__.py
  webservice/models/webservice_backend.py
  webservice/readme/CONTRIBUTORS.rst
  webservice/readme/DESCRIPTION.rst
  webservice/security/ir.model.access.csv
  webservice/static/description/icon.png
  webservice/static/description/index.html
  webservice/tests/__init__.py
  webservice/tests/common.py
  webservice/tests/test_webservice.py
  webservice/views/webservice_backend.xml
Labels: bot is merging ⏳

#582 [15.0] edi_storage: path configurable by type and param
  edi_storage_oca/components/base.py
  edi_storage_oca/components/listener.py
  edi_storage_oca/components/receive.py
  edi_storage_oca/components/send.py
  edi_storage_oca/models/edi_backend.py
  edi_storage_oca/models/edi_exchange_type.py
  edi_storage_oca/tests/__init__.py
  edi_storage_oca/tests/common.py
  edi_storage_oca/tests/test_components_base.py
  edi_storage_oca/tests/test_edi_backend_storage.py
  edi_storage_oca/tests/test_exchange_type.py
Labels: approved, bot is merging ⏳

#640 [14.0] edi_oca: improve auto btns
  edi_oca/__manifest__.py
  edi_oca/migrations/14.0.1.10.0/post-migrate.py
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/static/src/js/widget_edi.js
  edi_oca/static/src/xml/widget_edi.xml
  edi_oca/templates/exchange_mixin_buttons.xml
  edi_oca/tests/test_consumer_mixin.py
  edi_oca/views/edi_exchange_type_views.xml
Labels: approved, bot is merging ⏳

#643 [14.0] edi: backend archive (port from v13) + integrate w/ edi_endpoint
  edi_endpoint_oca/models/edi_backend.py
  edi_endpoint_oca/tests/test_edi_endpoint.py
  edi_endpoint_oca/tests/test_edi_endpoint_controller.py
  edi_oca/models/edi_backend.py
  edi_oca/views/edi_backend_views.xml
Labels: approved, bot is merging ⏳

#645 [14.0] Misc improvements and fixes
  edi_exchange_template_oca/models/edi_exchange_template_output.py
  edi_exchange_template_oca/views/edi_exchange_template_output_views.xml
  edi_oca/models/__init__.py
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_id_mixin.py
  edi_oca/tests/test_backend_input.py
  edi_oca/tests/test_backend_process.py
  edi_oca/tests/test_consumer_mixin.py
  edi_oca/tests/test_edi_backend_cron.py
  edi_oca/tests/test_record.py
  edi_oca/tests/test_security.py
  edi_oca/wizards/edi_exchange_record_create_wiz.py
  edi_sale_order_import_ubl_endpoint/__manifest__.py
  edi_xml_oca/components/xml_handler.py
  sale_order_import_ubl/__manifest__.py
  sale_order_import_ubl/tests/common.py
  sale_order_import_ubl/tests/test_ubl_order_import.py
Labels: approved, bot is merging ⏳

#647 [14.0] edi_oca: misc fix/imp
  edi_exchange_template_oca/models/edi_exchange_template_mixin.py
  edi_exchange_template_oca/models/edi_exchange_template_output.py
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/templates/exchange_chatter_msg.xml
  edi_oca/tests/test_consumer_mixin.py
  edi_oca/tests/test_edi_backend_cron.py
  edi_oca/tests/test_exchange_type.py
  edi_oca/tests/test_record.py
  edi_oca/views/edi_exchange_type_views.xml
  edi_storage_oca/models/edi_backend.py
  edi_storage_oca/tests/test_edi_backend_storage.py
Labels: bot is merging ⏳

#642 [FIX][14.0]purchase_order_ubl - fix stack-trace in _render_qweb_pdf
  purchase_order_ubl/models/report.py
Labels: approved, ready to merge, bot is merging ⏳

#648 [14.0] edi_webservice: add generic send component
  edi_webservice_oca/__init__.py
  edi_webservice_oca/__manifest__.py
  edi_webservice_oca/components/__init__.py
  edi_webservice_oca/components/send.py
  edi_webservice_oca/demo/edi_backend.xml
  edi_webservice_oca/readme/CONFIGURATION.rst
  edi_webservice_oca/readme/CONTRIBUTORS.rst
  edi_webservice_oca/readme/DESCRIPTION.rst
  edi_webservice_oca/tests/__init__.py
  edi_webservice_oca/tests/common.py
  edi_webservice_oca/tests/test_backend.py
  edi_webservice_oca/tests/test_send.py
Labels: bot is merging ⏳
