Repository OCA/edi, pull requests merged in 2022-10, with the labels that each got.

#513 Add .oca-port.json
  .oca-port.json
  .pre-commit-config.yaml
Labels: help wanted, approved, ready to merge, bot is merging ⏳, stale

#666 [14.0] edi: drop ack record auto create
  edi_oca/models/edi_backend.py
  edi_oca/tests/test_edi_backend_cron.py
Labels: needs review, approved, bot is merging ⏳

#511 [14.0][MIG] edi_voxel > edi_voxel_oca
  edi_voxel_oca/README.rst
  edi_voxel_oca/__init__.py
  edi_voxel_oca/__manifest__.py
  edi_voxel_oca/data/data_voxel_uom.xml
  edi_voxel_oca/i18n/edi_voxel.pot
  edi_voxel_oca/i18n/es.po
  edi_voxel_oca/models/__init__.py
  edi_voxel_oca/models/account.py
  edi_voxel_oca/models/queue_job.py
  edi_voxel_oca/models/res_company.py
  edi_voxel_oca/models/res_config_settings.py
  edi_voxel_oca/models/res_partner.py
  edi_voxel_oca/models/uom_uom.py
  edi_voxel_oca/models/voxel_login.py
  edi_voxel_oca/models/voxel_mixin.py
  edi_voxel_oca/readme/CONTRIBUTORS.rst
  edi_voxel_oca/readme/DESCRIPTION.rst
  edi_voxel_oca/security/ir.model.access.csv
  edi_voxel_oca/security/voxel_security.xml
  edi_voxel_oca/static/description/icon.png
  edi_voxel_oca/static/description/index.html
  edi_voxel_oca/views/account_tax_views.xml
  edi_voxel_oca/views/product_uom_views.xml
  edi_voxel_oca/views/res_company_view.xml
  edi_voxel_oca/views/res_config_settings_views.xml
  edi_voxel_oca/views/res_partner_views.xml
  edi_voxel_oca/views/template_voxel_report.xml
  edi_voxel_oca/views/voxel_login_views.xml
  setup/edi_voxel_oca/odoo/addons/edi_voxel_oca
  setup/edi_voxel_oca/setup.py
Labels: approved, bot is merging ⏳, stale

#495 [13.0] Fix account_invoice_export wrong assignment
  account_invoice_export/models/account_move.py
Labels: bot is merging ⏳, stale

#672 [14.0] edi: fix _get_component ctx propagation
  edi_oca/models/edi_backend.py
Labels: approved, bot is merging ⏳

#673 [14.0] account_invoice_import_simple_pdf: allow to match partners on additionnal fields
  account_invoice_import_simple_pdf/wizard/account_invoice_import.py
Labels: bot is merging ⏳
