Repository OCA/edi, pull requests merged in 2022-01, with the labels that each got.

#499 [14.0] endpoint_route_handler important fixes
  endpoint/tests/test_endpoint.py
  endpoint/tests/test_endpoint_controller.py
  endpoint_route_handler/models/endpoint_route_handler.py
  endpoint_route_handler/models/ir_http.py
  endpoint_route_handler/registry.py
  endpoint_route_handler/tests/common.py
  endpoint_route_handler/tests/test_endpoint.py
  endpoint_route_handler/tests/test_endpoint_controller.py
Labels: bot is merging ⏳

#498 [14.0] Misc minor fixes for edi framework + endpoint
  edi_endpoint_oca/models/edi_backend.py
  edi_endpoint_oca/views/edi_endpoint_views.xml
  edi_oca/i18n/edi.pot
  edi_oca/i18n/edi_oca.pot
  edi_oca/i18n/fr.po
  edi_oca/models/edi_exchange_record.py
  edi_oca/templates/exchange_chatter_msg.xml
  edi_oca/views/edi_exchange_record_views.xml
  endpoint/views/endpoint_view.xml
  endpoint_auth_api_key/models/endpoint_mixin.py
  endpoint_auth_api_key/views/endpoint_view.xml
Labels: bot is merging ⏳

#514 Misc fix of authorship name
  edi_endpoint_oca/__manifest__.py
  edi_endpoint_oca/controllers/main.py
  edi_endpoint_oca/models/edi_backend.py
  edi_endpoint_oca/models/edi_backend_type.py
  edi_endpoint_oca/models/edi_endpoint.py
  edi_endpoint_oca/tests/test_edi_endpoint.py
  edi_endpoint_oca/tests/test_edi_endpoint_controller.py
  edi_endpoint_oca/views/edi_endpoint_views.xml
  endpoint/__manifest__.py
  endpoint/controllers/main.py
  endpoint/models/endpoint_mixin.py
  endpoint/tests/common.py
  endpoint/tests/test_endpoint.py
  endpoint/tests/test_endpoint_controller.py
  endpoint/views/endpoint_view.xml
  endpoint_auth_api_key/__manifest__.py
  endpoint_auth_api_key/models/endpoint_mixin.py
  endpoint_auth_api_key/tests/test_endpoint.py
  endpoint_auth_api_key/tests/test_endpoint_controller.py
  endpoint_auth_api_key/views/endpoint_view.xml
  endpoint_route_handler/__manifest__.py
  endpoint_route_handler/models/endpoint_route_handler.py
  endpoint_route_handler/models/ir_http.py
  endpoint_route_handler/registry.py
  endpoint_route_handler/tests/common.py
  endpoint_route_handler/tests/test_endpoint.py
  endpoint_route_handler/tests/test_endpoint_controller.py
Labels: bot is merging ⏳

#451 [14.0] Plug sale_order_import w/ EDI framework
  edi_sale_order_import/README.rst
  edi_sale_order_import/__init__.py
  edi_sale_order_import/__manifest__.py
  edi_sale_order_import/components/__init__.py
  edi_sale_order_import/components/process.py
  edi_sale_order_import/readme/CONTRIBUTORS.rst
  edi_sale_order_import/readme/DESCRIPTION.rst
  edi_sale_order_import_ubl/README.rst
  edi_sale_order_import_ubl/__init__.py
  edi_sale_order_import_ubl/__manifest__.py
  edi_sale_order_import_ubl/data/edi_exchange_type.xml
  edi_sale_order_import_ubl/readme/CONTRIBUTORS.rst
  edi_sale_order_import_ubl/readme/DESCRIPTION.rst
  edi_sale_order_import_ubl_endpoint/README.rst
  edi_sale_order_import_ubl_endpoint/__init__.py
  edi_sale_order_import_ubl_endpoint/__manifest__.py
  edi_sale_order_import_ubl_endpoint/data/endpoint.xml
  edi_sale_order_import_ubl_endpoint/readme/CONTRIBUTORS.rst
  edi_sale_order_import_ubl_endpoint/readme/DESCRIPTION.rst
  edi_ubl_oca/README.rst
  edi_ubl_oca/__init__.py
  edi_ubl_oca/__manifest__.py
  edi_ubl_oca/data/edi_backend_type.xml
  edi_ubl_oca/demo/edi_backend_demo.xml
  edi_ubl_oca/readme/CONTRIBUTORS.rst
  edi_ubl_oca/readme/DESCRIPTION.rst
  setup/edi_sale_order_import/odoo/addons/edi_sale_order_import
  setup/edi_sale_order_import/setup.py
  setup/edi_sale_order_import_ubl/odoo/addons/edi_sale_order_import_ubl
  setup/edi_sale_order_import_ubl/setup.py
  setup/edi_sale_order_import_ubl_endpoint/odoo/addons/edi_sale_order_import_ubl_endpoint
  setup/edi_sale_order_import_ubl_endpoint/setup.py
  setup/edi_ubl_oca/odoo/addons/edi_ubl_oca
  setup/edi_ubl_oca/setup.py
Labels: approved, bot is merging ⏳

#512 [14.0][FW] base_business_document_import: match product by packaging barcode too
  base_business_document_import/models/business_document_import.py
  base_business_document_import/tests/test_business_document_import.py
  sale_order_import_ubl/demo/demo_data.xml
  sale_order_import_ubl/tests/files/UBL-Order-2.1-Example.xml
  sale_order_import_ubl/tests/test_ubl_order_import.py
Labels: approved, bot is merging ⏳

#516 [14.0] endpoint_route_handler: fix rules by group
  endpoint_route_handler/registry.py
Labels: bot is merging ⏳

#501 [15.0][MIG] account_einvoice_generate
  account_einvoice_generate/README.rst
  account_einvoice_generate/__init__.py
  account_einvoice_generate/__manifest__.py
  account_einvoice_generate/i18n/account_e-invoice_generate.pot
  account_einvoice_generate/i18n/account_einvoice_generate.pot
  account_einvoice_generate/i18n/hr.po
  account_einvoice_generate/models/__init__.py
  account_einvoice_generate/models/account_move.py
  account_einvoice_generate/models/res_company.py
  account_einvoice_generate/readme/CONFIGURE.rst
  account_einvoice_generate/readme/CONTRIBUTORS.rst
  account_einvoice_generate/readme/DESCRIPTION.rst
  account_einvoice_generate/readme/INSTALL.rst
  account_einvoice_generate/static/description/icon.png
  account_einvoice_generate/static/description/index.html
  account_einvoice_generate/tests/__init__.py
  account_einvoice_generate/tests/test_einvoice_generate.py
  account_einvoice_generate/views/res_config_settings.xml
  account_einvoice_generate/wizards/__init__.py
  account_einvoice_generate/wizards/res_config_settings.py
  setup/account_einvoice_generate/odoo/addons/account_einvoice_generate
  setup/account_einvoice_generate/setup.py
Labels: bot is merging ⏳

#518 [14.0] sale_order_import: _parse_xml handle NotImplementedError
  sale_order_import/wizard/sale_order_import.py
Labels: enhancement, approved, bot is merging ⏳

#500 [15.0][MIG] base_facturx
  base_facturx/README.rst
  base_facturx/__init__.py
  base_facturx/__manifest__.py
  base_facturx/data/zugferd_codes.xml
  base_facturx/i18n/base_facturx.pot
  base_facturx/i18n/base_zugferd.pot
  base_facturx/i18n/es.po
  base_facturx/i18n/fr.po
  base_facturx/models/__init__.py
  base_facturx/models/base_facturx.py
  base_facturx/readme/CONFIGURE.rst
  base_facturx/readme/CONTRIBUTORS.rst
  base_facturx/readme/DESCRIPTION.rst
  base_facturx/readme/USAGE.rst
  base_facturx/static/description/icon.png
  base_facturx/static/description/index.html
  setup/base_facturx/odoo/addons/base_facturx
  setup/base_facturx/setup.py
Labels: bot is merging ⏳

#519 [14.0][FIX] Fix access right issues when using actions
  account_invoice_download/models/account_invoice_download_config.py
  account_invoice_download/wizard/account_invoice_download_credentials.py
  account_invoice_download_ovh/wizard/ovh_api_credentials.py
  account_invoice_import/models/res_partner.py
  account_invoice_import/wizard/account_invoice_import.py
  edi_backend_partner_oca/models/res_partner.py
  edi_endpoint_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/models/edi_exchange_record.py
  endpoint_auth_api_key/models/endpoint_mixin.py
Labels: bot is merging ⏳
