Repository OCA/edi, pull requests merged in 2022-06, with the labels that each got.

#592 edi_oca: allow to override dt for exchange filename
  edi_oca/models/edi_exchange_type.py
  edi_oca/tests/test_backend_base.py
  edi_oca/tests/test_exchange_type.py
Labels: bot is merging ⏳

#601 [13.0][FIX] remove PyPDF2 dependency
  base_business_document_import/__manifest__.py
  base_ubl/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#614 [FIX] edi_oca: Adapt tests
  edi_oca/tests/test_record.py
Labels: bot is merging ⏳

#591 edi_oca: allow to override dt for exchange filename
  edi_oca/models/edi_exchange_type.py
  edi_oca/tests/test_backend_base.py
  edi_oca/tests/test_exchange_type.py
Labels: approved, ready to merge, bot is merging ⏳

#570 [FIX][14.0] account_invoice_import_simple_pdf: use fix version of dateparser
  account_invoice_import_simple_pdf/__manifest__.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#593 [MIG] edi_stock_oca: Migration to 14.0
  edi_stock_oca/README.rst
  edi_stock_oca/__init__.py
  edi_stock_oca/__manifest__.py
  edi_stock_oca/i18n/edi_stock_oca.pot
  edi_stock_oca/models/__init__.py
  edi_stock_oca/models/stock_picking.py
  edi_stock_oca/readme/CONTRIBUTORS.rst
  edi_stock_oca/readme/DESCRIPTION.rst
  edi_stock_oca/static/description/icon.png
  edi_stock_oca/static/description/index.html
  edi_stock_oca/tests/__init__.py
  edi_stock_oca/tests/test_edi.py
  edi_stock_oca/views/res_partner.xml
  edi_stock_oca/views/stock_picking.xml
  setup/edi_stock_oca/odoo/addons/edi_stock_oca
  setup/edi_stock_oca/setup.py
Labels: approved, bot is merging ⏳
