Repository OCA/edi, pull requests merged in 2022-04, with the labels that each got.

#555 [14.0] endpoint_route_handler: dev status = Beta
  endpoint_route_handler/__manifest__.py
  endpoint_route_handler/readme/ROADMAP.rst
Labels: bot is merging ⏳

#552 [15.0] edi: misc fix/imp
  edi_oca/data/job_function.xml
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/templates/exchange_chatter_msg.xml
  edi_oca/tests/test_backend_base.py
  edi_oca/tests/test_backend_output.py
  edi_oca/tests/test_record.py
  edi_oca/views/edi_backend_views.xml
  edi_oca/views/edi_exchange_record_views.xml
  edi_oca/views/menuitems.xml
  edi_storage_oca/components/check.py
Labels: bot is merging ⏳

#560 [15.0] [IMP] edi_storage_oca: Update development status
  edi_storage_oca/README.rst
  edi_storage_oca/__manifest__.py
Labels: approved, bot is merging ⏳

#562 Updated Copier from template
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  base_edi/__manifest__.py
  edi/__manifest__.py
  edi_voxel/__manifest__.py
  edi_voxel_sale_order_import/__manifest__.py
  edi_voxel_stock_picking/__manifest__.py
  webservice/__manifest__.py
Labels: approved, ready to merge
