Repository OCA/edi, pull requests merged in 2022-12, with the labels that each got.

#694 [14.0] edi_exchange_template: add prettify option
  edi_exchange_template_oca/models/edi_exchange_template_output.py
  edi_exchange_template_oca/tests/test_edi_backend_output.py
  edi_exchange_template_oca/views/edi_exchange_template_output_views.xml
Labels: bot is merging ⏳

#683 [15.0][DCK] Updated from template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  edi_oca/tests/test_consumer_mixin.py
  edi_oca/tests/test_record.py
  edi_oca/tests/test_security.py
Labels: bot is merging ⏳

#676 [15.0][MIG] edi_voxel_oca: Migration to version 15.0
  edi_voxel_oca/README.rst
  edi_voxel_oca/__init__.py
  edi_voxel_oca/__manifest__.py
  edi_voxel_oca/data/data_voxel_uom.xml
  edi_voxel_oca/i18n/edi_voxel.pot
  edi_voxel_oca/i18n/edi_voxel_oca.pot
  edi_voxel_oca/i18n/es.po
  edi_voxel_oca/models/__init__.py
  edi_voxel_oca/models/account.py
  edi_voxel_oca/models/queue_job.py
  edi_voxel_oca/models/res_company.py
  edi_voxel_oca/models/res_config_settings.py
  edi_voxel_oca/models/res_partner.py
  edi_voxel_oca/models/uom_uom.py
  edi_voxel_oca/models/voxel_login.py
  edi_voxel_oca/models/voxel_mixin.py
  edi_voxel_oca/readme/CONTRIBUTORS.rst
  edi_voxel_oca/readme/DESCRIPTION.rst
  edi_voxel_oca/security/ir.model.access.csv
  edi_voxel_oca/security/voxel_security.xml
  edi_voxel_oca/static/description/icon.png
  edi_voxel_oca/static/description/index.html
  edi_voxel_oca/views/account_tax_views.xml
  edi_voxel_oca/views/product_uom_views.xml
  edi_voxel_oca/views/res_company_view.xml
  edi_voxel_oca/views/res_config_settings_views.xml
  edi_voxel_oca/views/res_partner_views.xml
  edi_voxel_oca/views/template_voxel_report.xml
  edi_voxel_oca/views/voxel_login_views.xml
  setup/edi_voxel_oca/odoo/addons/edi_voxel_oca
  setup/edi_voxel_oca/setup.py
Labels: bot is merging ⏳

#695 [FIX] edi: output might be not UTF-8 encodable, like PDFs
  edi_oca/models/edi_backend.py
  edi_oca/tests/result.pdf
  edi_oca/tests/test_backend_output.py
Labels: approved, bot is merging ⏳

#662 [14.0] Add edi_party_data_oca
  edi_party_data_oca/README.rst
  edi_party_data_oca/__init__.py
  edi_party_data_oca/__manifest__.py
  edi_party_data_oca/components/__init__.py
  edi_party_data_oca/components/common.py
  edi_party_data_oca/components/party_data.py
  edi_party_data_oca/models/__init__.py
  edi_party_data_oca/models/edi_exchange_type.py
  edi_party_data_oca/readme/CONFIGURE.rst
  edi_party_data_oca/readme/CONTRIBUTORS.rst
  edi_party_data_oca/readme/DESCRIPTION.rst
  edi_party_data_oca/readme/USAGE.rst
  edi_party_data_oca/tests/__init__.py
  edi_party_data_oca/tests/test_party_data.py
  edi_party_data_oca/utils.py
  edi_party_data_oca/views/edi_exchange_type_views.xml
  setup/edi_party_data_oca/odoo/addons/edi_party_data_oca
  setup/edi_party_data_oca/setup.py
Labels: bot is merging ⏳

#613 [14.0][IMP] base_ebill_payment_contract: find contracts for partner
  base_ebill_payment_contract/__manifest__.py
  base_ebill_payment_contract/demo/ebill_payment_contract.xml
  base_ebill_payment_contract/models/res_partner.py
  base_ebill_payment_contract/tests/test_base_ebill_payment_contract.py
Labels: bot is merging ⏳

#692 [14.0][IMP] product_import: handle company and active flag
  product_import/__init__.py
  product_import/models/__init__.py
  product_import/tests/common.py
  product_import/tests/test_parse_validate.py
  product_import/tests/test_product_import.py
  product_import/wizard/product_import.py
Labels: bot is merging ⏳

#696 [14.0][ADD] edi_exchange_template_party_data + misc improvements
  edi_exchange_template_oca/__manifest__.py
  edi_exchange_template_oca/models/edi_exchange_template_mixin.py
  edi_exchange_template_oca/models/edi_exchange_template_output.py
  edi_exchange_template_party_data/README.rst
  edi_exchange_template_party_data/__init__.py
  edi_exchange_template_party_data/__manifest__.py
  edi_exchange_template_party_data/models/__init__.py
  edi_exchange_template_party_data/models/edi_exchange_template_output.py
  edi_exchange_template_party_data/readme/CONTRIBUTORS.rst
  edi_exchange_template_party_data/readme/DESCRIPTION.rst
  edi_exchange_template_party_data/tests/__init__.py
  edi_exchange_template_party_data/tests/test_output_tmpl.py
  setup/edi_exchange_template_party_data/odoo/addons/edi_exchange_template_party_data
  setup/edi_exchange_template_party_data/setup.py
Labels: bot is merging ⏳

#697 [14.0] edi_party_data: use display_name by default
  edi_party_data_oca/components/common.py
  edi_party_data_oca/readme/CONFIGURE.rst
  edi_party_data_oca/tests/test_party_data.py
Labels: approved, bot is merging ⏳

#677 [15.0][MIG] edi_voxel_account_invoice_oca: Migration to version 15.0
  edi_voxel_account_invoice_oca/README.rst
  edi_voxel_account_invoice_oca/__init__.py
  edi_voxel_account_invoice_oca/__manifest__.py
  edi_voxel_account_invoice_oca/data/ir_cron_data.xml
  edi_voxel_account_invoice_oca/i18n/edi_voxel_account_invoice_oca.pot
  edi_voxel_account_invoice_oca/i18n/es.po
  edi_voxel_account_invoice_oca/models/__init__.py
  edi_voxel_account_invoice_oca/models/account_move.py
  edi_voxel_account_invoice_oca/models/res_company.py
  edi_voxel_account_invoice_oca/models/res_config_settings.py
  edi_voxel_account_invoice_oca/readme/CONFIGURE.rst
  edi_voxel_account_invoice_oca/readme/CONTRIBUTORS.rst
  edi_voxel_account_invoice_oca/readme/DESCRIPTION.rst
  edi_voxel_account_invoice_oca/readme/USAGE.rst
  edi_voxel_account_invoice_oca/reports/__init__.py
  edi_voxel_account_invoice_oca/reports/report_voxel_invoice.py
  edi_voxel_account_invoice_oca/static/description/icon.png
  edi_voxel_account_invoice_oca/static/description/index.html
  edi_voxel_account_invoice_oca/tests/__init__.py
  edi_voxel_account_invoice_oca/tests/test_voxel_account_invoice.py
  edi_voxel_account_invoice_oca/views/account_move_views.xml
  edi_voxel_account_invoice_oca/views/report_voxel_invoice.xml
  edi_voxel_account_invoice_oca/views/res_company_view.xml
  edi_voxel_account_invoice_oca/views/res_config_settings_views.xml
  setup/edi_voxel_account_invoice_oca/odoo/addons/edi_voxel_account_invoice_oca
  setup/edi_voxel_account_invoice_oca/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#700 [13.0][IMP] edi_backend_partner: modify backend view
  edi_backend_partner/views/edi_backend_views.xml
Labels: approved, ready to merge, bot is merging ⏳
