Repository OCA/edi, pull requests merged in 2023-08, with the labels that each got.

#794 [16.0] FIX #104 UBL: use address of partner, not of commercial_parter
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#778 [14.0] edi: add disable flag in core mixin + exc type partner config
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/views/edi_exchange_type_views.xml
Labels: bot is merging ⏳

#804 [13.0][FIX] edi_voxel_sale_order_import: Propagate onchange updates
  edi_voxel_sale_order_import/models/sale_order.py
Labels: approved, bot is merging ⏳

#770 [14.0][ADD] account_invoice_download_scaleway
  account_invoice_download_scaleway/README.rst
  account_invoice_download_scaleway/__init__.py
  account_invoice_download_scaleway/__manifest__.py
  account_invoice_download_scaleway/demo/scaleway.xml
  account_invoice_download_scaleway/models/__init__.py
  account_invoice_download_scaleway/models/account_invoice_download_config.py
  account_invoice_download_scaleway/readme/CONFIGURE.rst
  account_invoice_download_scaleway/readme/CONTRIBUTORS.rst
  account_invoice_download_scaleway/readme/DESCRIPTION.rst
  account_invoice_download_scaleway/readme/USAGE.rst
  account_invoice_download_scaleway/views/account_invoice_download_config.xml
  setup/account_invoice_download_scaleway/odoo/addons/account_invoice_download_scaleway
  setup/account_invoice_download_scaleway/setup.py
Labels: bot is merging ⏳

#790 [14.0] edi_oca: fix count EDI exhange record using consume mixin
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/tests/test_consumer_mixin.py
Labels: approved, ready to merge, bot is merging ⏳
