Repository OCA/edi, pull requests merged in 2023-10, with the labels that each got.

#824 [14.0] edi: fix handling of archived types and rules
  edi_oca/models/edi_exchange_type.py
  edi_oca/tests/test_exchange_type.py
  edi_oca/views/edi_exchange_type_views.xml
Labels: bot is merging ⏳

#793 [15.0] FIX #104 UBL: use address of partner, not of commercial_parter
  base_ubl/models/ubl.py
Labels: approved, bot is merging ⏳

#828 [14.0] account_invoice_import: start OCA wizard when user click on "Upload" in supplier invoice tree view
  account_invoice_import/models/__init__.py
  account_invoice_import/models/account_journal.py
Labels: approved, bot is merging ⏳

#813 [16.0][MIG] base_edifact: Migration to 16.0
  base_edifact/README.rst
  base_edifact/__init__.py
  base_edifact/__manifest__.py
  base_edifact/models/__init__.py
  base_edifact/models/edifact.py
  base_edifact/readme/CONFIGURE.rst
  base_edifact/readme/CONTRIBUTORS.rst
  base_edifact/readme/DESCRIPTION.rst
  base_edifact/readme/HISTORY.rst
  base_edifact/readme/INSTALL.rst
  base_edifact/readme/USAGE.rst
  base_edifact/static/description/icon.png
  base_edifact/static/description/icon.svg
  base_edifact/static/description/index.html
  base_edifact/tests/__init__.py
  base_edifact/tests/files/Retail_EDIFACT_ORDERS_sample1.txt
  base_edifact/tests/files/Retail_EDIFACT_ORDERS_sample2.txt
  base_edifact/tests/test_base_edifact.py
  requirements.txt
  setup/base_edifact/odoo/addons/base_edifact
  setup/base_edifact/setup.py
Labels: bot is merging ⏳

#834 [15.0][IMP] edi: test performance improvement
  edi_voxel_account_invoice_oca/tests/test_voxel_account_invoice.py
  edi_voxel_stock_picking_oca/tests/test_voxel_stock_picking.py
Labels: bot is merging ⏳

#816 [16.0][MIG] sale_order_import: Migration to 16.0
  sale_order_import/README.rst
  sale_order_import/__init__.py
  sale_order_import/__manifest__.py
  sale_order_import/i18n/es.po
  sale_order_import/i18n/fr.po
  sale_order_import/i18n/sale_order_import.pot
  sale_order_import/models/__init__.py
  sale_order_import/models/sale.py
  sale_order_import/readme/CONTRIBUTORS.rst
  sale_order_import/readme/CREDITS.rst
  sale_order_import/readme/DESCRIPTION.rst
  sale_order_import/readme/USAGE.rst
  sale_order_import/security/ir.model.access.csv
  sale_order_import/static/description/icon.png
  sale_order_import/static/description/index.html
  sale_order_import/tests/__init__.py
  sale_order_import/tests/common.py
  sale_order_import/tests/fixtures/test.pdf
  sale_order_import/tests/test_order_import.py
  sale_order_import/tests/test_parse_validate.py
  sale_order_import/tests/test_sale_order.py
  sale_order_import/wizard/__init__.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_import/wizard/sale_order_import_view.xml
  setup/sale_order_import/odoo/addons/sale_order_import
  setup/sale_order_import/setup.py
Labels: approved, bot is merging ⏳

#838 [16.0][FIX] account_invoice_facturx: crash on HS code
  account_invoice_facturx/models/account_move.py
Labels: bot is merging ⏳

#837 [14.0][FIX] sale_order_ubl: fix crash when closing POS session
  sale_order_ubl/models/report.py
Labels: bot is merging ⏳

#707 [16.0][MIG] account_invoice_facturx_py3o
  account_invoice_facturx_py3o/README.rst
  account_invoice_facturx_py3o/__init__.py
  account_invoice_facturx_py3o/__manifest__.py
  account_invoice_facturx_py3o/i18n/account_invoice_factur-x_py3o.pot
  account_invoice_facturx_py3o/i18n/account_invoice_facturx_py3o.pot
  account_invoice_facturx_py3o/i18n/de.po
  account_invoice_facturx_py3o/i18n/es.po
  account_invoice_facturx_py3o/models/__init__.py
  account_invoice_facturx_py3o/models/py3o_report.py
  account_invoice_facturx_py3o/readme/CONTRIBUTORS.rst
  account_invoice_facturx_py3o/readme/DESCRIPTION.rst
  account_invoice_facturx_py3o/static/description/icon.png
  account_invoice_facturx_py3o/static/description/index.html
  setup/account_invoice_facturx_py3o/odoo/addons/account_invoice_facturx_py3o
  setup/account_invoice_facturx_py3o/setup.py
Labels: bot is merging ⏳, no stale

#836 [14.0] account_invoice_import_simple_pdf: works with newer PyMuPDF versions & add pypdf backend
  account_invoice_import_simple_pdf/__manifest__.py
  account_invoice_import_simple_pdf/readme/CONFIGURE.rst
  account_invoice_import_simple_pdf/readme/INSTALL.rst
  account_invoice_import_simple_pdf/tests/pdf/akretion_france-test.pdf
  account_invoice_import_simple_pdf/tests/test_invoice_import.py
  account_invoice_import_simple_pdf/wizard/account_invoice_import.py
  requirements.txt
Labels: bot is merging ⏳

#839 [16.0][IMP] sale_order_import: Add confirm_order flag to wizard
  sale_order_import/tests/test_order_import.py
  sale_order_import/wizard/sale_order_import.py
Labels: bot is merging ⏳

#835 [16.0][IMP] base_edifact: Support more EDIFACT format
  base_edifact/models/edifact.py
  base_edifact/tests/files/test_orders_-_no_PRI_segments.txt
  base_edifact/tests/files/test_orders_-_no_ean_in_LIN_segments.txt
  base_edifact/tests/test_base_edifact.py
Labels: bot is merging ⏳

#841 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_invoice_download/i18n/account_invoice_download.pot
  account_invoice_download/views/account_invoice_download_config.xml
  account_invoice_download/views/account_invoice_download_log.xml
  account_invoice_download_ovh/demo/ovh_demo.xml
  account_invoice_export/data/mail_activity_type.xml
  account_invoice_export/data/queue_job_data.xml
  account_invoice_import/i18n/account_invoice_import.pot
  account_invoice_import/views/account_invoice_import_config.xml
  base_business_document_import/i18n/cs_CZ.po
  edi_exchange_template_oca/i18n/edi_exchange_template_oca.pot
  edi_exchange_template_oca/views/edi_exchange_template_output_views.xml
  edi_oca/i18n/edi_oca.pot
  edi_oca/views/edi_backend_type_views.xml
  edi_oca/views/edi_exchange_record_views.xml
  edi_oca/views/edi_exchange_type_views.xml
Labels: help wanted, needs review, bot is merging ⏳

#826 [14.0][IMP] base_business_document_import: add support for price with tax i…
  base_business_document_import/models/business_document_import.py
Labels: approved, bot is merging ⏳

#743 [16.0][MIG] base_business_document_import_phone
  base_business_document_import_phone/README.rst
  base_business_document_import_phone/__init__.py
  base_business_document_import_phone/__manifest__.py
  base_business_document_import_phone/i18n/base_business_document_import_phone.pot
  base_business_document_import_phone/i18n/de.po
  base_business_document_import_phone/i18n/hr.po
  base_business_document_import_phone/models/__init__.py
  base_business_document_import_phone/models/business_document_import.py
  base_business_document_import_phone/readme/CONTRIBUTORS.rst
  base_business_document_import_phone/readme/DESCRIPTION.rst
  base_business_document_import_phone/readme/INSTALL.rst
  base_business_document_import_phone/static/description/icon.png
  base_business_document_import_phone/static/description/index.html
  base_business_document_import_phone/tests/__init__.py
  base_business_document_import_phone/tests/test_phone_partner_match.py
  requirements.txt
  setup/base_business_document_import_phone/odoo/addons/base_business_document_import_phone
  setup/base_business_document_import_phone/setup.py
Labels: bot is merging ⏳, no stale
