Repository OCA/edi, pull requests merged in 2023-11, with the labels that each got.

#827 [14.0][IMP] account_invoice_import: fwd ports for ATI Support (tests)
  account_invoice_import/tests/test_invoice_import.py
Labels: approved, ready to merge, bot is merging ⏳

#573 [14.0][IMP][FIX] account_invoice_import_invoice2data add line support and additional partner fields
  account_invoice_import_invoice2data/__manifest__.py
  account_invoice_import_invoice2data/demo/demo_data.xml
  account_invoice_import_invoice2data/readme/CONFIGURE.rst
  account_invoice_import_invoice2data/readme/DESCRIPTION.rst
  account_invoice_import_invoice2data/readme/HISTORY.rst
  account_invoice_import_invoice2data/readme/INSTALL.rst
  account_invoice_import_invoice2data/readme/ROADMAP.rst
  account_invoice_import_invoice2data/tests/pdf/AzureInterior.pdf
  account_invoice_import_invoice2data/tests/test_invoice_import.py
  account_invoice_import_invoice2data/wizard/account_invoice_import.py
Labels: approved, ready to merge, bot is merging ⏳

#807 [FIX] base_business_document_import: fixed typo in _match_tax method
  base_business_document_import/models/business_document_import.py
Labels: approved, ready to merge, bot is merging ⏳

#843 [15.0][FIX] edi_oca: avoid flooding error in the record chatter (forward port)
  edi_oca/models/edi_backend.py
Labels: approved, bot is merging ⏳

#833 [14.0] account_invoice_import_invoice2data: support for lines with taxes included
  account_invoice_import_invoice2data/readme/CONFIGURE.rst
  account_invoice_import_invoice2data/readme/ROADMAP.rst
  account_invoice_import_invoice2data/tests/test_invoice_import.py
  account_invoice_import_invoice2data/wizard/account_invoice_import.py
Labels: bot is merging ⏳

#821 [16.0][MIG] sale_order_import_edifact: Migration to 16.0
  sale_order_import_edifact/README.rst
  sale_order_import_edifact/__init__.py
  sale_order_import_edifact/__manifest__.py
  sale_order_import_edifact/demo/demo_data.xml
  sale_order_import_edifact/models/__init__.py
  sale_order_import_edifact/models/business_document_import.py
  sale_order_import_edifact/readme/CONFIGURE.rst
  sale_order_import_edifact/readme/CONTRIBUTORS.rst
  sale_order_import_edifact/readme/CREDITS.rst
  sale_order_import_edifact/readme/DESCRIPTION.rst
  sale_order_import_edifact/readme/HISTORY.rst
  sale_order_import_edifact/readme/ROADMAP.rst
  sale_order_import_edifact/static/description/icon.png
  sale_order_import_edifact/static/description/icon.svg
  sale_order_import_edifact/static/description/index.html
  sale_order_import_edifact/tests/__init__.py
  sale_order_import_edifact/tests/common.py
  sale_order_import_edifact/tests/test_edifact_order_import.py
  sale_order_import_edifact/wizard/__init__.py
  sale_order_import_edifact/wizard/sale_order_import.py
  sale_order_import_edifact/wizard/sale_order_import_view.xml
  setup/sale_order_import_edifact/odoo/addons/sale_order_import_edifact
  setup/sale_order_import_edifact/setup.py
Labels: bot is merging ⏳

#852 [IMP] edi_oca: Show traceback on exception errors
  edi_oca/models/edi_backend.py
  edi_oca/tests/test_backend_output.py
  edi_oca/tests/test_backend_process.py
  edi_oca/tests/test_backend_validate.py
Labels: approved, ready to merge, bot is merging ⏳

#865 [14.0] account_invoice_ubl*: fix tests
  account_invoice_ubl/tests/common.py
  account_invoice_ubl/tests/test_ubl_generate.py
  account_invoice_ubl_peppol/tests/test_ubl_email_attachment.py
Labels: bot is merging ⏳

#868 [15.0][PORT][IMP] edi_oca: Show traceback on exception errors from 14.0
  edi_oca/models/edi_backend.py
  edi_oca/tests/test_backend_output.py
  edi_oca/tests/test_backend_process.py
  edi_oca/tests/test_backend_validate.py
Labels: bot is merging ⏳

#844 [16.0][IMP] sale_order_import: Improve sale_order_import to warn user…
  sale_order_import/tests/test_order_import.py
  sale_order_import/wizard/sale_order_import.py
Labels: approved, ready to merge, bot is merging ⏳

#855 [14.0] edi_oca: fix/imp jobs
  edi_exchange_template_oca/tests/test_edi_backend_output.py
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_backend_jobs.py
  edi_oca/tests/test_exchange_type.py
Labels: approved, ready to merge, bot is merging ⏳

#876 [15.0][FIX] edi_voxel_stock_picking_oca: Proper action_done method
  edi_voxel_stock_picking_oca/models/stock_picking.py
Labels: approved, bot is merging ⏳

#796 [14.0] edi: generate/send chain jobs + add identity exact match based on checksum
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_backend_output.py
  edi_oca/tests/test_record.py
  edi_oca/utils.py
  edi_oca/views/edi_exchange_record_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#880 [14.0] edi: fix consumer mixin copy origin exc record
  edi_oca/models/edi_exchange_consumer_mixin.py
Labels: approved, bot is merging ⏳
