Repository OCA/edi, pull requests merged in 2023-09, with the labels that each got.

#808 [14.0] edi_oca: avoid duplicate `Model` field name
  edi_oca/models/edi_exchange_type_rule.py
Labels: approved, bot is merging ⏳

#716 [FIX] remove pin version of dateparser
  account_invoice_import_invoice2data/__manifest__.py
  account_invoice_import_simple_pdf/__manifest__.py
  edi_pdf2data_oca/__manifest__.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#768 [14.0] base_business_document_import: Fix company domain
  base_business_document_import/models/business_document_import.py
Labels: approved, ready to merge, bot is merging ⏳

#811 [15.0] Fix build
  edi_webservice_oca/tests/test_edi_webservice.py
  pdf_helper/tests/test_helper.py
Labels: bot is merging ⏳

#819 [FIX] edi_oca: Adapt tests to changes on error messages
  edi_oca/tests/test_security.py
  edi_oca/views/edi_backend_views.xml
Labels: bot is merging ⏳

#792 [14.0][PORT] 323 from 13.0
  account_invoice_ubl/models/account_move.py
  base_ubl/models/ubl.py
  sale_order_ubl/models/sale.py
Labels: approved, bot is merging ⏳

#795 [14.0][MIG] account_invoice_ubl_peppol
  account_invoice_ubl_peppol/README.rst
  account_invoice_ubl_peppol/__init__.py
  account_invoice_ubl_peppol/__manifest__.py
  account_invoice_ubl_peppol/data/peppol.eas.list.csv
  account_invoice_ubl_peppol/i18n/account_invoice_ubl_email_attachment.pot
  account_invoice_ubl_peppol/i18n/account_invoice_ubl_peppol.pot
  account_invoice_ubl_peppol/i18n/de.po
  account_invoice_ubl_peppol/i18n/hr.po
  account_invoice_ubl_peppol/i18n/nl.po
  account_invoice_ubl_peppol/models/__init__.py
  account_invoice_ubl_peppol/models/account_move.py
  account_invoice_ubl_peppol/models/peppol_eas_list.py
  account_invoice_ubl_peppol/models/res_company.py
  account_invoice_ubl_peppol/models/res_config_settings.py
  account_invoice_ubl_peppol/models/res_country.py
  account_invoice_ubl_peppol/models/res_partner.py
  account_invoice_ubl_peppol/readme/CONFIGURE.rst
  account_invoice_ubl_peppol/readme/CONTRIBUTORS.rst
  account_invoice_ubl_peppol/readme/DESCRIPTION.rst
  account_invoice_ubl_peppol/readme/ROADMAP.rst
  account_invoice_ubl_peppol/readme/USAGE.rst
  account_invoice_ubl_peppol/security/ir.model.access.csv
  account_invoice_ubl_peppol/static/description/icon.png
  account_invoice_ubl_peppol/static/description/index.html
  account_invoice_ubl_peppol/tests/__init__.py
  account_invoice_ubl_peppol/tests/test_ubl_email_attachment.py
  account_invoice_ubl_peppol/views/peppol_eas_list.xml
  account_invoice_ubl_peppol/views/res_config_settings.xml
  account_invoice_ubl_peppol/views/res_country.xml
  setup/account_invoice_ubl_peppol/odoo/addons/account_invoice_ubl_peppol
  setup/account_invoice_ubl_peppol/setup.py
Labels: bot is merging ⏳
