Repository OCA/edi, pull requests merged in 2023-12, with the labels that each got.

#883 [14.0] account_invoice_*: fix tests import
  account_invoice_facturx/tests/test_facturx_invoice.py
  account_invoice_import_invoice2data/tests/test_invoice_import.py
Labels: bot is merging ⏳

#881 [14.0][IMP] product_import: always create product Active
  product_import/tests/test_product_import.py
  product_import/wizard/product_import.py
Labels: approved, bot is merging ⏳

#884 [16.0][FIX] base_business_document_import tests
  base_business_document_import/tests/test_business_document_import.py
Labels: approved, ready to merge, bot is merging ⏳

#879 [16.0][MIG] despatch_advice_import
  despatch_advice_import/README.rst
  despatch_advice_import/__init__.py
  despatch_advice_import/__manifest__.py
  despatch_advice_import/readme/CONTRIBUTORS.rst
  despatch_advice_import/readme/CREDITS.rst
  despatch_advice_import/readme/DESCRIPTION.rst
  despatch_advice_import/security/ir.model.access.csv
  despatch_advice_import/static/description/icon.png
  despatch_advice_import/static/description/index.html
  despatch_advice_import/tests/__init__.py
  despatch_advice_import/tests/test_despatch_advice_import.py
  despatch_advice_import/wizard/__init__.py
  despatch_advice_import/wizard/despatch_advice_import.py
  despatch_advice_import/wizard/despatch_advice_import.xml
  setup/despatch_advice_import/odoo/addons/despatch_advice_import
  setup/despatch_advice_import/setup.py
Labels: bot is merging ⏳

#878 [16.0][MIG] despatch_advice_import_ubl
  despatch_advice_import_ubl/README.rst
  despatch_advice_import_ubl/__init__.py
  despatch_advice_import_ubl/__manifest__.py
  despatch_advice_import_ubl/readme/CONTRIBUTORS.rst
  despatch_advice_import_ubl/readme/CREDITS.rst
  despatch_advice_import_ubl/readme/DESCRIPTION.rst
  despatch_advice_import_ubl/static/description/icon.png
  despatch_advice_import_ubl/static/description/index.html
  despatch_advice_import_ubl/tests/__init__.py
  despatch_advice_import_ubl/tests/files/despatch_advice_2.xml
  despatch_advice_import_ubl/tests/files/despatch_advice_tmpl.xml
  despatch_advice_import_ubl/tests/files/do_mix1.xml
  despatch_advice_import_ubl/tests/files/do_mix2.xml
  despatch_advice_import_ubl/tests/test_despatch_advice_import.py
  despatch_advice_import_ubl/tests/test_despatch_advice_mix.py
  despatch_advice_import_ubl/wizard/__init__.py
  despatch_advice_import_ubl/wizard/despatch_advice_import.py
  setup/despatch_advice_import_ubl/odoo/addons/despatch_advice_import_ubl
  setup/despatch_advice_import_ubl/setup.py
Labels: bot is merging ⏳

#895 [15.0][FIX] edi_oca: avoid pre-migrate error
  edi_oca/migrations/15.0.1.6.0/pre-migrate.py
Labels: approved, bot is merging ⏳

#897 [14.0][FIX] edi_oca: avoid pre-migrate error
  edi_oca/migrations/14.0.1.20.0/pre-migrate.py
Labels: approved, bot is merging ⏳

#894 [17.0][MIG] base_edi: Migration to 17.0
  base_edi/README.rst
  base_edi/__init__.py
  base_edi/__manifest__.py
  base_edi/data/module_category.xml
  base_edi/i18n/base_edi.pot
  base_edi/i18n/es.po
  base_edi/i18n/fr.po
  base_edi/i18n/hr.po
  base_edi/i18n/nl.po
  base_edi/pyproject.toml
  base_edi/readme/CONTRIBUTORS.md
  base_edi/readme/DESCRIPTION.md
  base_edi/readme/ROADMAP.md
  base_edi/security/edi_groups.xml
  base_edi/static/description/icon.png
  base_edi/static/description/icon.svg
  base_edi/static/description/index.html
  base_edi/views/edi_menu.xml
Labels: bot is merging ⏳

#809 [FIX] edi_webservice_oca: add internal user webservice backend read a…
  edi_webservice_oca/models/edi_backend.py
  edi_webservice_oca/tests/test_send.py
Labels: approved, ready to merge, bot is merging ⏳
