Repository OCA/edi, pull requests merged in 2023-03, with the labels that each got.

#732 [14.0] Update pre-commit conf
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: needs review

#723 [16.0][MIG] pdf_helper
  pdf_helper/README.rst
  pdf_helper/__init__.py
  pdf_helper/__manifest__.py
  pdf_helper/i18n/pdf_helper.pot
  pdf_helper/models/__init__.py
  pdf_helper/models/helper.py
  pdf_helper/readme/CONTRIBUTORS.rst
  pdf_helper/readme/DESCRIPTION.rst
  pdf_helper/readme/USAGE.rst
  pdf_helper/static/description/icon.png
  pdf_helper/static/description/index.html
  pdf_helper/tests/__init__.py
  pdf_helper/tests/fixtures/pdf_with_xml_test.pdf
  pdf_helper/tests/test_helper.py
  pdf_helper/utils.py
  setup/pdf_helper/odoo/addons/pdf_helper
  setup/pdf_helper/setup.py
Labels: bot is merging ⏳

#681 [15.0][MIG] edi_voxel_stock_picking > edi_voxel_stock_picking_oca: Migration to version 15.0
  edi_voxel_stock_picking_oca/README.rst
  edi_voxel_stock_picking_oca/__init__.py
  edi_voxel_stock_picking_oca/__manifest__.py
  edi_voxel_stock_picking_oca/data/ir_cron_data.xml
  edi_voxel_stock_picking_oca/i18n/edi_voxel_stock_picking_oca.pot
  edi_voxel_stock_picking_oca/i18n/es.po
  edi_voxel_stock_picking_oca/models/__init__.py
  edi_voxel_stock_picking_oca/models/res_company.py
  edi_voxel_stock_picking_oca/models/res_config_settings.py
  edi_voxel_stock_picking_oca/models/stock_picking.py
  edi_voxel_stock_picking_oca/readme/CONFIGURE.rst
  edi_voxel_stock_picking_oca/readme/CONTRIBUTORS.rst
  edi_voxel_stock_picking_oca/readme/DESCRIPTION.rst
  edi_voxel_stock_picking_oca/readme/USAGE.rst
  edi_voxel_stock_picking_oca/reports/__init__.py
  edi_voxel_stock_picking_oca/reports/report_voxel_picking.py
  edi_voxel_stock_picking_oca/static/description/icon.png
  edi_voxel_stock_picking_oca/static/description/index.html
  edi_voxel_stock_picking_oca/tests/__init__.py
  edi_voxel_stock_picking_oca/tests/test_voxel_stock_picking.py
  edi_voxel_stock_picking_oca/views/report_voxel_picking.xml
  edi_voxel_stock_picking_oca/views/res_company_view.xml
  edi_voxel_stock_picking_oca/views/res_config_settings_views.xml
  edi_voxel_stock_picking_oca/views/stock_picking_views.xml
  setup/edi_voxel_stock_picking_oca/odoo/addons/edi_voxel_stock_picking_oca
  setup/edi_voxel_stock_picking_oca/setup.py
Labels: approved, bot is merging ⏳

#679 [15.0][MIG] edi_voxel_secondary_unit > edi_voxel_secondary_unit_oca: Migration to version 15.0
  edi_voxel_secondary_unit_oca/README.rst
  edi_voxel_secondary_unit_oca/__init__.py
  edi_voxel_secondary_unit_oca/__manifest__.py
  edi_voxel_secondary_unit_oca/i18n/edi_voxel_secondary_unit.pot
  edi_voxel_secondary_unit_oca/i18n/es.po
  edi_voxel_secondary_unit_oca/models/__init__.py
  edi_voxel_secondary_unit_oca/models/product_secondary_unit.py
  edi_voxel_secondary_unit_oca/readme/CONTRIBUTORS.rst
  edi_voxel_secondary_unit_oca/readme/DESCRIPTION.rst
  edi_voxel_secondary_unit_oca/readme/USAGE.rst
  edi_voxel_secondary_unit_oca/static/description/icon.png
  edi_voxel_secondary_unit_oca/static/description/index.html
  edi_voxel_secondary_unit_oca/views/product_secondary_unit_views.xml
  setup/edi_voxel_secondary_unit_oca/odoo/addons/edi_voxel_secondary_unit_oca
  setup/edi_voxel_secondary_unit_oca/setup.py
Labels: bot is merging ⏳

#682 [15.0][MIG] edi_voxel_stock_picking_secondary_unit: Migration to version 15.0
  edi_voxel_stock_picking_secondary_unit_oca/README.rst
  edi_voxel_stock_picking_secondary_unit_oca/__init__.py
  edi_voxel_stock_picking_secondary_unit_oca/__manifest__.py
  edi_voxel_stock_picking_secondary_unit_oca/i18n/edi_voxel_stock_picking_secondary_unit_oca.pot
  edi_voxel_stock_picking_secondary_unit_oca/readme/CONTRIBUTORS.rst
  edi_voxel_stock_picking_secondary_unit_oca/readme/DESCRIPTION.rst
  edi_voxel_stock_picking_secondary_unit_oca/readme/USAGE.rst
  edi_voxel_stock_picking_secondary_unit_oca/reports/__init__.py
  edi_voxel_stock_picking_secondary_unit_oca/reports/report_voxel_picking.py
  edi_voxel_stock_picking_secondary_unit_oca/static/description/icon.png
  edi_voxel_stock_picking_secondary_unit_oca/static/description/index.html
  edi_voxel_stock_picking_secondary_unit_oca/tests/__init__.py
  edi_voxel_stock_picking_secondary_unit_oca/tests/test_voxel_stock_picking_secondary_unit.py
  setup/edi_voxel_stock_picking_secondary_unit_oca/odoo/addons/edi_voxel_stock_picking_secondary_unit_oca
  setup/edi_voxel_stock_picking_secondary_unit_oca/setup.py
Labels: approved, bot is merging ⏳, stale

#704 [16.0][MIG] account_einvoice_generate
  account_einvoice_generate/README.rst
  account_einvoice_generate/__init__.py
  account_einvoice_generate/__manifest__.py
  account_einvoice_generate/i18n/account_e-invoice_generate.pot
  account_einvoice_generate/i18n/account_einvoice_generate.pot
  account_einvoice_generate/i18n/hr.po
  account_einvoice_generate/models/__init__.py
  account_einvoice_generate/models/account_move.py
  account_einvoice_generate/models/res_company.py
  account_einvoice_generate/readme/CONFIGURE.rst
  account_einvoice_generate/readme/CONTRIBUTORS.rst
  account_einvoice_generate/readme/DESCRIPTION.rst
  account_einvoice_generate/readme/INSTALL.rst
  account_einvoice_generate/static/description/icon.png
  account_einvoice_generate/static/description/index.html
  account_einvoice_generate/tests/__init__.py
  account_einvoice_generate/tests/test_einvoice_generate.py
  account_einvoice_generate/views/res_config_settings.xml
  account_einvoice_generate/wizards/__init__.py
  account_einvoice_generate/wizards/res_config_settings.py
  setup/account_einvoice_generate/odoo/addons/account_einvoice_generate
  setup/account_einvoice_generate/setup.py
Labels: bot is merging ⏳

#734 business_document_import: Improve vat match
  base_business_document_import/models/business_document_import.py
Labels: approved, ready to merge, bot is merging ⏳

#733 account_invoice_import: FIX Partner creation ref + Improve comments
  account_invoice_import/wizard/account_invoice_import.py
Labels: approved, ready to merge, merged 🎉

#738 [14.0][FIX] account_invoice_import: fix crash due to missing method
  account_invoice_import/wizard/account_invoice_import.py
Labels: approved, bot is merging ⏳
