Repository OCA/edi, pull requests merged in 2023-02, with the labels that each got.

#718 [16.0] Update pre-commit conf
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: needs review

#646 [15.0][FWD] edi_oca: port changes from 14.0
  edi_endpoint_oca/models/edi_backend.py
  edi_oca/__manifest__.py
  edi_oca/components/base.py
  edi_oca/migrations/15.0.1.4.0/post-migrate.py
  edi_oca/models/__init__.py
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/models/edi_id_mixin.py
  edi_oca/static/src/js/widget_edi.js
  edi_oca/static/src/xml/widget_edi.xml
  edi_oca/templates/exchange_chatter_msg.xml
  edi_oca/templates/exchange_mixin_buttons.xml
  edi_oca/tests/test_backend_input.py
  edi_oca/tests/test_backend_process.py
  edi_oca/tests/test_consumer_mixin.py
  edi_oca/tests/test_edi_backend_cron.py
  edi_oca/tests/test_record.py
  edi_oca/tests/test_security.py
  edi_oca/views/edi_backend_views.xml
  edi_oca/views/edi_exchange_type_views.xml
  edi_oca/wizards/edi_exchange_record_create_wiz.py
Labels: bot is merging ⏳

#719 [14.0] Update pre-commit conf
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
Labels: needs review

#721 [IMP] edi_storage_oca: Delete processed files if you want it
  edi_storage_oca/components/listener.py
  edi_storage_oca/models/edi_backend.py
  edi_storage_oca/tests/test_edi_storage_listener.py
  edi_storage_oca/views/edi_backend_views.xml
Labels: bot is merging ⏳

#726 [14.0][IMP] product_import_ubl: select vendor by reference
  product_import_ubl/tests/files/UBL-Catalogue_Example2.xml
  product_import_ubl/tests/test_ubl_catalogue_import.py
  product_import_ubl/wizard/product_import.py
Labels: approved, bot is merging ⏳

#323 [13.0][ADD] account_invoice_ubl_peppol
  account_invoice_ubl/models/account_move.py
  account_invoice_ubl_peppol/README.rst
  account_invoice_ubl_peppol/__init__.py
  account_invoice_ubl_peppol/__manifest__.py
  account_invoice_ubl_peppol/data/peppol.eas.list.csv
  account_invoice_ubl_peppol/i18n/account_invoice_ubl_email_attachment.pot
  account_invoice_ubl_peppol/i18n/de.po
  account_invoice_ubl_peppol/i18n/hr.po
  account_invoice_ubl_peppol/i18n/nl.po
  account_invoice_ubl_peppol/models/__init__.py
  account_invoice_ubl_peppol/models/account_move.py
  account_invoice_ubl_peppol/models/peppol_eas_list.py
  account_invoice_ubl_peppol/models/res_company.py
  account_invoice_ubl_peppol/models/res_config_settings.py
  account_invoice_ubl_peppol/models/res_country.py
  account_invoice_ubl_peppol/models/res_partner.py
  account_invoice_ubl_peppol/readme/CONFIGURE.rst
  account_invoice_ubl_peppol/readme/CONTRIBUTORS.rst
  account_invoice_ubl_peppol/readme/DESCRIPTION.rst
  account_invoice_ubl_peppol/readme/ROADMAP.rst
  account_invoice_ubl_peppol/readme/USAGE.rst
  account_invoice_ubl_peppol/security/ir.model.access.csv
  account_invoice_ubl_peppol/static/description/icon.png
  account_invoice_ubl_peppol/static/description/index.html
  account_invoice_ubl_peppol/tests/__init__.py
  account_invoice_ubl_peppol/tests/test_ubl_email_attachment.py
  account_invoice_ubl_peppol/views/peppol_eas_list.xml
  account_invoice_ubl_peppol/views/res_config_settings.xml
  account_invoice_ubl_peppol/views/res_country.xml
  base_ubl/models/ubl.py
  sale_order_ubl/models/sale.py
  setup/account_invoice_ubl_peppol/odoo/addons/account_invoice_ubl_peppol
  setup/account_invoice_ubl_peppol/setup.py
Labels: approved, bot is merging ⏳

#722 [FIX] invoice2data: Fallback to tesseract
  account_invoice_import_invoice2data/wizard/account_invoice_import.py
Labels: approved, bot is merging ⏳

#631 [14.0] mig account_invoice ubl_email_attachment
  account_invoice_ubl_email_attachment/README.rst
  account_invoice_ubl_email_attachment/__init__.py
  account_invoice_ubl_email_attachment/__manifest__.py
  account_invoice_ubl_email_attachment/i18n/account_invoice_ubl_email_attachment.pot
  account_invoice_ubl_email_attachment/i18n/de.po
  account_invoice_ubl_email_attachment/i18n/hr.po
  account_invoice_ubl_email_attachment/i18n/nl.po
  account_invoice_ubl_email_attachment/models/__init__.py
  account_invoice_ubl_email_attachment/models/account_move.py
  account_invoice_ubl_email_attachment/models/mail_template.py
  account_invoice_ubl_email_attachment/models/res_company.py
  account_invoice_ubl_email_attachment/models/res_config_settings.py
  account_invoice_ubl_email_attachment/readme/CONFIGURE.rst
  account_invoice_ubl_email_attachment/readme/CONTRIBUTORS.rst
  account_invoice_ubl_email_attachment/readme/DESCRIPTION.rst
  account_invoice_ubl_email_attachment/readme/USAGE.rst
  account_invoice_ubl_email_attachment/static/description/icon.png
  account_invoice_ubl_email_attachment/static/description/index.html
  account_invoice_ubl_email_attachment/tests/__init__.py
  account_invoice_ubl_email_attachment/tests/test_ubl_email_attachment.py
  account_invoice_ubl_email_attachment/views/res_config_settings.xml
  setup/account_invoice_ubl_email_attachment/odoo/addons/account_invoice_ubl_email_attachment
  setup/account_invoice_ubl_email_attachment/setup.py
Labels: approved, ready to merge, bot is merging ⏳
