Repository OCA/edi, pull requests merged in 2023-05, with the labels that each got.

#757 [14.0][IMP] job identity key on acount_invoice_export
  account_invoice_export/models/account_move.py
Labels: bot is merging ⏳

#699 [14.0] Add sale_order_import_ubl_line_customer_ref
  sale_order_import_ubl_customer_free_ref/__manifest__.py
  sale_order_import_ubl_customer_free_ref/wizard/sale_order_import.py
  sale_order_import_ubl_line_customer_ref/README.rst
  sale_order_import_ubl_line_customer_ref/__init__.py
  sale_order_import_ubl_line_customer_ref/__manifest__.py
  sale_order_import_ubl_line_customer_ref/readme/CONTRIBUTORS.rst
  sale_order_import_ubl_line_customer_ref/readme/DESCRIPTION.rst
  sale_order_import_ubl_line_customer_ref/tests/__init__.py
  sale_order_import_ubl_line_customer_ref/tests/test_order_line_customer_ref.py
  sale_order_import_ubl_line_customer_ref/wizard/__init__.py
  sale_order_import_ubl_line_customer_ref/wizard/sale_order_import.py
  setup/sale_order_import_ubl_line_customer_ref/odoo/addons/sale_order_import_ubl_line_customer_ref
  setup/sale_order_import_ubl_line_customer_ref/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#762 [14.0] edi + edi_webservice: add 'as_bytes' option for binary files
  edi_oca/models/edi_exchange_record.py
  edi_webservice_oca/components/send.py
  edi_webservice_oca/readme/CONFIGURATION.rst
Labels: bot is merging ⏳

#765 [14.0] edi_oca: assertion was not executed
  edi_oca/tests/test_record.py
Labels: bot is merging ⏳

#764 [14.0] edi_oca: avoid backend mismatch
  edi_oca/models/edi_backend.py
  edi_oca/tests/test_exchange_type.py
  edi_oca/tests/test_record.py
Labels: bot is merging ⏳

#689 [MIG] edi_pdf2data_oca: Migration to 14.0
  edi_pdf2data_oca/README.rst
  edi_pdf2data_oca/__init__.py
  edi_pdf2data_oca/__manifest__.py
  edi_pdf2data_oca/components/__init__.py
  edi_pdf2data_oca/components/edi_input_pdf2data_process.py
  edi_pdf2data_oca/components/edi_process_data.py
  edi_pdf2data_oca/data/edi_data.xml
  edi_pdf2data_oca/models/__init__.py
  edi_pdf2data_oca/models/pdf2data_template.py
  edi_pdf2data_oca/readme/CONFIGURE.rst
  edi_pdf2data_oca/readme/CONTRIBUTORS.rst
  edi_pdf2data_oca/readme/DESCRIPTION.rst
  edi_pdf2data_oca/readme/USAGE.rst
  edi_pdf2data_oca/security/ir.model.access.csv
  edi_pdf2data_oca/static/description/icon.png
  edi_pdf2data_oca/static/description/index.html
  edi_pdf2data_oca/tests/AmazonWebServices.pdf
  edi_pdf2data_oca/tests/__init__.py
  edi_pdf2data_oca/tests/com.amazon.aws-exclude.yml
  edi_pdf2data_oca/tests/com.amazon.aws-include.yml
  edi_pdf2data_oca/tests/com.amazon.aws.yml
  edi_pdf2data_oca/tests/test_components.py
  edi_pdf2data_oca/tests/test_pdf2data.py
  edi_pdf2data_oca/views/pdf2data_template.xml
  edi_pdf2data_oca/wizard/__init__.py
  edi_pdf2data_oca/wizard/pdf2data_import.py
  edi_pdf2data_oca/wizard/pdf2data_import.xml
  edi_pdf2data_oca/wizards/__init__.py
  edi_pdf2data_oca/wizards/pdf2data_template_import_yml.py
  edi_pdf2data_oca/wizards/pdf2data_template_import_yml.xml
  setup/edi_pdf2data_oca/odoo/addons/edi_pdf2data_oca
  setup/edi_pdf2data_oca/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#766 [14.0] sale_order_import: accept default order data via ctx
  sale_order_import/tests/test_order_import.py
  sale_order_import/wizard/sale_order_import.py
Labels: bot is merging ⏳

#756 [13.0][ADD] edi_bank_statement_oca
  edi_bank_statement_oca/README.rst
  edi_bank_statement_oca/__init__.py
  edi_bank_statement_oca/__manifest__.py
  edi_bank_statement_oca/models/__init__.py
  edi_bank_statement_oca/models/account_bank_statement.py
  edi_bank_statement_oca/static/description/icon.png
  edi_bank_statement_oca/views/account_bank_statement_views.xml
  edi_bank_statement_oca/views/edi_exchange_record_views.xml
  setup/edi_bank_statement_oca/odoo/addons/edi_bank_statement_oca
  setup/edi_bank_statement_oca/setup.py
Labels: approved, bot is merging ⏳

#767 [14.0] edi: misc improvements
  edi_exchange_template_oca/models/edi_backend.py
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/views/edi_backend_views.xml
  edi_oca/views/edi_exchange_record_views.xml
  edi_oca/views/edi_exchange_type_views.xml
  edi_oca/views/menuitems.xml
Labels: bot is merging ⏳

#769 [14.0] product_import: Fix product's company
  product_import/wizard/product_import.py
  product_import_ubl/tests/common.py
  product_import_ubl/tests/files/UBL-Catalogue_Example.xml
  product_import_ubl/tests/files/UBL-Catalogue_Example2.xml
  product_import_ubl/tests/test_ubl_catalogue_import.py
Labels: approved, bot is merging ⏳

#736 [15.0][MIG] pdf_helper
  pdf_helper/README.rst
  pdf_helper/__init__.py
  pdf_helper/__manifest__.py
  pdf_helper/i18n/pdf_helper.pot
  pdf_helper/models/__init__.py
  pdf_helper/models/helper.py
  pdf_helper/readme/CONTRIBUTORS.rst
  pdf_helper/readme/DESCRIPTION.rst
  pdf_helper/readme/USAGE.rst
  pdf_helper/static/description/icon.png
  pdf_helper/static/description/index.html
  pdf_helper/tests/__init__.py
  pdf_helper/tests/fixtures/pdf_with_xml_test.pdf
  pdf_helper/tests/test_helper.py
  pdf_helper/utils.py
  setup/pdf_helper/odoo/addons/pdf_helper
  setup/pdf_helper/setup.py
Labels: bot is merging ⏳

#772 [13.0][IMP] edi_stock_oca: add exchange_record_views
  edi_stock_oca/__manifest__.py
  edi_stock_oca/views/edi_exchange_record_views.xml
Labels: approved, bot is merging ⏳

#774 [14.0] edi: fix related record missing broken views
  edi_oca/models/edi_exchange_record.py
  edi_oca/views/edi_exchange_record_views.xml
Labels: bot is merging ⏳
