Repository OCA/edi, pull requests merged in 2024-02, with the labels that each got.

#916 [UPD] base_wamas_ubl: Update grammars ART, ARTEAN, WEAK, WEAP, related tests and fix utils
  base_wamas_ubl/lib/wamas/const.py
  base_wamas_ubl/lib/wamas/test_utils.py
  base_wamas_ubl/lib/wamas/ubl_template/reception.xml
  base_wamas_ubl/lib/wamas/ubl_template/return.xml
  base_wamas_ubl/lib/wamas/utils.py
  base_wamas_ubl/lib/wamas/wamas_grammar/art.py
  base_wamas_ubl/lib/wamas/wamas_grammar/arte.py
  base_wamas_ubl/lib/wamas/wamas_grammar/artean.py
  base_wamas_ubl/lib/wamas/wamas_grammar/weak.py
  base_wamas_ubl/lib/wamas/wamas_grammar/weap.py
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-ARTEAN_INPUT.dict
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-ARTEAN_OUTPUT.wamas
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-ARTE_INPUT.dict
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-ARTE_OUTPUT.wamas
  base_wamas_ubl/tests/samples/UBL2WAMAS-SAMPLE_WEAK_WEAP.wamas
  base_wamas_ubl/tests/test_base_wamas_ubl.py
Labels: bot is merging ⏳

#854 [16.0][ADD] account_invoice_edifact
  account_invoice_edifact/README.rst
  account_invoice_edifact/__init__.py
  account_invoice_edifact/__manifest__.py
  account_invoice_edifact/demo/data_demo.xml
  account_invoice_edifact/models/__init__.py
  account_invoice_edifact/models/account_move.py
  account_invoice_edifact/readme/CONTRIBUTORS.rst
  account_invoice_edifact/readme/CREDITS.rst
  account_invoice_edifact/readme/DESCRIPTION.rst
  account_invoice_edifact/static/description/index.html
  account_invoice_edifact/tests/__init__.py
  account_invoice_edifact/tests/test_account_move.py
  setup/account_invoice_edifact/odoo/addons/account_invoice_edifact
  setup/account_invoice_edifact/setup.py
Labels: bot is merging ⏳

#911 [17.0][MIG] pdf_helper: Migration to 17.0
  pdf_helper/README.rst
  pdf_helper/__init__.py
  pdf_helper/__manifest__.py
  pdf_helper/i18n/es.po
  pdf_helper/i18n/hr.po
  pdf_helper/i18n/pdf_helper.pot
  pdf_helper/models/__init__.py
  pdf_helper/models/helper.py
  pdf_helper/pyproject.toml
  pdf_helper/readme/CONTRIBUTORS.md
  pdf_helper/readme/DESCRIPTION.md
  pdf_helper/readme/USAGE.md
  pdf_helper/static/description/icon.png
  pdf_helper/static/description/index.html
  pdf_helper/tests/__init__.py
  pdf_helper/tests/fixtures/pdf_with_xml_test.pdf
  pdf_helper/tests/test_helper.py
  pdf_helper/utils.py
Labels: merged 🎉

#848 [16.0][PORT] 826 from 14.0
  base_business_document_import/models/business_document_import.py
Labels: approved, ready to merge, bot is merging ⏳

#898 [16.0][FIX + IMP] pdf helper: Fix multi-attachments + Add pdf_embed_xml
  base_ubl/models/ubl.py
  pdf_helper/models/helper.py
  pdf_helper/readme/CONTRIBUTORS.rst
  pdf_helper/readme/USAGE.rst
  pdf_helper/tests/test_helper.py
  pdf_helper/utils.py
Labels: approved, ready to merge, bot is merging ⏳

#918 [16.0][FIX] base_wamas_ubl: address export correction
  base_wamas_ubl/lib/wamas/utils.py
  base_wamas_ubl/lib/wamas/wamas_grammar/kretk.py
  base_wamas_ubl/lib/wamas/wamas_grammar/lst.py
  base_wamas_ubl/lib/wamas/wamas_grammar/weak.py
  base_wamas_ubl/tests/samples/DICT2WAMAS-SAMPLE_OUTPUT.wamas
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-LST_INPUT.dict
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-LST_OUTPUT.wamas
  base_wamas_ubl/tests/samples/UBL2WAMAS-SAMPLE_AUSK_AUSP.wamas
  base_wamas_ubl/tests/samples/UBL2WAMAS-SAMPLE_KRETK_KRETP-DESPATCH_ADVICE.xml
  base_wamas_ubl/tests/samples/UBL2WAMAS-SAMPLE_KRETK_KRETP.wamas
  base_wamas_ubl/tests/samples/UBL2WAMAS-SAMPLE_WEAK_WEAP-DESPATCH_ADVICE.xml
  base_wamas_ubl/tests/samples/UBL2WAMAS-SAMPLE_WEAK_WEAP.wamas
Labels: approved, bot is merging ⏳

#922 [16.0][IMP] base_wamas_ubl: Improve key in ART
  base_wamas_ubl/lib/wamas/wamas_grammar/art.py
Labels: approved, bot is merging ⏳

#944 edi_webservice_oca: fix README
  edi_webservice_oca/README.rst
  edi_webservice_oca/readme/CONFIGURE.rst
  edi_webservice_oca/static/description/index.html
Labels: bot is merging ⏳

#942 [16.0][IMP] base_wamas_ubl: Improve KRETP telegram
  base_wamas_ubl/lib/wamas/wamas_grammar/kretp.py
  base_wamas_ubl/tests/samples/UBL2WAMAS-SAMPLE_KRETK_KRETP.wamas
Labels: bot is merging ⏳

#943 [16.0][UPD] sale_order_import_edifact: Update EDIFACT mapping
  sale_order_import_edifact/tests/common.py
  sale_order_import_edifact/tests/test_edifact_order_import.py
  sale_order_import_edifact/wizard/sale_order_import.py
Labels: bot is merging ⏳
