Repository OCA/edi, pull requests merged in 2024-04, with the labels that each got.

#961 [15.0][IMP] edi_voxel_sale_order_import_oca: Show XML contents on error
  edi_voxel_sale_order_import_oca/models/sale_order.py
Labels: approved, bot is merging ⏳

#941 [17.0]MIG] base_business_document_import: Migration to 17.0
  base_business_document_import/README.rst
  base_business_document_import/__init__.py
  base_business_document_import/__manifest__.py
  base_business_document_import/i18n/base_business_document_import.pot
  base_business_document_import/i18n/cs_CZ.po
  base_business_document_import/i18n/es.po
  base_business_document_import/i18n/fr.po
  base_business_document_import/i18n/fr_FR.po
  base_business_document_import/i18n/nl.po
  base_business_document_import/models/__init__.py
  base_business_document_import/models/business_document_import.py
  base_business_document_import/pyproject.toml
  base_business_document_import/readme/CONTRIBUTORS.md
  base_business_document_import/readme/DESCRIPTION.md
  base_business_document_import/static/description/icon.png
  base_business_document_import/static/description/index.html
  base_business_document_import/tests/__init__.py
  base_business_document_import/tests/test_business_document_import.py
Labels: bot is merging ⏳

#954 [FIX] base_wamas_ubl: reception
  base_wamas_ubl/lib/wamas/ubl_template/reception.xml
  base_wamas_ubl/lib/wamas/ubl_template/return.xml
  base_wamas_ubl/lib/wamas/wamas_grammar/weap.py
  base_wamas_ubl/tests/samples/UBL2WAMAS-SAMPLE_WEAK_WEAP.wamas
  base_wamas_ubl/tests/samples/WAMAS2UBL-SAMPLE_KRETKQ_KRETPQ-DESPATCH_ADVICE.xml
  base_wamas_ubl/tests/samples/WAMAS2UBL-SAMPLE_WEAKQ_WEAPQ-DESPATCH_ADVICE.xml
Labels: approved, ready to merge, bot is merging ⏳

#957 [16.0][IMP] base_wamas_ubl: update Art_ArtGrp and Art_WaLvsSort_LvsSortiment
  base_wamas_ubl/lib/wamas/wamas_grammar/art.py
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-ART_OUTPUT.wamas
Labels: approved, ready to merge, bot is merging ⏳

#966 [15.0][FIX] edi_exchange_template_oca: Change SavepointCase to TransactionCase
  edi_exchange_template_oca/tests/test_nswrapper.py
Labels: bot is merging ⏳
