Repository OCA/edi, pull requests merged in 2024-06, with the labels that each got.

#987 [15.0][FIX] edi_voxel_account_invoice_oca: Intercept post low level method
  edi_voxel_account_invoice_oca/models/account_move.py
Labels: approved, bot is merging ⏳

#993 Replace author 'Camptocamp SA' with 'Camptocamp'
  account_invoice_export/__manifest__.py
  base_ebill_payment_contract/__manifest__.py
  sale_order_customer_free_ref/__manifest__.py
  sale_order_packaging_import/__manifest__.py
Labels: bot is merging ⏳

#986 [12.0] edi_oca: Fix Access error for Administrator (backport)
  edi_oca/migrations/14.0.1.10.0/post-migrate.py
  edi_oca/migrations/14.0.1.20.0/post-migrate.py
  edi_oca/migrations/14.0.1.20.0/pre-migrate.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_security.py
Labels: approved, ready to merge, bot is merging ⏳

#964 [15.0][ADD] base_import_pdf_by_template: New module
  base_import_pdf_by_template/README.rst
  base_import_pdf_by_template/__init__.py
  base_import_pdf_by_template/__manifest__.py
  base_import_pdf_by_template/demo/base_import_pdf_template.xml
  base_import_pdf_by_template/i18n/base_import_pdf_by_template.pot
  base_import_pdf_by_template/i18n/es.po
  base_import_pdf_by_template/models/__init__.py
  base_import_pdf_by_template/models/base_import_pdf_template.py
  base_import_pdf_by_template/readme/CONFIGURE.rst
  base_import_pdf_by_template/readme/CONTRIBUTORS.rst
  base_import_pdf_by_template/readme/DESCRIPTION.rst
  base_import_pdf_by_template/readme/ROADMAP.rst
  base_import_pdf_by_template/readme/USAGE.rst
  base_import_pdf_by_template/security/ir.model.access.csv
  base_import_pdf_by_template/security/security.xml
  base_import_pdf_by_template/static/description/icon.png
  base_import_pdf_by_template/static/description/index.html
  base_import_pdf_by_template/static/src/js/import_menu.js
  base_import_pdf_by_template/static/src/xml/import_menu.xml
  base_import_pdf_by_template/tests/__init__.py
  base_import_pdf_by_template/tests/data/res-partner.pdf
  base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
  base_import_pdf_by_template/views/base_import_pdf_template_line_views.xml
  base_import_pdf_by_template/views/base_import_pdf_template_views.xml
  base_import_pdf_by_template/wizards/__init__.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_mixin.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_preview.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_preview_views.xml
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload_views.xml
  requirements.txt
  setup/base_import_pdf_by_template/odoo/addons/base_import_pdf_by_template
  setup/base_import_pdf_by_template/setup.py
  setup/test_base_import_pdf_by_template/odoo/addons/test_base_import_pdf_by_template
  setup/test_base_import_pdf_by_template/setup.py
  test_base_import_pdf_by_template/README.rst
  test_base_import_pdf_by_template/__init__.py
  test_base_import_pdf_by_template/__manifest__.py
  test_base_import_pdf_by_template/demo/base_import_pdf_template.xml
  test_base_import_pdf_by_template/hooks.py
  test_base_import_pdf_by_template/i18n/test_base_import_pdf_by_template.pot
  test_base_import_pdf_by_template/readme/CONTRIBUTORS.rst
  test_base_import_pdf_by_template/readme/DESCRIPTION.rst
  test_base_import_pdf_by_template/static/description/icon.png
  test_base_import_pdf_by_template/static/description/index.html
  test_base_import_pdf_by_template/tests/__init__.py
  test_base_import_pdf_by_template/tests/data/account_invoice_tecnativa.pdf
  test_base_import_pdf_by_template/tests/data/purchase_order_declathon.pdf
  test_base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
Labels: approved, bot is merging ⏳
