Repository OCA/edi, pull requests merged in 2024-12, with the labels that each got.

#1035 [14.0][IMP] edi_oca: Add new model edi.configuration
  edi_oca/README.rst
  edi_oca/__manifest__.py
  edi_oca/data/edi_configuration.xml
  edi_oca/models/__init__.py
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_configuration.py
  edi_oca/models/edi_configuration_trigger.py
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/readme/CONTRIBUTORS.rst
  edi_oca/security/ir_model_access.xml
  edi_oca/static/description/index.html
  edi_oca/tests/__init__.py
  edi_oca/tests/fake_components.py
  edi_oca/tests/fake_models.py
  edi_oca/tests/test_consumer_mixin.py
  edi_oca/tests/test_edi_configuration.py
  edi_oca/views/edi_configuration_trigger_views.xml
  edi_oca/views/edi_configuration_views.xml
  edi_oca/views/menuitems.xml
Labels: approved, ready to merge, bot is merging ⏳

#1081 [17.0][FIX] test_base_import_pdf_by_template: Improve pattern
  test_base_import_pdf_by_template/demo/base_import_pdf_template.xml
Labels: bot is merging ⏳

#1071 [17.0][FW][IMP] base_edi: introduce a basic edi user group
  base_edi/security/edi_groups.xml
Labels: bot is merging ⏳

#1085 [14.0] account_invoice_*facturx: fix factur-x lib version
  account_invoice_facturx/__manifest__.py
  account_invoice_import_facturx/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#1082 [15.0][FIX] test_base_import_pdf_by_template: Improve pattern
  account_invoice_facturx/__manifest__.py
  requirements.txt
  test_base_import_pdf_by_template/demo/base_import_pdf_template.xml
Labels: bot is merging ⏳

#893 [16.0][MIG] base_ubl_payment
  account_einvoice_generate/models/account_move.py
  base_ubl_payment/README.rst
  base_ubl_payment/__init__.py
  base_ubl_payment/__manifest__.py
  base_ubl_payment/i18n/base_ubl_payment.pot
  base_ubl_payment/i18n/es.po
  base_ubl_payment/i18n/fr.po
  base_ubl_payment/i18n/hr.po
  base_ubl_payment/i18n/nl.po
  base_ubl_payment/models/__init__.py
  base_ubl_payment/models/ubl.py
  base_ubl_payment/readme/CONTRIBUTORS.rst
  base_ubl_payment/readme/DESCRIPTION.rst
  base_ubl_payment/static/description/icon.png
  base_ubl_payment/static/description/index.html
  setup/base_ubl_payment/odoo/addons/base_ubl_payment
  setup/base_ubl_payment/setup.py
Labels: approved, bot is merging ⏳

#1001 [IMP] product_import, product_import_ubl: add sale_delay
  product_import/tests/test_product_import.py
  product_import/wizard/product_import.py
  product_import_ubl/wizard/product_import.py
Labels: bot is merging ⏳, no stale

#1083 [FIX] edi_oca: compute inverse properly
  edi_oca/models/edi_exchange_type.py
Labels: bot is merging ⏳

#1014 [15.0][FWP] edi_oca: Fix Access error for Administrator (forward port)
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_security.py
Labels: bot is merging ⏳, stale

#1056 [17.0][ADD] base_import_pdf_by_template_account: New module
  base_import_pdf_by_template/models/base_import_pdf_template.py
  base_import_pdf_by_template/security/security.xml
  base_import_pdf_by_template/views/base_import_pdf_template_line_views.xml
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload.py
  base_import_pdf_by_template_account/README.rst
  base_import_pdf_by_template_account/__init__.py
  base_import_pdf_by_template_account/__manifest__.py
  base_import_pdf_by_template_account/demo/base_import_pdf_template.xml
  base_import_pdf_by_template_account/i18n/base_import_pdf_by_template_account.pot
  base_import_pdf_by_template_account/i18n/es.po
  base_import_pdf_by_template_account/models/__init__.py
  base_import_pdf_by_template_account/models/account_move.py
  base_import_pdf_by_template_account/pyproject.toml
  base_import_pdf_by_template_account/readme/CONTRIBUTORS.md
  base_import_pdf_by_template_account/readme/DESCRIPTION.md
  base_import_pdf_by_template_account/security/ir.model.access.csv
  base_import_pdf_by_template_account/security/security.xml
  base_import_pdf_by_template_account/static/description/icon.png
  base_import_pdf_by_template_account/static/description/index.html
  base_import_pdf_by_template_account/tests/__init__.py
  base_import_pdf_by_template_account/tests/data/account_invoice_tecnativa.pdf
  base_import_pdf_by_template_account/tests/test_base_import_pdf_by_template_account.py
  base_import_pdf_by_template_account/views/base_import_pdf_template_views.xml
  test_base_import_pdf_by_template/demo/base_import_pdf_template.xml
  test_base_import_pdf_by_template/hooks.py
  test_base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
Labels: approved, bot is merging ⏳

#1097 [16.0][IMP] account_einvoice_generate: add hook for tax's UNECE Due Date Type Code
  account_einvoice_generate/models/account_move.py
  account_invoice_facturx/models/account_move.py
Labels: bot is merging ⏳

#1099 [16.0][FIX] account_invoice_report: backport use of _is_invoice_report()
  account_invoice_facturx/models/ir_actions_report.py
Labels: bot is merging ⏳

#1047 [17.0][IMP] account_invoice_facturx: add RateApplicablePercent in XML when there is not tax
  account_invoice_facturx/README.rst
  account_invoice_facturx/models/account_move.py
  account_invoice_facturx/readme/INSTALL.md
  account_invoice_facturx/static/description/index.html
Labels: bot is merging ⏳

#1102 [18.0][FW][IMP] base_edi: introduce a basic edi user group
  base_edi/security/edi_groups.xml
Labels: approved, bot is merging ⏳
