Repository OCA/edi, pull requests merged in 2024-07, with the labels that each got.

#945 [16.0][IMP] despatch_advice_import_ubl : collect package (logistic transport units)
  despatch_advice_import/wizard/despatch_advice_import.py
  despatch_advice_import_ubl/tests/files/despatch_advice_2.xml
  despatch_advice_import_ubl/tests/files/despatch_advice_tmpl.xml
  despatch_advice_import_ubl/tests/test_despatch_advice_import.py
  despatch_advice_import_ubl/tests/test_despatch_advice_mix.py
  despatch_advice_import_ubl/wizard/despatch_advice_import.py
Labels: approved, ready to merge, bot is merging ⏳

#988 [16.0[IMP] base_wamas_ubl: Fix arte grammar
  base_wamas_ubl/lib/wamas/wamas_grammar/arte.py
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-ARTE_INPUT.dict
  base_wamas_ubl/tests/samples/TELEGRAM-SAMPLE-ARTE_OUTPUT.wamas
Labels: approved, ready to merge, bot is merging ⏳

#990 [16.0][IMP] base_edifact: improve method map2odoo_product to take pia segment into account
  base_edifact/README.rst
  base_edifact/models/edifact.py
  base_edifact/readme/CONTRIBUTORS.rst
  base_edifact/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1002 [16.0][IMP] base_wamas_ubl: support escaping the value of variables into the xml content
  base_wamas_ubl/lib/wamas/utils.py
Labels: approved, ready to merge, bot is merging ⏳

#1004 [16.0][IMP] base_edi: introduce a basic edi user group
  base_edi/security/edi_groups.xml
Labels: bot is merging ⏳

#1005 [15.0][IMP] base_edi: introduce a basic edi user group (Backport from 16.0)
  base_edi/security/edi_groups.xml
Labels: bot is merging ⏳

#1006 [14.0][IMP] base_edi: introduce a basic edi user group (Backport from 16.0)
  base_edi/security/edi_groups.xml
Labels: bot is merging ⏳

#890 [16.0][MIG] account_invoice_export
  account_invoice_export/README.rst
  account_invoice_export/__init__.py
  account_invoice_export/__manifest__.py
  account_invoice_export/data/mail_activity_type.xml
  account_invoice_export/i18n/account_invoice_export.pot
  account_invoice_export/models/__init__.py
  account_invoice_export/models/account_move.py
  account_invoice_export/models/transmit_method.py
  account_invoice_export/readme/CONTRIBUTORS.rst
  account_invoice_export/readme/CREDITS.rst
  account_invoice_export/readme/DESCRIPTION.rst
  account_invoice_export/static/description/icon.png
  account_invoice_export/static/description/index.html
  account_invoice_export/tests/__init__.py
  account_invoice_export/tests/common.py
  account_invoice_export/tests/test_export_invoice.py
  account_invoice_export/views/account_move.xml
  account_invoice_export/views/message_template.xml
  account_invoice_export/views/transmit_method.xml
  account_invoice_export_job/README.rst
  account_invoice_export_job/__init__.py
  account_invoice_export_job/__manifest__.py
  account_invoice_export_job/data/queue_job_data.xml
  account_invoice_export_job/models/__init__.py
  account_invoice_export_job/models/account_move.py
  account_invoice_export_job/readme/CONTRIBUTORS.rst
  account_invoice_export_job/readme/CREDITS.rst
  account_invoice_export_job/readme/DESCRIPTION.rst
  account_invoice_export_job/static/description/index.html
  account_invoice_export_job/tests/__init__.py
  account_invoice_export_job/tests/test_account_invoice_export_job.py
  account_invoice_export_job/views/message_template.xml
  setup/account_invoice_export/odoo/addons/account_invoice_export
  setup/account_invoice_export/setup.py
  setup/account_invoice_export_job/odoo/addons/account_invoice_export_job
  setup/account_invoice_export_job/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1010 [15.0][FIX] edi_oca: Don't run quick_exec if backend is not active
  edi_oca/models/edi_exchange_record.py
Labels: bot is merging ⏳

#1009 [14.0][FIX] edi_oca: Don't run quick_exec if backend is not active
  edi_oca/models/edi_exchange_record.py
Labels: bot is merging ⏳

#995 [13.0] Replace 'Camptocamp SA' with 'Camptocamp'
  account_invoice_export/__manifest__.py
  base_ebill_payment_contract/__manifest__.py
  sale_order_customer_free_ref/__manifest__.py
  sale_order_import_ubl_customer_free_ref/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#1015 [14.0][FIX] edi_oca: do not try to automatically re-process input_processed_error records
  edi_oca/models/edi_backend.py
  edi_oca/tests/test_backend_jobs.py
Labels: bot is merging ⏳

#1008 [14.0][FIX] purchase_order_ubl: filter out section/note lines
  purchase_order_ubl/models/purchase.py
Labels: bot is merging ⏳

#1011 [12.0][BKP] edi_oca: More commits
  edi_oca/__manifest__.py
  edi_oca/data/ir_actions_server.xml
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/tests/test_backend_input.py
  edi_oca/tests/test_backend_jobs.py
  edi_oca/tests/test_backend_process.py
  edi_oca/tests/test_backend_validate.py
  edi_oca/views/edi_backend_views.xml
  edi_oca/views/edi_exchange_record_views.xml
  edi_oca/views/edi_exchange_type_views.xml
Labels: approved, bot is merging ⏳

#1012 [14.0] edi_endpoint: fix form view inheritance
  edi_endpoint_oca/views/edi_endpoint_views.xml
Labels: bot is merging ⏳
