Repository OCA/edi, pull requests merged in 2024-05, with the labels that each got.

#977 [15.0][FIX] edi_webservice_oca: Add responses to test-requirements.txt (from edi_webservice_oca tests)
  edi_webservice_oca/demo/edi_backend.xml
  edi_webservice_oca/tests/test_backend.py
  test-requirements.txt
Labels: bot is merging ⏳

#974 [14.0][FIX] edi_oca: Fix Access error for Administrator
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_security.py
Labels: approved, ready to merge, bot is merging ⏳

#973 [16.0][IMP] base_edifact: LIN segment might not contain EAN
  base_edifact/models/edifact.py
Labels: approved, ready to merge, bot is merging ⏳

#976 [14.0][FIX] pdf_helper: fix crash in PDF parsing and PyPDF2 -> pypdf
  pdf_helper/__manifest__.py
  pdf_helper/models/helper.py
  pdf_helper/static/description/index.html
  pdf_helper/utils.py
  requirements.txt
Labels: bot is merging ⏳

#978 [16.0][IMP] base_edifact: return code/barcode product even though not found in map2odoo_product
  base_edifact/models/edifact.py
  base_edifact/tests/test_base_edifact.py
Labels: bot is merging ⏳

#889 [16.0][MIG] base_ebill_payment_contract
  base_ebill_payment_contract/README.rst
  base_ebill_payment_contract/__init__.py
  base_ebill_payment_contract/__manifest__.py
  base_ebill_payment_contract/demo/ebill_payment_contract.xml
  base_ebill_payment_contract/i18n/base_ebill_payment_contract.pot
  base_ebill_payment_contract/i18n/es.po
  base_ebill_payment_contract/models/__init__.py
  base_ebill_payment_contract/models/ebill_payment_contract.py
  base_ebill_payment_contract/models/res_partner.py
  base_ebill_payment_contract/readme/CONTRIBUTORS.rst
  base_ebill_payment_contract/readme/CREDITS.rst
  base_ebill_payment_contract/readme/DESCRIPTION.rst
  base_ebill_payment_contract/readme/USAGE.rst
  base_ebill_payment_contract/security/ir.model.access.csv
  base_ebill_payment_contract/static/description/icon.png
  base_ebill_payment_contract/static/description/index.html
  base_ebill_payment_contract/tests/__init__.py
  base_ebill_payment_contract/tests/test_base_ebill_payment_contract.py
  base_ebill_payment_contract/views/ebill_payment_contract.xml
  setup/base_ebill_payment_contract/odoo/addons/base_ebill_payment_contract
  setup/base_ebill_payment_contract/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#981 [14.0][FIX] base_ebill_payment_contract: fix tests
  base_ebill_payment_contract/tests/test_base_ebill_payment_contract.py
Labels: bot is merging ⏳

#982 [16.0][FIX] base_ebill_payment_contract: fix tests
  base_ebill_payment_contract/tests/test_base_ebill_payment_contract.py
Labels: bot is merging ⏳
