Repository OCA/edi, pull requests merged in 2024-10, with the labels that each got.

#1048 [17.0][MIG] base_import_pdf_by_template: Migration to 17.0
  base_import_pdf_by_template/README.rst
  base_import_pdf_by_template/__init__.py
  base_import_pdf_by_template/__manifest__.py
  base_import_pdf_by_template/demo/base_import_pdf_template.xml
  base_import_pdf_by_template/i18n/base_import_pdf_by_template.pot
  base_import_pdf_by_template/i18n/es.po
  base_import_pdf_by_template/models/__init__.py
  base_import_pdf_by_template/models/base_import_pdf_template.py
  base_import_pdf_by_template/pyproject.toml
  base_import_pdf_by_template/readme/CONFIGURE.md
  base_import_pdf_by_template/readme/CONTRIBUTORS.md
  base_import_pdf_by_template/readme/DESCRIPTION.md
  base_import_pdf_by_template/readme/ROADMAP.md
  base_import_pdf_by_template/readme/USAGE.md
  base_import_pdf_by_template/security/ir.model.access.csv
  base_import_pdf_by_template/security/security.xml
  base_import_pdf_by_template/static/description/icon.png
  base_import_pdf_by_template/static/description/index.html
  base_import_pdf_by_template/static/src/js/import_menu.esm.js
  base_import_pdf_by_template/static/src/xml/import_records.xml
  base_import_pdf_by_template/tests/__init__.py
  base_import_pdf_by_template/tests/data/res-partner.pdf
  base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
  base_import_pdf_by_template/views/base_import_pdf_template_line_views.xml
  base_import_pdf_by_template/views/base_import_pdf_template_views.xml
  base_import_pdf_by_template/wizards/__init__.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_mixin.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_preview.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_preview_views.xml
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload_views.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#1049 [17.0][MIG] test_base_import_pdf_by_template: Migration to 17.0
  test_base_import_pdf_by_template/README.rst
  test_base_import_pdf_by_template/__init__.py
  test_base_import_pdf_by_template/__manifest__.py
  test_base_import_pdf_by_template/demo/base_import_pdf_template.xml
  test_base_import_pdf_by_template/hooks.py
  test_base_import_pdf_by_template/i18n/test_base_import_pdf_by_template.pot
  test_base_import_pdf_by_template/pyproject.toml
  test_base_import_pdf_by_template/readme/CONTRIBUTORS.md
  test_base_import_pdf_by_template/readme/DESCRIPTION.md
  test_base_import_pdf_by_template/static/description/icon.png
  test_base_import_pdf_by_template/static/description/index.html
  test_base_import_pdf_by_template/tests/__init__.py
  test_base_import_pdf_by_template/tests/data/account_invoice_tecnativa.pdf
  test_base_import_pdf_by_template/tests/data/purchase_order_declathon.pdf
  test_base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
Labels: approved, bot is merging ⏳

#1042 [12.0][FIX] fix issue pypdf 5.0 dropped support for python<=3.7
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#1044 [12.0][IMP] edi_oca: Add hook on new output exchange record search
  edi_oca/models/edi_backend.py
Labels: approved, bot is merging ⏳

#892 [16.0][FIX] base_ubl: schemeID for GTIN is 0160
  base_ubl/models/ubl.py
  base_ubl/tests/__init__.py
  base_ubl/tests/test_ubl_parse.py
Labels: approved, bot is merging ⏳

#1051 [17.0][IMP] base_import_pdf_by_template: Add dd/MM/YY date_format compatibility
  base_import_pdf_by_template/models/base_import_pdf_template.py
  base_import_pdf_by_template/views/base_import_pdf_template_line_views.xml
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_preview.py
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_preview_views.xml
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload.py
Labels: approved, bot is merging ⏳

#1046 [16.0][IMP] account_invoice_facturx: add RateApplicablePercent in XML when there is not tax
  account_invoice_facturx/README.rst
  account_invoice_facturx/models/account_move.py
  account_invoice_facturx/readme/INSTALL.rst
  account_invoice_facturx/static/description/index.html
Labels: bot is merging ⏳

#1053 [15.0][IMP] base_import_pdf_by_template: Add fixed value compatibility to different types of fields
  base_import_pdf_by_template/README.rst
  base_import_pdf_by_template/demo/base_import_pdf_template.xml
  base_import_pdf_by_template/models/base_import_pdf_template.py
  base_import_pdf_by_template/readme/ROADMAP.rst
  base_import_pdf_by_template/static/description/index.html
  base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
  base_import_pdf_by_template/views/base_import_pdf_template_line_views.xml
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload.py
  test_base_import_pdf_by_template/demo/base_import_pdf_template.xml
  test_base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
Labels: approved, bot is merging ⏳

#1055 [18.0][MIG] base_edi
  base_edi/README.rst
  base_edi/__init__.py
  base_edi/__manifest__.py
  base_edi/data/module_category.xml
  base_edi/i18n/base_edi.pot
  base_edi/i18n/es.po
  base_edi/i18n/fr.po
  base_edi/i18n/hr.po
  base_edi/i18n/it.po
  base_edi/i18n/nl.po
  base_edi/pyproject.toml
  base_edi/readme/CONTRIBUTORS.md
  base_edi/readme/DESCRIPTION.md
  base_edi/readme/ROADMAP.md
  base_edi/security/edi_groups.xml
  base_edi/static/description/icon.png
  base_edi/static/description/icon.svg
  base_edi/static/description/index.html
  base_edi/tests/__init__.py
  base_edi/tests/test_base_edi.py
  base_edi/views/edi_menu.xml
Labels: bot is merging ⏳

#1057 [17.0][FIX] pdf_helper: Odoo compatibility
  pdf_helper/tests/test_helper.py
  pdf_helper/utils.py
Labels: bot is merging ⏳

#1054 [17.0][IMP] base_import_pdf_by_template: Add fixed value compatibility to different types of fields
  base_import_pdf_by_template/README.rst
  base_import_pdf_by_template/demo/base_import_pdf_template.xml
  base_import_pdf_by_template/models/base_import_pdf_template.py
  base_import_pdf_by_template/readme/ROADMAP.md
  base_import_pdf_by_template/static/description/index.html
  base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
  base_import_pdf_by_template/views/base_import_pdf_template_line_views.xml
  test_base_import_pdf_by_template/demo/base_import_pdf_template.xml
  test_base_import_pdf_by_template/tests/test_base_import_pdf_by_template.py
Labels: bot is merging ⏳
