Repository OCA/edi, pull requests merged in 2024-03, with the labels that each got.

#946 [16.0][IMP] base_wamas_ubl: update ID for reception and return UBL template
  base_wamas_ubl/lib/wamas/ubl_template/reception.xml
  base_wamas_ubl/lib/wamas/ubl_template/return.xml
  base_wamas_ubl/tests/samples/WAMAS2UBL-SAMPLE_KRETKQ_KRETPQ-DESPATCH_ADVICE.xml
  base_wamas_ubl/tests/samples/WAMAS2UBL-SAMPLE_WEAKQ_WEAPQ-DESPATCH_ADVICE.xml
Labels: approved, bot is merging ⏳

#950 [16.0][IMP] base_edifact: Map PIA segment with product default_code
  base_edifact/models/edifact.py
  base_edifact/tests/test_base_edifact.py
Labels: approved, bot is merging ⏳

#940 [UPD] base_wamas_ubl: Add new grammars BKORR, LBA, LBABQ, LBAEQ and LBAMQ
  base_wamas_ubl/lib/wamas/const.py
  base_wamas_ubl/lib/wamas/wamas_grammar/bkorr.py
  base_wamas_ubl/lib/wamas/wamas_grammar/lba.py
  base_wamas_ubl/lib/wamas/wamas_grammar/lbabq.py
  base_wamas_ubl/lib/wamas/wamas_grammar/lbaeq.py
  base_wamas_ubl/lib/wamas/wamas_grammar/lbamq.py
Labels: bot is merging ⏳

#948 [17.0][MIG] account_invoice_facturx
  account_invoice_facturx/README.rst
  account_invoice_facturx/__init__.py
  account_invoice_facturx/__manifest__.py
  account_invoice_facturx/hooks.py
  account_invoice_facturx/i18n/account_invoice_factur-x.pot
  account_invoice_facturx/i18n/account_invoice_facturx.pot
  account_invoice_facturx/i18n/de.po
  account_invoice_facturx/i18n/es.po
  account_invoice_facturx/i18n/fr.po
  account_invoice_facturx/models/__init__.py
  account_invoice_facturx/models/account_move.py
  account_invoice_facturx/models/ir_actions_report.py
  account_invoice_facturx/models/res_company.py
  account_invoice_facturx/pyproject.toml
  account_invoice_facturx/readme/CONFIGURE.md
  account_invoice_facturx/readme/CONTRIBUTORS.md
  account_invoice_facturx/readme/DESCRIPTION.md
  account_invoice_facturx/readme/INSTALL.md
  account_invoice_facturx/static/description/icon.png
  account_invoice_facturx/static/description/index.html
  account_invoice_facturx/static/logos/factur-x-basic.png
  account_invoice_facturx/static/logos/factur-x-basicwl.png
  account_invoice_facturx/static/logos/factur-x-en16931.png
  account_invoice_facturx/static/logos/factur-x-extended.png
  account_invoice_facturx/static/logos/factur-x-minimum.png
  account_invoice_facturx/tests/__init__.py
  account_invoice_facturx/tests/test_facturx_invoice.py
  account_invoice_facturx/views/account_move.xml
  account_invoice_facturx/views/res_config_settings.xml
  account_invoice_facturx/views/res_partner.xml
  account_invoice_facturx/wizards/__init__.py
  account_invoice_facturx/wizards/res_config_settings.py
  requirements.txt
Labels: bot is merging ⏳

#861 [IMP]base_ubl_payment: Add payment means to SEPA direct debit/credit …
  base_ubl_payment/models/ubl.py
Labels: approved, bot is merging ⏳

#934 [14.0] account_invoice_import_simple_pdf: remove pdfplumber
  account_invoice_import_simple_pdf/README.rst
  account_invoice_import_simple_pdf/__manifest__.py
  account_invoice_import_simple_pdf/readme/CONFIGURE.rst
  account_invoice_import_simple_pdf/readme/INSTALL.rst
  account_invoice_import_simple_pdf/static/description/index.html
  account_invoice_import_simple_pdf/tests/test_invoice_import.py
  account_invoice_import_simple_pdf/wizard/account_invoice_import.py
  requirements.txt
Labels: bot is merging ⏳

#952 [16.0][UPD] base_wamas_ubl: Update AUSK grammar
  base_wamas_ubl/lib/wamas/wamas_grammar/ausk.py
Labels: approved, ready to merge, bot is merging ⏳

#956 [15.0][MIG] edi_voxel_sale_secondary_unit: Migration to version 15.0
  edi_voxel_sale_secondary_unit_oca/README.rst
  edi_voxel_sale_secondary_unit_oca/__init__.py
  edi_voxel_sale_secondary_unit_oca/__manifest__.py
  edi_voxel_sale_secondary_unit_oca/i18n/edi_voxel_sale_secondary_unit.pot
  edi_voxel_sale_secondary_unit_oca/models/__init__.py
  edi_voxel_sale_secondary_unit_oca/models/sale_order.py
  edi_voxel_sale_secondary_unit_oca/readme/CONTRIBUTORS.rst
  edi_voxel_sale_secondary_unit_oca/readme/DESCRIPTION.rst
  edi_voxel_sale_secondary_unit_oca/readme/USAGE.rst
  edi_voxel_sale_secondary_unit_oca/static/description/icon.png
  edi_voxel_sale_secondary_unit_oca/static/description/index.html
  edi_voxel_sale_secondary_unit_oca/tests/__init__.py
  edi_voxel_sale_secondary_unit_oca/tests/test_edi_voxel_sale_secondary_unit.py
  setup/edi_voxel_sale_secondary_unit_oca/odoo/addons/edi_voxel_sale_secondary_unit_oca
  setup/edi_voxel_sale_secondary_unit_oca/setup.py
Labels: bot is merging ⏳

#955 [16.0][IMP] despatch_advice_import: allow to validate picking with quantity larger than the reserved quantity
  despatch_advice_import/tests/test_despatch_advice_import.py
  despatch_advice_import/wizard/despatch_advice_import.py
  despatch_advice_import/wizard/despatch_advice_import.xml
Labels: approved, ready to merge, bot is merging ⏳
