Repository OCA/edi, pull requests merged in 2025-02, with the labels that each got.

#1124 [14.0] edi: fix _edi_send_via_edi w/ quick exec
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_sale_oca/views/res_partner.xml
  edi_xml_oca/tests/common.py
  edi_xml_oca/tests/test_xml.py
Labels: bot is merging ⏳

#1125 [16.0][IMP] base_wamas_ubl sub-transfer
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_COMB_WEAKQ_WEAPQ-DESPATCH_ADVICE.xml
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_COMB_WEAKQ_WEAPQ.wamas
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_SIMPLE_WEAKQ_WEAPQ-DESPATCH_ADVICE.xml
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_SIMPLE_WEAKQ_WEAPQ.wamas
  base_wamas_ubl/lib/wamas/tests/test_wamas2ubl.py
  base_wamas_ubl/lib/wamas/wamas2ubl.py
  base_wamas_ubl/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1123 [14.0] edi_exchange_template: declare tmpl to use explicitly
  edi_exchange_template_oca/__manifest__.py
  edi_exchange_template_oca/migrations/14.0.1.6.0/post-migrate.py
  edi_exchange_template_oca/models/__init__.py
  edi_exchange_template_oca/models/edi_backend.py
  edi_exchange_template_oca/models/edi_exchange_template_mixin.py
  edi_exchange_template_oca/models/edi_exchange_type.py
  edi_exchange_template_oca/tests/__init__.py
  edi_exchange_template_oca/tests/test_backend_and_type.py
  edi_exchange_template_oca/tests/test_edi_backend_output.py
  edi_exchange_template_oca/views/edi_exchange_template_output_views.xml
  edi_exchange_template_oca/views/edi_exchange_type_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1126 [18.0] [MIG] sale_order_customer_free_ref
  sale_order_customer_free_ref/README.rst
  sale_order_customer_free_ref/__init__.py
  sale_order_customer_free_ref/__manifest__.py
  sale_order_customer_free_ref/i18n/es.po
  sale_order_customer_free_ref/i18n/it.po
  sale_order_customer_free_ref/i18n/sale_order_customer_free_ref.pot
  sale_order_customer_free_ref/models/__init__.py
  sale_order_customer_free_ref/models/account_move.py
  sale_order_customer_free_ref/models/sale_order.py
  sale_order_customer_free_ref/pyproject.toml
  sale_order_customer_free_ref/readme/CONTRIBUTORS.md
  sale_order_customer_free_ref/readme/CREDITS.md
  sale_order_customer_free_ref/readme/DESCRIPTION.md
  sale_order_customer_free_ref/static/description/icon.png
  sale_order_customer_free_ref/static/description/index.html
  sale_order_customer_free_ref/tests/__init__.py
  sale_order_customer_free_ref/tests/test_sale_order_customer_free_ref.py
  sale_order_customer_free_ref/views/account_move.xml
  sale_order_customer_free_ref/views/sale_order.xml
Labels: approved, bot is merging ⏳

#1129 [17.0][IMP] base_import_pdf_by_template: Add *d-*b-*Y date_format
  base_import_pdf_by_template/README.rst
  base_import_pdf_by_template/models/base_import_pdf_template.py
  base_import_pdf_by_template/readme/ROADMAP.md
  base_import_pdf_by_template/static/description/index.html
Labels: bot is merging ⏳
