Repository OCA/edi, pull requests merged in 2025-01, with the labels that each got.

#1068 [16.0] base_wamas_ubl: run lib tests
  base_wamas_ubl/lib/test_wamas2dict
  base_wamas_ubl/lib/wamas/dict2wamas.py
  base_wamas_ubl/lib/wamas/tests/samples/UBL2WAMAS-SAMPLE_AUSK_AUSP-DESPATCH_ADVICE2.xml
  base_wamas_ubl/lib/wamas/tests/samples/UBL2WAMAS-SAMPLE_AUSK_AUSP.wamas
  base_wamas_ubl/lib/wamas/tests/samples/UBL2WAMAS-SAMPLE_KRETK_KRETP-DESPATCH_ADVICE.xml
  base_wamas_ubl/lib/wamas/tests/samples/UBL2WAMAS-SAMPLE_KRETK_KRETP.wamas
  base_wamas_ubl/lib/wamas/tests/samples/UBL2WAMAS-SAMPLE_WEAK_WEAP-DESPATCH_ADVICE.xml
  base_wamas_ubl/lib/wamas/tests/samples/UBL2WAMAS-SAMPLE_WEAK_WEAP.wamas
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_AUSKQ_WATEKQ_WATEPQ-DESPATCH_ADVICE.xml
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_AUSKQ_WATEKQ_WATEPQ.wamas
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_KRETKQ_KRETPQ-DESPATCH_ADVICE.xml
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_KRETKQ_KRETPQ.wamas
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_WEAKQ_WEAPQ-DESPATCH_ADVICE.xml
  base_wamas_ubl/lib/wamas/tests/samples/WAMAS2UBL-SAMPLE_WEAKQ_WEAPQ.wamas
  base_wamas_ubl/lib/wamas/tests/test_dict2wamas.py
  base_wamas_ubl/lib/wamas/tests/test_ubl2wamas.py
  base_wamas_ubl/lib/wamas/tests/test_wamas2dict.py
  base_wamas_ubl/lib/wamas/tests/test_wamas2ubl.py
  base_wamas_ubl/lib/wamas/tests/test_wamas2wamas.py
  base_wamas_ubl/lib/wamas/utils.py
  base_wamas_ubl/tests/test_base_wamas_ubl.py
  base_wamas_ubl/tests/test_wamas_lib.py
Labels: bot is merging ⏳

#1060 [16.0][FIX] base_wamas_ubl: dict_key in Art_RestHaltTaWa
  base_wamas_ubl/lib/wamas/wamas_grammar/art.py
Labels: approved, ready to merge, bot is merging ⏳

#1034 [16.0][IMP] base_wamas_ubl PromiseDeliveryPeriod
  base_wamas_ubl/lib/wamas/tests/samples/UBL2WAMAS-SAMPLE_WEAK_WEAP-DESPATCH_ADVICE.xml
  base_wamas_ubl/lib/wamas/tests/samples/UBL2WAMAS-SAMPLE_WEAK_WEAP.wamas
  base_wamas_ubl/lib/wamas/utils.py
  base_wamas_ubl/lib/wamas/wamas_grammar/weak.py
  base_wamas_ubl/lib/wamas/wamas_grammar/weap.py
Labels: approved, bot is merging ⏳

#1105 [16.0][IMP] base_wamas_ubl: simulate partial reception
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_input_wea_partial.wamas
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_output_wea_partial.wamas
  base_wamas_ubl/lib/wamas/tests/test_wamas2wamas.py
  base_wamas_ubl/lib/wamas/utils.py
  base_wamas_ubl/lib/wamas/wamas2wamas.py
  base_wamas_ubl/lib/wamas/wamas_grammar/weapq.py
  base_wamas_ubl/models/base_wamas_ubl.py
Labels: approved, bot is merging ⏳

#1107 [16.0][IMP] base_wamas_ubl: simulate complete rejection at reception
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_input_kret_nothing.wamas
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_input_kret_partial.wamas
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_input_wea_nothing.wamas
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_output_kret.wamas
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_output_kret_nothing.wamas
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_output_kret_partial.wamas
  base_wamas_ubl/lib/wamas/tests/samples/wamas2wamas_output_wea_nothing.wamas
  base_wamas_ubl/lib/wamas/tests/test_wamas2wamas.py
  base_wamas_ubl/lib/wamas/utils.py
  base_wamas_ubl/lib/wamas/wamas2wamas.py
  base_wamas_ubl/lib/wamas/wamas_grammar/kretpq.py
  base_wamas_ubl/models/base_wamas_ubl.py
  base_wamas_ubl/tests/test_base_wamas_ubl.py
Labels: bot is merging ⏳

#1110 [14.0] edi_endpoint: extend mixin views
  edi_endpoint_oca/views/edi_endpoint_views.xml
Labels: bot is merging ⏳

#1112 [17.0][FIX] base_import_pdf_by_template_account: Avoid error when adding a pdf attachment to an invoice if no template applies
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload.py
  base_import_pdf_by_template_account/models/account_move.py
Labels: approved, bot is merging ⏳

#1037 [17.0][MIG] account_invoice_export
  account_invoice_export/README.rst
  account_invoice_export/__init__.py
  account_invoice_export/__manifest__.py
  account_invoice_export/data/mail_activity_type.xml
  account_invoice_export/i18n/account_invoice_export.pot
  account_invoice_export/i18n/it.po
  account_invoice_export/models/__init__.py
  account_invoice_export/models/account_move.py
  account_invoice_export/models/transmit_method.py
  account_invoice_export/pyproject.toml
  account_invoice_export/readme/CONTRIBUTORS.md
  account_invoice_export/readme/CREDITS.md
  account_invoice_export/readme/DESCRIPTION.md
  account_invoice_export/static/description/icon.png
  account_invoice_export/static/description/index.html
  account_invoice_export/tests/__init__.py
  account_invoice_export/tests/common.py
  account_invoice_export/tests/test_export_invoice.py
  account_invoice_export/views/account_move.xml
  account_invoice_export/views/message_template.xml
  account_invoice_export/views/transmit_method.xml
Labels: approved, ready to merge, bot is merging ⏳

#1038 [17.0][MIG] base_ebill_payment_contract
  base_ebill_payment_contract/README.rst
  base_ebill_payment_contract/__init__.py
  base_ebill_payment_contract/__manifest__.py
  base_ebill_payment_contract/demo/ebill_payment_contract.xml
  base_ebill_payment_contract/i18n/base_ebill_payment_contract.pot
  base_ebill_payment_contract/i18n/es.po
  base_ebill_payment_contract/i18n/it.po
  base_ebill_payment_contract/models/__init__.py
  base_ebill_payment_contract/models/ebill_payment_contract.py
  base_ebill_payment_contract/models/res_partner.py
  base_ebill_payment_contract/pyproject.toml
  base_ebill_payment_contract/readme/CONTRIBUTORS.md
  base_ebill_payment_contract/readme/CREDITS.md
  base_ebill_payment_contract/readme/DESCRIPTION.md
  base_ebill_payment_contract/readme/USAGE.md
  base_ebill_payment_contract/security/ir.model.access.csv
  base_ebill_payment_contract/static/description/icon.png
  base_ebill_payment_contract/static/description/index.html
  base_ebill_payment_contract/tests/__init__.py
  base_ebill_payment_contract/tests/test_base_ebill_payment_contract.py
  base_ebill_payment_contract/views/ebill_payment_contract.xml
Labels: approved, ready to merge, bot is merging ⏳

#1115 [17.0][FIX] base_import_pdf_by_template_account: Preventing 2 attachments linked to the same invoice
  base_import_pdf_by_template_account/models/account_move.py
  base_import_pdf_by_template_account/tests/test_base_import_pdf_by_template_account.py
Labels: bot is merging ⏳

#1106 [14.0] edi: edi.conf add btn to view partners
  edi_oca/models/edi_configuration.py
  edi_oca/views/edi_configuration_views.xml
  edi_sale_oca/views/res_partner.xml
Labels: bot is merging ⏳
