Repository OCA/edi, pull requests merged in 2025-04, with the labels that each got.

#1138 [15.0][IMP] edi_voxel_stock_picking_oca: Remove HTML tags from picking note for Voxel compatibility
  edi_voxel_stock_picking_oca/reports/report_voxel_picking.py
  edi_voxel_stock_picking_oca/tests/test_voxel_stock_picking.py
Labels: approved, bot is merging ⏳

#1142 [15.0][IMP] edi_oca: add company_id field with multi-company rule
  edi_oca/models/edi_exchange_record.py
  edi_oca/security/ir_model_access.xml
  edi_oca/views/edi_exchange_record_views.xml
Labels: bot is merging ⏳

#1140 [16.0][IMP] account_invoice_factux: stop pinning factur-x lib
  account_invoice_facturx/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#1148 [17.0][IMP] base_import_pdf_by_template_account: Define a class for the import process
  base_import_pdf_by_template_account/models/account_move.py
  base_import_pdf_by_template_account/tests/test_base_import_pdf_by_template_account.py
Labels: approved, bot is merging ⏳

#1143 [18.0][MIG] edi_voxel_oca: Migration to 18.0
  edi_voxel_oca/README.rst
  edi_voxel_oca/__init__.py
  edi_voxel_oca/__manifest__.py
  edi_voxel_oca/data/data_voxel_uom.xml
  edi_voxel_oca/data/queue_job_channel_data.xml
  edi_voxel_oca/i18n/edi_voxel.pot
  edi_voxel_oca/i18n/edi_voxel_oca.pot
  edi_voxel_oca/i18n/es.po
  edi_voxel_oca/i18n/it.po
  edi_voxel_oca/models/__init__.py
  edi_voxel_oca/models/account.py
  edi_voxel_oca/models/queue_job.py
  edi_voxel_oca/models/res_company.py
  edi_voxel_oca/models/res_config_settings.py
  edi_voxel_oca/models/res_partner.py
  edi_voxel_oca/models/uom_uom.py
  edi_voxel_oca/models/voxel_login.py
  edi_voxel_oca/models/voxel_mixin.py
  edi_voxel_oca/pyproject.toml
  edi_voxel_oca/readme/CONTRIBUTORS.md
  edi_voxel_oca/readme/DESCRIPTION.md
  edi_voxel_oca/security/ir.model.access.csv
  edi_voxel_oca/security/voxel_security.xml
  edi_voxel_oca/static/description/icon.png
  edi_voxel_oca/static/description/index.html
  edi_voxel_oca/views/account_tax_views.xml
  edi_voxel_oca/views/product_uom_views.xml
  edi_voxel_oca/views/res_company_view.xml
  edi_voxel_oca/views/res_config_settings_views.xml
  edi_voxel_oca/views/res_partner_views.xml
  edi_voxel_oca/views/template_voxel_report.xml
  edi_voxel_oca/views/voxel_login_views.xml
Labels: approved

#1139 [16.0][IMP] account_invoice_facturx: add support for negative prices
  account_invoice_facturx/models/account_move.py
Labels: bot is merging ⏳
