Repository OCA/edi, pull requests merged in 2025-05, with the labels that each got.

#1154 [15.0][IMP] edi_voxel_account_invoice_oca: Add invoice reference for credit notes
  edi_voxel_account_invoice_oca/reports/report_voxel_invoice.py
Labels: approved, bot is merging ⏳

#1155 [15.0][IMP] base_import_pdf_by_template: Allow update records. Backport from e4bbd0f90cfc55f62e173767f56de34c7c5c270d
  base_import_pdf_by_template/security/security.xml
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload.py
Labels: approved, bot is merging ⏳

#1156 [15.0][IMP] base_import_pdf_by_template: Add dd/MM/Y format date + prevent time_format if not set
  base_import_pdf_by_template/models/base_import_pdf_template.py
Labels: approved, bot is merging ⏳

#1152 [18.0][MIG] edi_voxel_secondary_unit_oca: Migration to version 18.0
  edi_voxel_secondary_unit_oca/README.rst
  edi_voxel_secondary_unit_oca/__init__.py
  edi_voxel_secondary_unit_oca/__manifest__.py
  edi_voxel_secondary_unit_oca/i18n/edi_voxel_secondary_unit.pot
  edi_voxel_secondary_unit_oca/i18n/edi_voxel_secondary_unit_oca.pot
  edi_voxel_secondary_unit_oca/i18n/es.po
  edi_voxel_secondary_unit_oca/models/__init__.py
  edi_voxel_secondary_unit_oca/models/product_secondary_unit.py
  edi_voxel_secondary_unit_oca/pyproject.toml
  edi_voxel_secondary_unit_oca/readme/CONTRIBUTORS.md
  edi_voxel_secondary_unit_oca/readme/DESCRIPTION.md
  edi_voxel_secondary_unit_oca/readme/USAGE.md
  edi_voxel_secondary_unit_oca/static/description/icon.png
  edi_voxel_secondary_unit_oca/static/description/index.html
  edi_voxel_secondary_unit_oca/views/product_secondary_unit_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1158 [15.0][IMP] edi_oca: Add mute_logger to test to prevent confusion in logs
  edi_oca/tests/test_exchange_type.py
Labels: bot is merging ⏳
