Repository OCA/edi, pull requests merged in 2025-06, with the labels that each got.

#1161 [17.0][IMP] base_edi: update icon style
  base_edi/static/description/icon.png
  base_edi/static/description/icon.svg
Labels: approved, bot is merging ⏳

#1162 [18.0][IMP] base_edi: update icon style
  base_edi/static/description/icon.png
  base_edi/static/description/icon.svg
Labels: bot is merging ⏳

#1114 [IMP] product_import_ubl: wrapping of XPathGetter functions
  product_import_ubl/wizard/product_import.py
Labels: bot is merging ⏳, stale

#1165 [16.0][FW] sale_order_import: add confirm_order flag
  .oca/oca-port/blacklist/sale_order_import.json
  sale_order_import/tests/test_order_import.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_import/wizard/sale_order_import_view.xml
Labels: bot is merging ⏳

#1166 [16.0] sale_order_import: pre-commit align w/ 18
  sale_order_import/wizard/sale_order_import.py
Labels: bot is merging ⏳

#1090 [14.0][ADD] edi_sale_ubl_oca
  edi_sale_input_oca/components/process.py
  edi_sale_input_oca/tests/test_process.py
  edi_sale_ubl_input_oca/README.rst
  edi_sale_ubl_input_oca/__init__.py
  edi_sale_ubl_input_oca/__manifest__.py
  edi_sale_ubl_input_oca/demo/edi_exchange_type.xml
  edi_sale_ubl_input_oca/readme/CONTRIBUTORS.rst
  edi_sale_ubl_input_oca/readme/DESCRIPTION.rst
  edi_sale_ubl_input_oca/tests/__init__.py
  edi_sale_ubl_input_oca/tests/test_order_in.py
  edi_sale_ubl_input_oca/tests/test_order_in_full_flow.py
  edi_sale_ubl_oca/README.rst
  edi_sale_ubl_oca/__init__.py
  edi_sale_ubl_oca/__manifest__.py
  edi_sale_ubl_oca/components/__init__.py
  edi_sale_ubl_oca/components/listeners.py
  edi_sale_ubl_oca/data/edi_state.xml
  edi_sale_ubl_oca/demo/edi_exchange_type.xml
  edi_sale_ubl_oca/models/__init__.py
  edi_sale_ubl_oca/models/sale_order.py
  edi_sale_ubl_oca/readme/CONTRIBUTORS.rst
  edi_sale_ubl_oca/readme/DESCRIPTION.rst
  edi_sale_ubl_oca/tests/__init__.py
  edi_sale_ubl_oca/tests/common.py
  edi_sale_ubl_oca/tests/test_order_state.py
  edi_sale_ubl_oca/views/sale_order.xml
  edi_sale_ubl_output_oca/README.rst
  edi_sale_ubl_output_oca/__init__.py
  edi_sale_ubl_output_oca/__manifest__.py
  edi_sale_ubl_output_oca/demo/edi_exchange_type.xml
  edi_sale_ubl_output_oca/demo/exc_templ_order_response.xml
  edi_sale_ubl_output_oca/readme/CONTRIBUTORS.rst
  edi_sale_ubl_output_oca/readme/DESCRIPTION.rst
  edi_sale_ubl_output_oca/templates/qweb_tmpl_order_response.xml
  edi_sale_ubl_output_oca/templates/qweb_tmpl_party.xml
  edi_sale_ubl_output_oca/tests/__init__.py
  edi_sale_ubl_output_oca/tests/test_order_in_full_flow.py
  edi_sale_ubl_output_oca/tests/test_order_response_out.py
  setup/edi_sale_ubl_input_oca/odoo/addons/edi_sale_ubl_input_oca
  setup/edi_sale_ubl_input_oca/setup.py
  setup/edi_sale_ubl_oca/odoo/addons/edi_sale_ubl_oca
  setup/edi_sale_ubl_oca/setup.py
  setup/edi_sale_ubl_output_oca/odoo/addons/edi_sale_ubl_output_oca
  setup/edi_sale_ubl_output_oca/setup.py
Labels: bot is merging ⏳

#1167 [18.0][MIG] base_business_document_import
  base_business_document_import/README.rst
  base_business_document_import/__init__.py
  base_business_document_import/__manifest__.py
  base_business_document_import/i18n/base_business_document_import.pot
  base_business_document_import/i18n/cs_CZ.po
  base_business_document_import/i18n/es.po
  base_business_document_import/i18n/fr.po
  base_business_document_import/i18n/fr_FR.po
  base_business_document_import/i18n/it.po
  base_business_document_import/i18n/nl.po
  base_business_document_import/models/__init__.py
  base_business_document_import/models/business_document_import.py
  base_business_document_import/pyproject.toml
  base_business_document_import/readme/CONTRIBUTORS.md
  base_business_document_import/readme/DESCRIPTION.md
  base_business_document_import/static/description/icon.png
  base_business_document_import/static/description/index.html
  base_business_document_import/tests/__init__.py
  base_business_document_import/tests/test_business_document_import.py
Labels: bot is merging ⏳

#1174 [12.0][BACKPORT][IMP] edi_oca: Split exchange error and traceback
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_backend_input.py
  edi_oca/tests/test_backend_output.py
  edi_oca/tests/test_backend_process.py
  edi_oca/tests/test_backend_validate.py
  edi_oca/views/edi_exchange_record_views.xml
Labels: approved, bot is merging ⏳

#1171 [18.0][mig] sale_order_import
  sale_order_import/README.rst
  sale_order_import/__init__.py
  sale_order_import/__manifest__.py
  sale_order_import/i18n/es.po
  sale_order_import/i18n/fr.po
  sale_order_import/i18n/it.po
  sale_order_import/i18n/sale_order_import.pot
  sale_order_import/models/__init__.py
  sale_order_import/models/sale.py
  sale_order_import/pyproject.toml
  sale_order_import/readme/CONTRIBUTORS.md
  sale_order_import/readme/CREDITS.md
  sale_order_import/readme/DESCRIPTION.md
  sale_order_import/readme/USAGE.md
  sale_order_import/security/ir.model.access.csv
  sale_order_import/static/description/icon.png
  sale_order_import/static/description/index.html
  sale_order_import/tests/__init__.py
  sale_order_import/tests/common.py
  sale_order_import/tests/fixtures/test.pdf
  sale_order_import/tests/test_order_import.py
  sale_order_import/tests/test_parse_validate.py
  sale_order_import/tests/test_sale_order.py
  sale_order_import/wizard/__init__.py
  sale_order_import/wizard/sale_order_import.py
  sale_order_import/wizard/sale_order_import_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1176 [18.0][MIG] partner_identification_import
  partner_identification_import/README.rst
  partner_identification_import/__init__.py
  partner_identification_import/__manifest__.py
  partner_identification_import/i18n/es.po
  partner_identification_import/i18n/it.po
  partner_identification_import/i18n/partner_identification_import.pot
  partner_identification_import/models/__init__.py
  partner_identification_import/models/business_document_import.py
  partner_identification_import/pyproject.toml
  partner_identification_import/readme/CONTRIBUTORS.md
  partner_identification_import/readme/CREDITS.md
  partner_identification_import/readme/DESCRIPTION.md
  partner_identification_import/static/description/icon.png
  partner_identification_import/static/description/index.html
  partner_identification_import/tests/__init__.py
  partner_identification_import/tests/test_business_document_import.py
Labels: approved, bot is merging ⏳

#1175 [18.0][MIG] sale_order_import_ubl_line_customer_ref
  sale_order_import_ubl_line_customer_ref/README.rst
  sale_order_import_ubl_line_customer_ref/__init__.py
  sale_order_import_ubl_line_customer_ref/__manifest__.py
  sale_order_import_ubl_line_customer_ref/i18n/es.po
  sale_order_import_ubl_line_customer_ref/i18n/it.po
  sale_order_import_ubl_line_customer_ref/i18n/sale_order_import_ubl_line_customer_ref.pot
  sale_order_import_ubl_line_customer_ref/pyproject.toml
  sale_order_import_ubl_line_customer_ref/readme/CONTRIBUTORS.md
  sale_order_import_ubl_line_customer_ref/readme/DESCRIPTION.md
  sale_order_import_ubl_line_customer_ref/static/description/icon.png
  sale_order_import_ubl_line_customer_ref/static/description/index.html
  sale_order_import_ubl_line_customer_ref/tests/__init__.py
  sale_order_import_ubl_line_customer_ref/tests/test_order_line_customer_ref.py
  sale_order_import_ubl_line_customer_ref/wizard/__init__.py
  sale_order_import_ubl_line_customer_ref/wizard/sale_order_import.py
Labels: bot is merging ⏳

#1177 [17.0][FIX] base_import_pdf_by_template: Try to set default values to prevent side effects
  base_import_pdf_by_template/wizards/wizard_base_import_pdf_upload.py
Labels: approved, bot is merging ⏳

#1179 [FIX] account_invoice_import: avoid crash when XML date field has spaces or line returns
  account_invoice_import/wizard/account_invoice_import.py
Labels: bot is merging ⏳
