Repository OCA/edi, pull requests merged in 2025-07, with the labels that each got.

#1178 [18.0][FIX] sale_order_import: fix price source by pricelist
  sale_order_import/wizard/sale_order_import.py
Labels: approved, bot is merging ⏳

#1189 [18.0][MIG] sale_order_import_ubl_customer_free_ref: Migration to 18.0
  sale_order_import_ubl_customer_free_ref/README.rst
  sale_order_import_ubl_customer_free_ref/__init__.py
  sale_order_import_ubl_customer_free_ref/__manifest__.py
  sale_order_import_ubl_customer_free_ref/i18n/it.po
  sale_order_import_ubl_customer_free_ref/i18n/sale_order_import_ubl_customer_free_ref.pot
  sale_order_import_ubl_customer_free_ref/pyproject.toml
  sale_order_import_ubl_customer_free_ref/readme/CONTRIBUTORS.md
  sale_order_import_ubl_customer_free_ref/readme/DESCRIPTION.md
  sale_order_import_ubl_customer_free_ref/static/description/icon.png
  sale_order_import_ubl_customer_free_ref/static/description/index.html
  sale_order_import_ubl_customer_free_ref/tests/__init__.py
  sale_order_import_ubl_customer_free_ref/tests/files/UBL-Order-2.0-Example.xml
  sale_order_import_ubl_customer_free_ref/tests/files/UBL-Order-2.1-Example.xml
  sale_order_import_ubl_customer_free_ref/tests/files/UBL-Order-2.2-Example.xml
  sale_order_import_ubl_customer_free_ref/tests/test_ubl_order_import.py
  sale_order_import_ubl_customer_free_ref/wizard/__init__.py
  sale_order_import_ubl_customer_free_ref/wizard/sale_order_import.py
Labels: bot is merging ⏳

#1199 [15.0][IMP] edi_voxel_account_invoice_oca: Add tax base amount and description to invoice report
  edi_voxel_account_invoice_oca/reports/report_voxel_invoice.py
  edi_voxel_account_invoice_oca/tests/test_voxel_account_invoice.py
Labels: approved, bot is merging ⏳

#1191 [18.0] [MIG] account_invoice_export: Migration to 18.0
  account_invoice_export/README.rst
  account_invoice_export/__init__.py
  account_invoice_export/__manifest__.py
  account_invoice_export/data/mail_activity_type.xml
  account_invoice_export/i18n/account_invoice_export.pot
  account_invoice_export/i18n/it.po
  account_invoice_export/models/__init__.py
  account_invoice_export/models/account_move.py
  account_invoice_export/models/transmit_method.py
  account_invoice_export/pyproject.toml
  account_invoice_export/readme/CONTRIBUTORS.md
  account_invoice_export/readme/CREDITS.md
  account_invoice_export/readme/DESCRIPTION.md
  account_invoice_export/static/description/icon.png
  account_invoice_export/static/description/index.html
  account_invoice_export/tests/__init__.py
  account_invoice_export/tests/common.py
  account_invoice_export/tests/test_export_invoice.py
  account_invoice_export/views/account_move.xml
  account_invoice_export/views/message_template.xml
  account_invoice_export/views/transmit_method.xml
Labels: approved, ready to merge, bot is merging ⏳

#1192 [18.0] [MIG] account_invoice_export_server_env: Migration to 18.0
  account_invoice_export_server_env/README.rst
  account_invoice_export_server_env/__init__.py
  account_invoice_export_server_env/__manifest__.py
  account_invoice_export_server_env/i18n/account_invoice_export_server_env.pot
  account_invoice_export_server_env/i18n/es.po
  account_invoice_export_server_env/i18n/it.po
  account_invoice_export_server_env/models/__init__.py
  account_invoice_export_server_env/models/transmit_method.py
  account_invoice_export_server_env/pyproject.toml
  account_invoice_export_server_env/readme/CREDITS.md
  account_invoice_export_server_env/readme/DESCRIPTION.md
  account_invoice_export_server_env/static/description/icon.png
  account_invoice_export_server_env/static/description/index.html
  account_invoice_export_server_env/tests/__init__.py
  account_invoice_export_server_env/tests/test_transmit_method.py
  account_invoice_export_server_env/tests/testfiles/test/test.conf
Labels: approved, ready to merge, bot is merging ⏳

#1196 [18.0][MIG] sale_order_import_packaging (renamed from sale_order_packaging_import)
  sale_order_import_packaging/README.rst
  sale_order_import_packaging/__init__.py
  sale_order_import_packaging/__manifest__.py
  sale_order_import_packaging/i18n/es.po
  sale_order_import_packaging/i18n/it.po
  sale_order_import_packaging/i18n/sale_order_packaging_import.pot
  sale_order_import_packaging/models/__init__.py
  sale_order_import_packaging/models/business_document_import.py
  sale_order_import_packaging/pyproject.toml
  sale_order_import_packaging/readme/CONTRIBUTORS.md
  sale_order_import_packaging/readme/DESCRIPTION.md
  sale_order_import_packaging/static/description/icon.png
  sale_order_import_packaging/static/description/index.html
  sale_order_import_packaging/tests/__init__.py
  sale_order_import_packaging/tests/test_order_line_packaging_import.py
  sale_order_import_packaging/wizard/__init__.py
  sale_order_import_packaging/wizard/sale_order_import.py
Labels: bot is merging ⏳

#1202 [18.0][mig] base_ebill_payment_contract
  base_ebill_payment_contract/README.rst
  base_ebill_payment_contract/__init__.py
  base_ebill_payment_contract/__manifest__.py
  base_ebill_payment_contract/demo/ebill_payment_contract.xml
  base_ebill_payment_contract/i18n/base_ebill_payment_contract.pot
  base_ebill_payment_contract/i18n/es.po
  base_ebill_payment_contract/i18n/it.po
  base_ebill_payment_contract/models/__init__.py
  base_ebill_payment_contract/models/ebill_payment_contract.py
  base_ebill_payment_contract/models/res_partner.py
  base_ebill_payment_contract/pyproject.toml
  base_ebill_payment_contract/readme/CONTRIBUTORS.md
  base_ebill_payment_contract/readme/CREDITS.md
  base_ebill_payment_contract/readme/DESCRIPTION.md
  base_ebill_payment_contract/readme/USAGE.md
  base_ebill_payment_contract/security/ir.model.access.csv
  base_ebill_payment_contract/static/description/icon.png
  base_ebill_payment_contract/static/description/index.html
  base_ebill_payment_contract/tests/__init__.py
  base_ebill_payment_contract/tests/test_base_ebill_payment_contract.py
  base_ebill_payment_contract/views/ebill_payment_contract.xml
Labels: bot is merging ⏳
